$axure.loadCurrentPage({
  "url":"分组设置.html",
  "generationDate":new Date(1515736335823),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"22ffd0fe7139429bbebe6377ac292c32",
    "type":"Axure:Page",
    "name":"分组设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"926d9100c9bf478aa469ea708e5833cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":186},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"087c327597f0433dbf0cd15e59edc718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":186},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"364f4d03b7cb4385bcb6514f594bdfc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "verticalAlignment":"top",
            "location":{
              "x":90,
              "y":226},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3829b28aedd945d7bc47a67624e1b208",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "verticalAlignment":"top",
                "location":{
                  "x":90,
                  "y":226},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"823c37380378464eabd29bff184fde9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":248},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa386570977b4ca288fd4aa0ee315dd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":248},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"585430ff0c094061ad504453b4aaa5be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":90,
              "y":186},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9106fc621d634c66a784b98d56105152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":90,
                  "y":186},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"02e99ada893d47d7b1ad64c2e79c94a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":400,
              "y":280},
            "size":{
              "width":130,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf8b4ee207a1451fb48d4bf5662d14aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":400,
                  "y":280},
                "size":{
                  "width":130,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec1baf6ec82c44f0916a43af9160686e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":516,
              "y":290},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea4b8420492e41aeb7d2cae99ab17041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":516,
                  "y":290},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u42.png"}},
{
          "id":"a1bc261a0e8a47a88645ee507c80be02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":740,
              "y":242},
            "size":{
              "width":90,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25ff09b11c8646d7b38d8066e16eb059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":740,
                  "y":242},
                "size":{
                  "width":90,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"340f861e5a6e4d6293f26664e7b2433b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":326},
            "size":{
              "width":50,
              "height":52}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b8b190322d6484990f2dec5905e3d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":326},
                "size":{
                  "width":50,
                  "height":52}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u14.png"}},
{
          "id":"7d14a4fb21d54f1db8aa0f955c24c478",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":90,
              "y":388},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"3aa2c435a6544678a378f1c73e091ab2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":160,
              "y":326},
            "size":{
              "width":110,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b23644be1fd247598444e1ab5d81c6bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":160,
                  "y":326},
                "size":{
                  "width":110,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c500cc5459f94910929003ea24b3b3e1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":642},
            "size":{
              "width":218,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/分组设置/u19_line.png"}},
{
          "id":"ad31159e8b3d4f7a95d455ac5f161565",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":990,
              "y":164},
            "size":{
              "width":440,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f48ec63998451398d55304de8473ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":990,
                  "y":164},
                "size":{
                  "width":440,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u20.png"}},
{
          "id":"9bea0938c02046b1b293c51c89c72226",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1160,
              "y":180},
            "size":{
              "width":125,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b33e24698ea467da0acb901cc685cb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1160,
                  "y":180},
                "size":{
                  "width":125,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2336b515cb9946febf65d5fea26bd368",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1125,
              "y":232},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7f50d387604dc3862bcaf0c3105a43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1125,
                  "y":232},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b3efcfdd84c452bb79e548b142716de",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":1075,
              "y":282},
            "size":{
              "width":270,
              "height":46}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入分组名称，限10字内"},
{
          "id":"9bc5a3f176524b3799085d2abf658853",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":990,
              "y":356},
            "size":{
              "width":440,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/分组设置/u27_line.png"}},
{
          "id":"a228648d4e9e430db5102ab2a1ecf65f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":990,
              "y":362},
            "size":{
              "width":210,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0d896dfb2e1461899db0d96abff069b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":990,
                  "y":362},
                "size":{
                  "width":210,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c7384438e2d4c7abe75b091dad427f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1200,
              "y":362},
            "size":{
              "width":230,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26fdc48e95fa4d719fa163a962930f88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1200,
                  "y":362},
                "size":{
                  "width":230,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"524f3bf1af3047e2a586ca212a3aebff",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":90,
              "y":464},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"0c7538f901ca47eab68c44051bd75b7d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":412},
            "size":{
              "width":50,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"331a9332a2324daab7867ecc90d68114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":412},
                "size":{
                  "width":50,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建育人活动/u105.png"}},
{
          "id":"df7ef40247604740af23375a7d3cbb67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":160,
              "y":406},
            "size":{
              "width":110,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0640d4505f2948e99b0327bb0c151433",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":160,
                  "y":406},
                "size":{
                  "width":110,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75922f40bc464b19957d415eb2d2f279",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":633,
              "y":416.5},
            "size":{
              "width":37,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e16cd0c069414b49b08b96a9da844a29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":633,
                  "y":416.5},
                "size":{
                  "width":37,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u37.png"}},
{
          "id":"5d846cdf0e894c96aee371845766f6b4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":90,
              "y":542},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"879b54b1613f4d3c9ae6adb0fe65398a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":490},
            "size":{
              "width":50,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7924c9f29cee440b9976e3c78cd37aac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":490},
                "size":{
                  "width":50,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建育人活动/u105.png"}},
{
          "id":"a84335fc24a84651a45f997ba69c2df5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":160,
              "y":484},
            "size":{
              "width":110,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d52de677ae947649555cbbf70885a96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":160,
                  "y":484},
                "size":{
                  "width":110,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"159ae149920245ef88ea07ef1c5e425f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":766,
              "y":496},
            "size":{
              "width":37,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88a7d3d953434e97b6f27377d1db01aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":766,
                  "y":496},
                "size":{
                  "width":37,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u37.png"}},
{
          "id":"6a63cb9afdfb4aabb306119ed32c4876",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":90,
              "y":610},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"ea6a02e8c29f409fac4092519b397fc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":558},
            "size":{
              "width":50,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7c22761723d4e49ab1b58e22d6d1c31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":558},
                "size":{
                  "width":50,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建育人活动/u105.png"}},
{
          "id":"04b864d73ec24ff5aa1f0a5da81c50f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":160,
              "y":552},
            "size":{
              "width":110,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac119f8b3497426f8b14c17e90ab5148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":160,
                  "y":552},
                "size":{
                  "width":110,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bb810577ca74ac98fb4ca9f96583246",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":766,
              "y":564},
            "size":{
              "width":37,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c523444d5d44fd5a6f02b714d6e8ee2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":766,
                  "y":564},
                "size":{
                  "width":37,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u37.png"}},
{
          "id":"ee90973aad2340ba967514ccf172b38a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":90,
              "y":678},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"9e7947b469a94f92beb66d3c08703f18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":626},
            "size":{
              "width":50,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7fe74db4fb644809e15dfbe2e871526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":626},
                "size":{
                  "width":50,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建育人活动/u105.png"}},
{
          "id":"e838c3be34c24cbe9e1898f8448823a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":160,
              "y":620},
            "size":{
              "width":110,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbe4af567559430e95dc2ec1296c0973",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":160,
                  "y":620},
                "size":{
                  "width":110,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f357f7a24b844e15a7200425f52f51df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":766,
              "y":632},
            "size":{
              "width":37,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89f0f6911978447b84660a4f8b3346fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":766,
                  "y":632},
                "size":{
                  "width":37,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u37.png"}},
{
          "id":"fa74849eb50b4789ac00ebaf60f71951",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":360},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/学生管理/u46_line.png"}},
{
          "id":"6f2e2aee48fd4e37a1c3daa4aa0326f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":1030,
              "y":620.5},
            "size":{
              "width":377,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0280269a83994d6e97fd7f69024d364b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":1030,
                  "y":620.5},
                "size":{
                  "width":377,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u61.png"}},
{
          "id":"34a0f73fad57401b8bef40f4c0a91cbc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":574},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/学生管理/u46_line.png"}},
{
          "id":"eeb1d229deef4aaa8a64cf7ef635520b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":1030,
              "y":512},
            "size":{
              "width":540,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90250601e2c345c8bd4375367c8b1e1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":1030,
                  "y":512},
                "size":{
                  "width":540,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u64.png"}},
{
          "id":"10425552dee743699274275e99409948",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":428},
            "size":{
              "width":350,
              "height":264}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b59105fa97354680ace253df6018d5d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1580,
                  "y":428},
                "size":{
                  "width":350,
                  "height":264}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生管理/u59.png"}},
{
          "id":"2506cc1ab05740c89945fdc828595a72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1692,
              "y":438},
            "size":{
              "width":125,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c11b9921ac8b4d02aa28a07dbfcc7223",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1692,
                  "y":438},
                "size":{
                  "width":125,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2976629544b1400bbeb2dded29ff235b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1670,
              "y":486},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8166b39a6454cfbbfca05e286835b85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1670,
                  "y":486},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcff9e2e852d4367a886a38ad06dffe1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":1646,
              "y":536},
            "size":{
              "width":220,
              "height":46}},
          "adaptiveStyles":{
},
          "placeholderText":"请输入分组名称"},
{
          "id":"d1a97d0351474b2e819ae8ddb6c4b249",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":1580,
              "y":620},
            "size":{
              "width":350,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/学生管理/u63_line.png"}},
{
          "id":"59ace2d76a94408f8c2c8ccf03cf0a13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1580,
              "y":626},
            "size":{
              "width":170,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4357d4aac3974955825321080e7ab4b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1580,
                  "y":626},
                "size":{
                  "width":170,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ddf32c891a44d5ba5fe97103e22bfc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":1760,
              "y":626},
            "size":{
              "width":170,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7102ffaf82482e9dff2ad2bfd4bc0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1760,
                  "y":626},
                "size":{
                  "width":170,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dd9e9913e2e4e358aa31bec097f9af5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":557,
              "y":412.5},
            "size":{
              "width":39,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"043eca1d60b848d998c4eaab99498ece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":557,
                  "y":412.5},
                "size":{
                  "width":39,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u78.png"}},
{
          "id":"7e8feb7efc53452787c4e7a9d64707f6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":492},
            "size":{
              "width":39,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e1afbf3a18a4d2192c191c89ec413e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":492},
                "size":{
                  "width":39,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u78.png"}},
{
          "id":"725f8bf606c14f2293faacebd52b4c64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":560},
            "size":{
              "width":39,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf17a77378b84baf894f3d2a3cfb1740",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":560},
                "size":{
                  "width":39,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u78.png"}},
{
          "id":"0d5386d8908843178a8b5e125bea8f26",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":628},
            "size":{
              "width":39,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e93db8073a74628a01b50e3d48520d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":628},
                "size":{
                  "width":39,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u78.png"}},
{
          "id":"bafa1332a1a34239b113e4670655bd15",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":700},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"167696e6d599412f8234e53638e3cc89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":700},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"538e1d219711409588ad4ba3cb7b4996",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":1002,
              "y":786},
            "size":{
              "width":377,
              "height":55}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec4318e664cf4db697c7a159b9dbc8cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":1002,
                  "y":786},
                "size":{
                  "width":377,
                  "height":55}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u61.png"}},
{
          "id":"7ba72a52e5464dddaa844b83db523922",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":90,
              "y":90},
            "size":{
              "width":750,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a4b09900b7413e8b385aaa1e295c79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":90,
                  "y":90},
                "size":{
                  "width":750,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u90.png"}},
{
          "id":"d05fd4767a6345719e9ab950e1de8885",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":700,
              "y":393},
            "size":{
              "width":140,
              "height":77},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d77c497bc25342379dee9345cb509378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":700,
                  "y":393},
                "size":{
                  "width":140,
                  "height":77},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分组设置/u92.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "926d9100c9bf478aa469ea708e5833cf":{
      "scriptId":"u0"},
    "087c327597f0433dbf0cd15e59edc718":{
      "scriptId":"u1"},
    "364f4d03b7cb4385bcb6514f594bdfc4":{
      "scriptId":"u2"},
    "3829b28aedd945d7bc47a67624e1b208":{
      "scriptId":"u3"},
    "823c37380378464eabd29bff184fde9e":{
      "scriptId":"u4"},
    "aa386570977b4ca288fd4aa0ee315dd3":{
      "scriptId":"u5"},
    "585430ff0c094061ad504453b4aaa5be":{
      "scriptId":"u6"},
    "9106fc621d634c66a784b98d56105152":{
      "scriptId":"u7"},
    "02e99ada893d47d7b1ad64c2e79c94a6":{
      "scriptId":"u8"},
    "bf8b4ee207a1451fb48d4bf5662d14aa":{
      "scriptId":"u9"},
    "ec1baf6ec82c44f0916a43af9160686e":{
      "scriptId":"u10"},
    "ea4b8420492e41aeb7d2cae99ab17041":{
      "scriptId":"u11"},
    "a1bc261a0e8a47a88645ee507c80be02":{
      "scriptId":"u12"},
    "25ff09b11c8646d7b38d8066e16eb059":{
      "scriptId":"u13"},
    "340f861e5a6e4d6293f26664e7b2433b":{
      "scriptId":"u14"},
    "8b8b190322d6484990f2dec5905e3d74":{
      "scriptId":"u15"},
    "7d14a4fb21d54f1db8aa0f955c24c478":{
      "scriptId":"u16"},
    "3aa2c435a6544678a378f1c73e091ab2":{
      "scriptId":"u17"},
    "b23644be1fd247598444e1ab5d81c6bc":{
      "scriptId":"u18"},
    "c500cc5459f94910929003ea24b3b3e1":{
      "scriptId":"u19"},
    "ad31159e8b3d4f7a95d455ac5f161565":{
      "scriptId":"u20"},
    "d7f48ec63998451398d55304de8473ce":{
      "scriptId":"u21"},
    "9bea0938c02046b1b293c51c89c72226":{
      "scriptId":"u22"},
    "1b33e24698ea467da0acb901cc685cb4":{
      "scriptId":"u23"},
    "2336b515cb9946febf65d5fea26bd368":{
      "scriptId":"u24"},
    "ce7f50d387604dc3862bcaf0c3105a43":{
      "scriptId":"u25"},
    "7b3efcfdd84c452bb79e548b142716de":{
      "scriptId":"u26"},
    "9bc5a3f176524b3799085d2abf658853":{
      "scriptId":"u27"},
    "a228648d4e9e430db5102ab2a1ecf65f":{
      "scriptId":"u28"},
    "e0d896dfb2e1461899db0d96abff069b":{
      "scriptId":"u29"},
    "0c7384438e2d4c7abe75b091dad427f6":{
      "scriptId":"u30"},
    "26fdc48e95fa4d719fa163a962930f88":{
      "scriptId":"u31"},
    "524f3bf1af3047e2a586ca212a3aebff":{
      "scriptId":"u32"},
    "0c7538f901ca47eab68c44051bd75b7d":{
      "scriptId":"u33"},
    "331a9332a2324daab7867ecc90d68114":{
      "scriptId":"u34"},
    "df7ef40247604740af23375a7d3cbb67":{
      "scriptId":"u35"},
    "0640d4505f2948e99b0327bb0c151433":{
      "scriptId":"u36"},
    "75922f40bc464b19957d415eb2d2f279":{
      "scriptId":"u37"},
    "e16cd0c069414b49b08b96a9da844a29":{
      "scriptId":"u38"},
    "5d846cdf0e894c96aee371845766f6b4":{
      "scriptId":"u39"},
    "879b54b1613f4d3c9ae6adb0fe65398a":{
      "scriptId":"u40"},
    "7924c9f29cee440b9976e3c78cd37aac":{
      "scriptId":"u41"},
    "a84335fc24a84651a45f997ba69c2df5":{
      "scriptId":"u42"},
    "0d52de677ae947649555cbbf70885a96":{
      "scriptId":"u43"},
    "159ae149920245ef88ea07ef1c5e425f":{
      "scriptId":"u44"},
    "88a7d3d953434e97b6f27377d1db01aa":{
      "scriptId":"u45"},
    "6a63cb9afdfb4aabb306119ed32c4876":{
      "scriptId":"u46"},
    "ea6a02e8c29f409fac4092519b397fc0":{
      "scriptId":"u47"},
    "b7c22761723d4e49ab1b58e22d6d1c31":{
      "scriptId":"u48"},
    "04b864d73ec24ff5aa1f0a5da81c50f8":{
      "scriptId":"u49"},
    "ac119f8b3497426f8b14c17e90ab5148":{
      "scriptId":"u50"},
    "7bb810577ca74ac98fb4ca9f96583246":{
      "scriptId":"u51"},
    "9c523444d5d44fd5a6f02b714d6e8ee2":{
      "scriptId":"u52"},
    "ee90973aad2340ba967514ccf172b38a":{
      "scriptId":"u53"},
    "9e7947b469a94f92beb66d3c08703f18":{
      "scriptId":"u54"},
    "d7fe74db4fb644809e15dfbe2e871526":{
      "scriptId":"u55"},
    "e838c3be34c24cbe9e1898f8448823a3":{
      "scriptId":"u56"},
    "bbe4af567559430e95dc2ec1296c0973":{
      "scriptId":"u57"},
    "f357f7a24b844e15a7200425f52f51df":{
      "scriptId":"u58"},
    "89f0f6911978447b84660a4f8b3346fd":{
      "scriptId":"u59"},
    "fa74849eb50b4789ac00ebaf60f71951":{
      "scriptId":"u60"},
    "6f2e2aee48fd4e37a1c3daa4aa0326f6":{
      "scriptId":"u61"},
    "0280269a83994d6e97fd7f69024d364b":{
      "scriptId":"u62"},
    "34a0f73fad57401b8bef40f4c0a91cbc":{
      "scriptId":"u63"},
    "eeb1d229deef4aaa8a64cf7ef635520b":{
      "scriptId":"u64"},
    "90250601e2c345c8bd4375367c8b1e1e":{
      "scriptId":"u65"},
    "10425552dee743699274275e99409948":{
      "scriptId":"u66"},
    "b59105fa97354680ace253df6018d5d1":{
      "scriptId":"u67"},
    "2506cc1ab05740c89945fdc828595a72":{
      "scriptId":"u68"},
    "c11b9921ac8b4d02aa28a07dbfcc7223":{
      "scriptId":"u69"},
    "2976629544b1400bbeb2dded29ff235b":{
      "scriptId":"u70"},
    "e8166b39a6454cfbbfca05e286835b85":{
      "scriptId":"u71"},
    "fcff9e2e852d4367a886a38ad06dffe1":{
      "scriptId":"u72"},
    "d1a97d0351474b2e819ae8ddb6c4b249":{
      "scriptId":"u73"},
    "59ace2d76a94408f8c2c8ccf03cf0a13":{
      "scriptId":"u74"},
    "4357d4aac3974955825321080e7ab4b4":{
      "scriptId":"u75"},
    "0ddf32c891a44d5ba5fe97103e22bfc9":{
      "scriptId":"u76"},
    "ce7102ffaf82482e9dff2ad2bfd4bc0b":{
      "scriptId":"u77"},
    "7dd9e9913e2e4e358aa31bec097f9af5":{
      "scriptId":"u78"},
    "043eca1d60b848d998c4eaab99498ece":{
      "scriptId":"u79"},
    "7e8feb7efc53452787c4e7a9d64707f6":{
      "scriptId":"u80"},
    "5e1afbf3a18a4d2192c191c89ec413e8":{
      "scriptId":"u81"},
    "725f8bf606c14f2293faacebd52b4c64":{
      "scriptId":"u82"},
    "cf17a77378b84baf894f3d2a3cfb1740":{
      "scriptId":"u83"},
    "0d5386d8908843178a8b5e125bea8f26":{
      "scriptId":"u84"},
    "3e93db8073a74628a01b50e3d48520d4":{
      "scriptId":"u85"},
    "bafa1332a1a34239b113e4670655bd15":{
      "scriptId":"u86"},
    "167696e6d599412f8234e53638e3cc89":{
      "scriptId":"u87"},
    "538e1d219711409588ad4ba3cb7b4996":{
      "scriptId":"u88"},
    "ec4318e664cf4db697c7a159b9dbc8cd":{
      "scriptId":"u89"},
    "7ba72a52e5464dddaa844b83db523922":{
      "scriptId":"u90"},
    "10a4b09900b7413e8b385aaa1e295c79":{
      "scriptId":"u91"},
    "d05fd4767a6345719e9ab950e1de8885":{
      "scriptId":"u92"},
    "d77c497bc25342379dee9345cb509378":{
      "scriptId":"u93"}}});