$axure.loadCurrentPage({
  "url":"编辑活动.html",
  "generationDate":new Date(1515736336692),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6e383ffa672747fbb1ae37ec17282ee3",
    "type":"Axure:Page",
    "name":"编辑活动",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f922c4957f184fe0be6bf286c83b1dc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":56},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27f3b2abc2c044c99a1c289999ff840b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":56},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"c8ff37329de44d4f9cca216cc02229a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":50,
              "y":96},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae6ca2650af24c54931170fdbe51b270",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":50,
                  "y":96},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"16d670fc6ea347aeb3026de368027c75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":117},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10ad803257fd40599993640ba510f116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":117},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动详情",
                      "target":{
                        "targetType":"page",
                        "url":"活动详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"58b11740271f4f25b465a6fd9fcdd31e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":50,
              "y":56},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bc7e8d530784891b9c6f6d2813d1240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":50,
                  "y":56},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"d6ee722bc12942589c74a19f3ab80fb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":66,
              "y":198},
            "size":{
              "width":154,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cdb28a1861648198d6fcd951f02b76e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":198},
                "size":{
                  "width":154,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ab8860a082545e9b558a7cc74fcd77b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":50,
              "y":260},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"854606e97ce947bdaa905892c3c12e96",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":215,
              "y":205},
            "size":{
              "width":410,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"0adef169787f476f9b88ab60a5152551",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":630,
              "y":198},
            "size":{
              "width":160,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b2b84c3312143739a33a86abff765d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":630,
                  "y":198},
                "size":{
                  "width":160,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e567d4ae871841b3987bf7c9dc3ac12f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":50,
              "y":260},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"4b0c754804704b52998c10199da59171",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":66,
              "y":273},
            "size":{
              "width":224,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9a6ade64f954e53a67d2591e300b43b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":273},
                "size":{
                  "width":224,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"daecd1ff2eb24245bafdf25684c54012",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":343},
            "size":{
              "width":555,
              "height":221}},
          "adaptiveStyles":{
}},
{
          "id":"107dade239b74840aad926db3fccf090",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":505,
              "y":564},
            "size":{
              "width":285,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5202ccf42a4b68924fb46869047ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":505,
                  "y":564},
                "size":{
                  "width":285,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4bb728da7aca447e9c01e500c4daaa54",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":50,
              "y":1318},
            "size":{
              "width":750,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71757dbd4bfd4b63acdc87fb11224bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":50,
                  "y":1318},
                "size":{
                  "width":750,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 活动详情",
                      "target":{
                        "targetType":"page",
                        "url":"活动详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/创建育人活动/u22.png"}},
{
          "id":"a446050fea8d4df58bb340ddc86bd7d4",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":185,
              "y":831},
            "size":{
              "width":170,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1795990b09134bbdab4d9ed315e82c54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":185,
                  "y":831},
                "size":{
                  "width":170,
                  "height":28}},
              "adaptiveStyles":{
}}]},
{
          "id":"90785e62eb874ab98500a2f4c0b6921b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":455,
              "y":831},
            "size":{
              "width":170,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f0f7e303a9b40229bb8ced2877707df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":455,
                  "y":831},
                "size":{
                  "width":170,
                  "height":28}},
              "adaptiveStyles":{
}}]},
{
          "id":"b188cafda10b4f54b9e4cbf29aa53d52",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":185,
              "y":897},
            "size":{
              "width":170,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"327a6ae1c9fa492fbefe8d8120c79868",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":185,
                  "y":897},
                "size":{
                  "width":170,
                  "height":28}},
              "adaptiveStyles":{
}}]},
{
          "id":"cee4cdc769fb417b8dda53f7ec2fd513",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":185,
              "y":765},
            "size":{
              "width":170,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab062d59c0244e4c9103870de6873d92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":185,
                  "y":765},
                "size":{
                  "width":170,
                  "height":28}},
              "adaptiveStyles":{
}}]},
{
          "id":"36b55c264b6745aabf8cbaffde0f8e63",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":50,
              "y":951},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"9889fdf23e7a4b8cb055531efb4f1f77",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":50,
              "y":740},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"ff4ebeb8b141480baf83e286d0397775",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":66,
              "y":670},
            "size":{
              "width":705,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4628f8b6ef84825868a794a4ca49491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":670},
                "size":{
                  "width":705,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c67e99582d1941d8b820ef960cc182bf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":50,
              "y":650},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"59b8d9d6d7464f49b6b3b8090b48a546",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":66,
              "y":979},
            "size":{
              "width":693,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27c582868daa4e11aa96634979c5e68f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":66,
                  "y":979},
                "size":{
                  "width":693,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dad369480444666b8406656bc6c2a95",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":226,
              "y":366},
            "size":{
              "width":514,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0b8f455e3424fbfb9ea9ca168932d35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":226,
                  "y":366},
                "size":{
                  "width":514,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"009c24af2a2746468bf2dbb53e0a6f31",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":854},
            "size":{
              "width":99,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/管理员、老师/u390_line.png"}},
{
          "id":"fac5766dadbe4e21864bad20a67d2dd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":860,
              "y":819},
            "size":{
              "width":310,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e85c8f7d558547cba9cb07bdaef244b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":860,
                  "y":819},
                "size":{
                  "width":310,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑活动/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f922c4957f184fe0be6bf286c83b1dc1":{
      "scriptId":"u0"},
    "27f3b2abc2c044c99a1c289999ff840b":{
      "scriptId":"u1"},
    "c8ff37329de44d4f9cca216cc02229a0":{
      "scriptId":"u2"},
    "ae6ca2650af24c54931170fdbe51b270":{
      "scriptId":"u3"},
    "16d670fc6ea347aeb3026de368027c75":{
      "scriptId":"u4"},
    "10ad803257fd40599993640ba510f116":{
      "scriptId":"u5"},
    "58b11740271f4f25b465a6fd9fcdd31e":{
      "scriptId":"u6"},
    "6bc7e8d530784891b9c6f6d2813d1240":{
      "scriptId":"u7"},
    "d6ee722bc12942589c74a19f3ab80fb5":{
      "scriptId":"u8"},
    "0cdb28a1861648198d6fcd951f02b76e":{
      "scriptId":"u9"},
    "0ab8860a082545e9b558a7cc74fcd77b":{
      "scriptId":"u10"},
    "854606e97ce947bdaa905892c3c12e96":{
      "scriptId":"u11"},
    "0adef169787f476f9b88ab60a5152551":{
      "scriptId":"u12"},
    "1b2b84c3312143739a33a86abff765d3":{
      "scriptId":"u13"},
    "e567d4ae871841b3987bf7c9dc3ac12f":{
      "scriptId":"u14"},
    "4b0c754804704b52998c10199da59171":{
      "scriptId":"u15"},
    "a9a6ade64f954e53a67d2591e300b43b":{
      "scriptId":"u16"},
    "daecd1ff2eb24245bafdf25684c54012":{
      "scriptId":"u17"},
    "107dade239b74840aad926db3fccf090":{
      "scriptId":"u18"},
    "0f5202ccf42a4b68924fb46869047ebd":{
      "scriptId":"u19"},
    "4bb728da7aca447e9c01e500c4daaa54":{
      "scriptId":"u20"},
    "71757dbd4bfd4b63acdc87fb11224bed":{
      "scriptId":"u21"},
    "a446050fea8d4df58bb340ddc86bd7d4":{
      "scriptId":"u22"},
    "1795990b09134bbdab4d9ed315e82c54":{
      "scriptId":"u23"},
    "90785e62eb874ab98500a2f4c0b6921b":{
      "scriptId":"u24"},
    "8f0f7e303a9b40229bb8ced2877707df":{
      "scriptId":"u25"},
    "b188cafda10b4f54b9e4cbf29aa53d52":{
      "scriptId":"u26"},
    "327a6ae1c9fa492fbefe8d8120c79868":{
      "scriptId":"u27"},
    "cee4cdc769fb417b8dda53f7ec2fd513":{
      "scriptId":"u28"},
    "ab062d59c0244e4c9103870de6873d92":{
      "scriptId":"u29"},
    "36b55c264b6745aabf8cbaffde0f8e63":{
      "scriptId":"u30"},
    "9889fdf23e7a4b8cb055531efb4f1f77":{
      "scriptId":"u31"},
    "ff4ebeb8b141480baf83e286d0397775":{
      "scriptId":"u32"},
    "e4628f8b6ef84825868a794a4ca49491":{
      "scriptId":"u33"},
    "c67e99582d1941d8b820ef960cc182bf":{
      "scriptId":"u34"},
    "59b8d9d6d7464f49b6b3b8090b48a546":{
      "scriptId":"u35"},
    "27c582868daa4e11aa96634979c5e68f":{
      "scriptId":"u36"},
    "0dad369480444666b8406656bc6c2a95":{
      "scriptId":"u37"},
    "e0b8f455e3424fbfb9ea9ca168932d35":{
      "scriptId":"u38"},
    "009c24af2a2746468bf2dbb53e0a6f31":{
      "scriptId":"u39"},
    "fac5766dadbe4e21864bad20a67d2dd3":{
      "scriptId":"u40"},
    "e85c8f7d558547cba9cb07bdaef244b7":{
      "scriptId":"u41"}}});