$axure.loadCurrentPage({
  "url":"得分明细.html",
  "generationDate":new Date(1515736339800),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9131188c021946df8bdf90cf29e4a8de",
    "type":"Axure:Page",
    "name":"得分明细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cdced877154642c586b554ff27c0902c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":168},
            "size":{
              "width":750,
              "height":1204},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc0df088db3a4941942908d167810597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":168},
                "size":{
                  "width":750,
                  "height":1204},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u0.png"}},
{
          "id":"11de7db0e8784ab89cd0118d1c763b5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "verticalAlignment":"top",
            "location":{
              "x":60,
              "y":65},
            "size":{
              "width":750,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cca9a4645fc48fb98e7cda9329bdec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "verticalAlignment":"top",
                "location":{
                  "x":60,
                  "y":65},
                "size":{
                  "width":750,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/得分明细/u2.png"}},
{
          "id":"6d44cc2b998549009afde398e97ada2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":100},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40a2ee4289d4046af6fa998e8e6b4bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":100},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"4112a2b81f7e4c42bc090cdb242892dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":58,
              "y":25},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7f0b44233474fd0a27da67a520bbdfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":58,
                  "y":25},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"7bf638a75ef941cc9b2403e53a1d3fe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":64,
              "y":170},
            "size":{
              "width":742,
              "height":132},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"999b701afb8c4d509c60b554286e6480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":64,
                  "y":170},
                "size":{
                  "width":742,
                  "height":132},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u8.png"}},
{
          "id":"75e47fdc33b9412d940d673883ef6595",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":156,
              "y":170},
            "size":{
              "width":202,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae4e8f7f216f44efaf24aa60b5abc010",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":156,
                  "y":170},
                "size":{
                  "width":202,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"567bb31a1509413582f84b201ccb38c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":74,
              "y":200},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04690952753545229f041fe29b6e5f83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":74,
                  "y":200},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"a0933462bab24a42bd449a621a2800b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":332},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6c00b25742d441f8d29ffe26e964cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":332},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"31c3d93d90254f2da5d280d98f8ed339",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":676,
              "y":196},
            "size":{
              "width":128,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34999b774664a3387a880c23a422017",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":676,
                  "y":196},
                "size":{
                  "width":128,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d136a7b763294e658eb4757849b3f5d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":156,
              "y":327},
            "size":{
              "width":202,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32cb2093ea674946a3c2e2a6cb8fce17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":156,
                  "y":327},
                "size":{
                  "width":202,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c359edee453341d9b0f78ed8212098f8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":74,
              "y":369},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92af62178e6948b3b3fce80c5c51d671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":74,
                  "y":369},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"72aa9499d7754dc2adba57b684df5142",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":501},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbfe0e505e82411da9ea132dff10a791",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":62,
                  "y":501},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"68dc0238d8ad48909aef567ed11097b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":156,
              "y":503},
            "size":{
              "width":202,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1867592a35e44986ab7082ac64bd63d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":156,
                  "y":503},
                "size":{
                  "width":202,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a2087afa7e547caa14c92de03ff402c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":72,
              "y":538},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b164b44be2048e0a02ed464dfbce701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":72,
                  "y":538},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"97c6bb740f484f12bceb1752bef7b026",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":156,
              "y":237},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccc87df9464e432ba5f4b1faaeb6d808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":156,
                  "y":237},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0285cd19b9ec4a26a30e5e401a2207f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":156,
              "y":411},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1e61a6052f4017967ce8cb12c5354f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":156,
                  "y":411},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f3300a111734eaf97d1651d7fd15616",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":156,
              "y":578},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2967e0ffe25c4ed283011e9e4cc25199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":156,
                  "y":578},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ef3f524fe1f455ab0d3166052ed5870",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":62,
              "y":312},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"853d49c660204c25b77f5b250952675d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":60,
              "y":483},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"92bce271b4634993a6038d10ac51a6e6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":62,
              "y":652},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"a8fce96e5cbd4e28a352649914dabcb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":682,
              "y":362},
            "size":{
              "width":128,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a41b44c11594b45a4ca31b4d9a7d388",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":682,
                  "y":362},
                "size":{
                  "width":128,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5318df5886304473aabe6a5c41f4ac74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":680,
              "y":530},
            "size":{
              "width":128,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3312759aaca6495cbbeac224a16e2296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":680,
                  "y":530},
                "size":{
                  "width":128,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"716397641f714a339bb0725ab3a43158",
          "label":"得分详情动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":659},
            "size":{
              "width":746,
              "height":560}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c5810c9029d043658d6b5f36a9de5e2f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e1a276b3fd3d47089361ecb0a4d9607f",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6367c41250b242c48d20f4dbba0dbcc3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"8fbf430d2cc841cd97bff7f85cccfa50",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20ffa5a6ccb447ce84a5caafe9a14df9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"f1c1b97e582049e8a18d527fc06bd319",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0d206f9d3f34c7f805169cb773b6f59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"ae31d27d664d446bb378871bbcbcba45",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":90},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a63146550115452eb93160e2cffafcbd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":90},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2dfb8f3a083f47c8884f4cb2c5c72e28",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"277fcb0a135e495b813be7804aee8c8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":240},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"12ef7a0c0c8347e5a147778a38626d33",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03d00374026842b7baeafd6f67d72a60",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":320},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"2fe1b6bbacd6418fa81ba8a7e1f7dbcf",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":14},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce6bbd4e7fe242fabd4e5f5f786ad88e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":14},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e80c4cf9a7dc4113a2d3f0397773ea79",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":14},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c2b146a9fce4082ad5691cc6e29cbb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":14},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e3c4affec3534cda9b7b44f5b912705a",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9dd8b7a998bd4b998c20e1b6a02e0d4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":90},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a9a8f2adba494b4c99039d5cc3797b83",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":240,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"86bf6269def14aa1ad9d7dd6a95fa90c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":240,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0377abcfc51c407e9333bd2122e39f13",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":90},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0c326508edd54bc087271c2df77f4658",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":90},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6d23fffda1444beca4c3cf34ec0db1e9",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":170},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3f41be0d44d434da251a0fa68e32cd8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":170},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1a86e1676a0486dbd50ae252343a99e",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":170},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e356d5bfdf8e4509ade24b40abedc1e9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":170},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f5062e5509fe4b32a013d591601896bc",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":250},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1a9c95428be477d8ed99be3b4c75373",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":250},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c282e5d317e24d6aa0a6ca086729ac38",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":330},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"935f217100e44ec6a85420d7a5e762e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":330},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"843039cf8bc849be98528fd44bec018c",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":330},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32198b0f0ab54ded8dfd00cdcb8cf107",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":330},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ac6562180b0c48f08f7a75ab9c67815e",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":400},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bca3e67eca5542fab6a87231ff4675bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"e8b496e2ee8a44d59c7b0cb4f8603cb2",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":410},
                    "size":{
                      "width":250,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a0749124939467dbb8224e25b4b3926",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":410},
                        "size":{
                          "width":250,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2850ef1e1ef14da7ad1073e9d71aa27e",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":410},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16b6746fbebc4a97bcdefaa53ea27da2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":410},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8d45fc7d17644dc793bbb77daca38ec1",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":480},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2649d374b4d94c549247496fab70473e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":480},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"3804a46d6d3943ea9961e6cacb2db141",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":490},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc40ec50e7774142ab2b2b691d54be82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":490},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c68267c84d62493ab361d3594bb1680b",
                  "label":"",
                  "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":360,
                      "y":490},
                    "size":{
                      "width":170,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"50135001ee6d45219b1708b272c8e6a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"716397641f714a339bb0725ab3a43158",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":360,
                          "y":490},
                        "size":{
                          "width":170,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"3eb95e9e3c814f9b845c1d9214c67fb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":347,
              "y":112},
            "size":{
              "width":164,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f58edcd8bbe4a66b768398dba8dd14a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":347,
                  "y":112},
                "size":{
                  "width":164,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/得分明细/u86.png"}},
{
          "id":"ae4b986273cc401b998ce4758ee53ecc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":482,
              "y":129},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f727df08ae7b41719af4370048838122",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":482,
                  "y":129},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cdced877154642c586b554ff27c0902c":{
      "scriptId":"u0"},
    "bc0df088db3a4941942908d167810597":{
      "scriptId":"u1"},
    "11de7db0e8784ab89cd0118d1c763b5b":{
      "scriptId":"u2"},
    "6cca9a4645fc48fb98e7cda9329bdec1":{
      "scriptId":"u3"},
    "6d44cc2b998549009afde398e97ada2a":{
      "scriptId":"u4"},
    "e40a2ee4289d4046af6fa998e8e6b4bc":{
      "scriptId":"u5"},
    "4112a2b81f7e4c42bc090cdb242892dd":{
      "scriptId":"u6"},
    "d7f0b44233474fd0a27da67a520bbdfd":{
      "scriptId":"u7"},
    "7bf638a75ef941cc9b2403e53a1d3fe1":{
      "scriptId":"u8"},
    "999b701afb8c4d509c60b554286e6480":{
      "scriptId":"u9"},
    "75e47fdc33b9412d940d673883ef6595":{
      "scriptId":"u10"},
    "ae4e8f7f216f44efaf24aa60b5abc010":{
      "scriptId":"u11"},
    "567bb31a1509413582f84b201ccb38c2":{
      "scriptId":"u12"},
    "04690952753545229f041fe29b6e5f83":{
      "scriptId":"u13"},
    "a0933462bab24a42bd449a621a2800b8":{
      "scriptId":"u14"},
    "f6c00b25742d441f8d29ffe26e964cb1":{
      "scriptId":"u15"},
    "31c3d93d90254f2da5d280d98f8ed339":{
      "scriptId":"u16"},
    "a34999b774664a3387a880c23a422017":{
      "scriptId":"u17"},
    "d136a7b763294e658eb4757849b3f5d4":{
      "scriptId":"u18"},
    "32cb2093ea674946a3c2e2a6cb8fce17":{
      "scriptId":"u19"},
    "c359edee453341d9b0f78ed8212098f8":{
      "scriptId":"u20"},
    "92af62178e6948b3b3fce80c5c51d671":{
      "scriptId":"u21"},
    "72aa9499d7754dc2adba57b684df5142":{
      "scriptId":"u22"},
    "bbfe0e505e82411da9ea132dff10a791":{
      "scriptId":"u23"},
    "68dc0238d8ad48909aef567ed11097b0":{
      "scriptId":"u24"},
    "1867592a35e44986ab7082ac64bd63d2":{
      "scriptId":"u25"},
    "5a2087afa7e547caa14c92de03ff402c":{
      "scriptId":"u26"},
    "9b164b44be2048e0a02ed464dfbce701":{
      "scriptId":"u27"},
    "97c6bb740f484f12bceb1752bef7b026":{
      "scriptId":"u28"},
    "ccc87df9464e432ba5f4b1faaeb6d808":{
      "scriptId":"u29"},
    "0285cd19b9ec4a26a30e5e401a2207f1":{
      "scriptId":"u30"},
    "4f1e61a6052f4017967ce8cb12c5354f":{
      "scriptId":"u31"},
    "1f3300a111734eaf97d1651d7fd15616":{
      "scriptId":"u32"},
    "2967e0ffe25c4ed283011e9e4cc25199":{
      "scriptId":"u33"},
    "0ef3f524fe1f455ab0d3166052ed5870":{
      "scriptId":"u34"},
    "853d49c660204c25b77f5b250952675d":{
      "scriptId":"u35"},
    "92bce271b4634993a6038d10ac51a6e6":{
      "scriptId":"u36"},
    "a8fce96e5cbd4e28a352649914dabcb5":{
      "scriptId":"u37"},
    "7a41b44c11594b45a4ca31b4d9a7d388":{
      "scriptId":"u38"},
    "5318df5886304473aabe6a5c41f4ac74":{
      "scriptId":"u39"},
    "3312759aaca6495cbbeac224a16e2296":{
      "scriptId":"u40"},
    "716397641f714a339bb0725ab3a43158":{
      "scriptId":"u41"},
    "e1a276b3fd3d47089361ecb0a4d9607f":{
      "scriptId":"u42"},
    "6367c41250b242c48d20f4dbba0dbcc3":{
      "scriptId":"u43"},
    "8fbf430d2cc841cd97bff7f85cccfa50":{
      "scriptId":"u44"},
    "20ffa5a6ccb447ce84a5caafe9a14df9":{
      "scriptId":"u45"},
    "f1c1b97e582049e8a18d527fc06bd319":{
      "scriptId":"u46"},
    "d0d206f9d3f34c7f805169cb773b6f59":{
      "scriptId":"u47"},
    "ae31d27d664d446bb378871bbcbcba45":{
      "scriptId":"u48"},
    "a63146550115452eb93160e2cffafcbd":{
      "scriptId":"u49"},
    "2dfb8f3a083f47c8884f4cb2c5c72e28":{
      "scriptId":"u50"},
    "277fcb0a135e495b813be7804aee8c8f":{
      "scriptId":"u51"},
    "12ef7a0c0c8347e5a147778a38626d33":{
      "scriptId":"u52"},
    "03d00374026842b7baeafd6f67d72a60":{
      "scriptId":"u53"},
    "2fe1b6bbacd6418fa81ba8a7e1f7dbcf":{
      "scriptId":"u54"},
    "ce6bbd4e7fe242fabd4e5f5f786ad88e":{
      "scriptId":"u55"},
    "e80c4cf9a7dc4113a2d3f0397773ea79":{
      "scriptId":"u56"},
    "1c2b146a9fce4082ad5691cc6e29cbb3":{
      "scriptId":"u57"},
    "e3c4affec3534cda9b7b44f5b912705a":{
      "scriptId":"u58"},
    "9dd8b7a998bd4b998c20e1b6a02e0d4f":{
      "scriptId":"u59"},
    "a9a8f2adba494b4c99039d5cc3797b83":{
      "scriptId":"u60"},
    "86bf6269def14aa1ad9d7dd6a95fa90c":{
      "scriptId":"u61"},
    "0377abcfc51c407e9333bd2122e39f13":{
      "scriptId":"u62"},
    "0c326508edd54bc087271c2df77f4658":{
      "scriptId":"u63"},
    "6d23fffda1444beca4c3cf34ec0db1e9":{
      "scriptId":"u64"},
    "a3f41be0d44d434da251a0fa68e32cd8":{
      "scriptId":"u65"},
    "f1a86e1676a0486dbd50ae252343a99e":{
      "scriptId":"u66"},
    "e356d5bfdf8e4509ade24b40abedc1e9":{
      "scriptId":"u67"},
    "f5062e5509fe4b32a013d591601896bc":{
      "scriptId":"u68"},
    "c1a9c95428be477d8ed99be3b4c75373":{
      "scriptId":"u69"},
    "c282e5d317e24d6aa0a6ca086729ac38":{
      "scriptId":"u70"},
    "935f217100e44ec6a85420d7a5e762e4":{
      "scriptId":"u71"},
    "843039cf8bc849be98528fd44bec018c":{
      "scriptId":"u72"},
    "32198b0f0ab54ded8dfd00cdcb8cf107":{
      "scriptId":"u73"},
    "ac6562180b0c48f08f7a75ab9c67815e":{
      "scriptId":"u74"},
    "bca3e67eca5542fab6a87231ff4675bb":{
      "scriptId":"u75"},
    "e8b496e2ee8a44d59c7b0cb4f8603cb2":{
      "scriptId":"u76"},
    "5a0749124939467dbb8224e25b4b3926":{
      "scriptId":"u77"},
    "2850ef1e1ef14da7ad1073e9d71aa27e":{
      "scriptId":"u78"},
    "16b6746fbebc4a97bcdefaa53ea27da2":{
      "scriptId":"u79"},
    "8d45fc7d17644dc793bbb77daca38ec1":{
      "scriptId":"u80"},
    "2649d374b4d94c549247496fab70473e":{
      "scriptId":"u81"},
    "3804a46d6d3943ea9961e6cacb2db141":{
      "scriptId":"u82"},
    "dc40ec50e7774142ab2b2b691d54be82":{
      "scriptId":"u83"},
    "c68267c84d62493ab361d3594bb1680b":{
      "scriptId":"u84"},
    "50135001ee6d45219b1708b272c8e6a6":{
      "scriptId":"u85"},
    "3eb95e9e3c814f9b845c1d9214c67fb0":{
      "scriptId":"u86"},
    "8f58edcd8bbe4a66b768398dba8dd14a":{
      "scriptId":"u87"},
    "ae4b986273cc401b998ce4758ee53ecc":{
      "scriptId":"u88"},
    "f727df08ae7b41719af4370048838122":{
      "scriptId":"u89"}}});