$axure.loadCurrentPage({
  "url":"交作业_1.html",
  "generationDate":new Date(1515736338630),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8006237ae7c746dfb91403da3edaa097",
    "type":"Axure:Page",
    "name":"交作业",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"be7516bbfe5c4ad08cf0d8eb02c52241",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":1333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942fc51a9daf4b2b98041a08a27b7c88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":1333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务内容/u0.png"}},
{
          "id":"61a23d2ef7b045429d7f014e9bd2db81",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd54bef01494ba6a66ecf832ed36dd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"cc808d5c369347ce8ff0ba85d7fffb95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4effe63f731d4909941b1cab0e6598d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"c7f0c79da437453ea957c21a88a48a10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":131},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b693b120886408f82d2b7f207bbb2d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":131},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"ba020062666e4a71a6de77ea91e7c9e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":710,
              "y":125},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcff0238154c49dab14095fd07890274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":125},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19ea3174a1e94e45976fb4236b16790d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":80,
              "y":200},
            "size":{
              "width":750,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa065a1592ca4097aaca72c8db0ee230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":200},
                "size":{
                  "width":750,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b21ff5b8deb344d19defb8fe1f14575a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":541,
              "y":840},
            "size":{
              "width":285,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b324f09b0d144eebb96990b3f41b8be7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":541,
                  "y":840},
                "size":{
                  "width":285,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed8d98a55e03450dbdd8222e9ec6ed5c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":880,
              "y":1220},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"a391c34474eb46cb843a93a018eb66d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":1090,
              "y":1166},
            "size":{
              "width":340,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496dc98c5336481a84ca6674cd37a8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":1090,
                  "y":1166},
                "size":{
                  "width":340,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业_1/u15.png"}},
{
          "id":"ca59f701bd664331856b07071e7c2bdc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1856,
              "y":350},
            "size":{
              "width":404,
              "height":726}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8810835699f0407b997655924b6ebbbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1856,
                  "y":350},
                "size":{
                  "width":404,
                  "height":726}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业_1/u17.jpg"}},
{
          "id":"5f5d47804c56488bb293a660374b1fba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":84,
              "y":1276},
            "size":{
              "width":743,
              "height":125},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31493c0f3c05481a93358662c37ad71a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":84,
                  "y":1276},
                "size":{
                  "width":743,
                  "height":125},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业_1/u19.png"}},
{
          "id":"90b4955029444b319912d8a705a25bcc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":97,
              "y":923},
            "size":{
              "width":730,
              "height":317},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9162713fdcfd40eba7d851e6d3ca8428",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":97,
                  "y":923},
                "size":{
                  "width":730,
                  "height":317},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业_1/u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "be7516bbfe5c4ad08cf0d8eb02c52241":{
      "scriptId":"u0"},
    "942fc51a9daf4b2b98041a08a27b7c88":{
      "scriptId":"u1"},
    "61a23d2ef7b045429d7f014e9bd2db81":{
      "scriptId":"u2"},
    "7bd54bef01494ba6a66ecf832ed36dd8":{
      "scriptId":"u3"},
    "cc808d5c369347ce8ff0ba85d7fffb95":{
      "scriptId":"u4"},
    "4effe63f731d4909941b1cab0e6598d7":{
      "scriptId":"u5"},
    "c7f0c79da437453ea957c21a88a48a10":{
      "scriptId":"u6"},
    "9b693b120886408f82d2b7f207bbb2d6":{
      "scriptId":"u7"},
    "ba020062666e4a71a6de77ea91e7c9e1":{
      "scriptId":"u8"},
    "dcff0238154c49dab14095fd07890274":{
      "scriptId":"u9"},
    "19ea3174a1e94e45976fb4236b16790d":{
      "scriptId":"u10"},
    "fa065a1592ca4097aaca72c8db0ee230":{
      "scriptId":"u11"},
    "b21ff5b8deb344d19defb8fe1f14575a":{
      "scriptId":"u12"},
    "b324f09b0d144eebb96990b3f41b8be7":{
      "scriptId":"u13"},
    "ed8d98a55e03450dbdd8222e9ec6ed5c":{
      "scriptId":"u14"},
    "a391c34474eb46cb843a93a018eb66d2":{
      "scriptId":"u15"},
    "496dc98c5336481a84ca6674cd37a8ff":{
      "scriptId":"u16"},
    "ca59f701bd664331856b07071e7c2bdc":{
      "scriptId":"u17"},
    "8810835699f0407b997655924b6ebbbb":{
      "scriptId":"u18"},
    "5f5d47804c56488bb293a660374b1fba":{
      "scriptId":"u19"},
    "31493c0f3c05481a93358662c37ad71a":{
      "scriptId":"u20"},
    "90b4955029444b319912d8a705a25bcc":{
      "scriptId":"u21"},
    "9162713fdcfd40eba7d851e6d3ca8428":{
      "scriptId":"u22"}}});