$axure.loadCurrentPage({
  "url":"我的事项_1.html",
  "generationDate":new Date(1515736337696),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b340a3783971426693246fe646770a0b",
    "type":"Axure:Page",
    "name":"我的事项",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"09721af56cc6417d9ad393082cc2e871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":186},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c546eac1c7b4b6086d876579d65172c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":186},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u198.png"}},
{
          "id":"f3d4b4c167394b28aecf1209501fee14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "verticalAlignment":"top",
            "location":{
              "x":70,
              "y":97},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dcec33b75da4a0584a4117b31cd2f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "verticalAlignment":"top",
                "location":{
                  "x":70,
                  "y":97},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"ed72a883747149218518ab2e52e03bb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":118},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2de5c0416694e6591bca5cb0ffdfa0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":118},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生",
                      "target":{
                        "targetType":"page",
                        "url":"学生.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"94c56587898f4fca8569f96847b412cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":70,
              "y":57},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4455aebabcea46a4bac912b96a2e2c59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":70,
                  "y":57},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"b77d8648545e4164b0dd8268be292ee5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":75,
              "y":190},
            "size":{
              "width":742,
              "height":132},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"518c9a71f497426c961fa41ef0a20fc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":75,
                  "y":190},
                "size":{
                  "width":742,
                  "height":132},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u8.png"}},
{
          "id":"5475d1d1685a48598bfa3c40fa3647f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":167,
              "y":199},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d6e51b6707434ab7c7b42048d39768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":199},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed1cae81edaa46c9975a778afbed6a4f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":85,
              "y":220},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98d4a983c46f406ea0df6efee25d7c6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":85,
                  "y":220},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"bb15064efb6f482da0aaa3a0c8d1a4e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":352},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01686ee76574453cb7d091da92142d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":352},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"8ed3022f341947c59125c472b5cd182f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":687,
              "y":216},
            "size":{
              "width":128,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2743d53b66d24057a780f9075c4d4178",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":687,
                  "y":216},
                "size":{
                  "width":128,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e7fd01fa2b94eb08e32f840bf229380",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":668,
              "y":383},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40fa26342d4946d2b0acc915ffd828b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":668,
                  "y":383},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d58fe882141489aa4f09a3bbecc8c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":165,
              "y":362},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c16d4e746bef4dbbb4f2d94729c11043",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":362},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bf1d0e6f25f4b469138ec405051cd73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":85,
              "y":389},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cdee3cbf4a446338d40c8419da82250",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":85,
                  "y":389},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"0069b4567bd7402cb6b519c3a364b18d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":521},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8707160639a040b8a16da557b94fa6e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":521},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"741d911ca5844be88d42fe30e895d718",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":167,
              "y":537},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"244967caa57e4d5fba05ea9a8cfe445e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":537},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adce98624fb34ee59ae41ffd6d276087",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":83,
              "y":558},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97602c1a0a334c8c97ca5ae376a3ff40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":83,
                  "y":558},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"d1a06a9ae4b945179272e236d7225717",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":679,
              "y":560},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0db10f0c3a465fbd27427764ffa91d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":679,
                  "y":560},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e4ea90addd9d42f5917fbc110295e1e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":167,
              "y":257},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f0a84d9ea554e33aa0cb6ae22e90853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":257},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bf4eb09f28d4114a62466ea1b5e7976",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":165,
              "y":427},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5431e9e8ba6b4077a8723d0863b95578",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":427},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a69239a150f48fabd4211a60481dc55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":167,
              "y":597},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"289f1d56fbd14977af8f659d15da93e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":167,
                  "y":597},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4556b9e8e7e2450c8ae944299a63529a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":123},
            "size":{
              "width":41,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0c72a1a864844b8b691fd56b94f92a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":123},
                "size":{
                  "width":41,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u42.png"}},
{
          "id":"306dccd852ec4e54967417de36c16655",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":540,
              "y":552},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa479f8e5318471e80cabe85a01b01e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":552},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9586431e11eb4f46bcbcb456ba187d9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":257},
            "size":{
              "width":105,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项_1/u42_line.png"}},
{
          "id":"30b59ff0f8fe4202a0ccecd7098da139",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "lineSpacing":"36px",
            "location":{
              "x":930,
              "y":212},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8744bcac1859421182dc9523d2162145",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "lineSpacing":"36px",
                "location":{
                  "x":930,
                  "y":212},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项_1/u43.png"}},
{
          "id":"152fdea13f674ea289c01a1a66a747fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":710,
              "y":119},
            "size":{
              "width":100,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b3f535daf66401b81f23d812f3cf5f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":710,
                  "y":119},
                "size":{
                  "width":100,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已办事项",
                      "target":{
                        "targetType":"page",
                        "url":"已办事项_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0963d9d9ca0b42e6b63a8b2cdf8cd40b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":354,
              "y":136},
            "size":{
              "width":164,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23a33afe01fc45c5a1062e6c30c72c13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":354,
                  "y":136},
                "size":{
                  "width":164,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 全部活动动态面板 向下滑动 500 ms 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["2375d6a7cf73474a84f7ef4c3ac7d5c0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"lightbox",
                              "lightbox":{
                                "r":228,
                                "g":228,
                                "b":228,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u32.png"}},
{
          "id":"79b029bc764243bfb3653d4c31d32dba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":150},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68d6cbadb79241ffb688e1d81d965ecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":150},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 全部活动动态面板 向下滑动 500 ms 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["2375d6a7cf73474a84f7ef4c3ac7d5c0"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"lightbox",
                              "lightbox":{
                                "r":228,
                                "g":228,
                                "b":228,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u34.png"}},
{
          "id":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
          "label":"全部活动动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":188},
            "size":{
              "width":750,
              "height":300},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"68076afe09e2449582e9e206904c5798",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bd2119700f794e3893e01ec26298ee31",
                  "label":"",
                  "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":300}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f03f405b283e4044b3afb73bd641f994",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":300}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的事项/u53.png"}},
{
                  "id":"8d162eabc57944f7b5e0e16131cd4614",
                  "label":"",
                  "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":750,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04b476744a4b40d1988290f036eeec73",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":750,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0d2e65167974444090d454cd2b2137d0",
                  "label":"",
                  "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "location":{
                      "x":0,
                      "y":196},
                    "size":{
                      "width":750,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/管理员、老师/u370_line.png"}},
{
                  "id":"a0f4fb228a4447d4befcffe0cf0e97f6",
                  "label":"",
                  "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":750,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1d2e9118b034da292b8cc6acd13497e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":102},
                        "size":{
                          "width":750,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3d9590ae42f14c9ebb9638317bd1c6c5",
                  "label":"",
                  "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "location":{
                      "x":0,
                      "y":98},
                    "size":{
                      "width":750,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/管理员、老师/u370_line.png"}},
{
                  "id":"c06e506b1b2f4029a3d1bcfb58651ebc",
                  "label":"",
                  "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":4},
                    "size":{
                      "width":750,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48f0bfaaeb18454aa7c92b0e31dde171",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2375d6a7cf73474a84f7ef4c3ac7d5c0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":4},
                        "size":{
                          "width":750,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "09721af56cc6417d9ad393082cc2e871":{
      "scriptId":"u0"},
    "6c546eac1c7b4b6086d876579d65172c":{
      "scriptId":"u1"},
    "f3d4b4c167394b28aecf1209501fee14":{
      "scriptId":"u2"},
    "7dcec33b75da4a0584a4117b31cd2f31":{
      "scriptId":"u3"},
    "ed72a883747149218518ab2e52e03bb9":{
      "scriptId":"u4"},
    "c2de5c0416694e6591bca5cb0ffdfa0b":{
      "scriptId":"u5"},
    "94c56587898f4fca8569f96847b412cc":{
      "scriptId":"u6"},
    "4455aebabcea46a4bac912b96a2e2c59":{
      "scriptId":"u7"},
    "b77d8648545e4164b0dd8268be292ee5":{
      "scriptId":"u8"},
    "518c9a71f497426c961fa41ef0a20fc7":{
      "scriptId":"u9"},
    "5475d1d1685a48598bfa3c40fa3647f6":{
      "scriptId":"u10"},
    "36d6e51b6707434ab7c7b42048d39768":{
      "scriptId":"u11"},
    "ed1cae81edaa46c9975a778afbed6a4f":{
      "scriptId":"u12"},
    "98d4a983c46f406ea0df6efee25d7c6c":{
      "scriptId":"u13"},
    "bb15064efb6f482da0aaa3a0c8d1a4e5":{
      "scriptId":"u14"},
    "01686ee76574453cb7d091da92142d12":{
      "scriptId":"u15"},
    "8ed3022f341947c59125c472b5cd182f":{
      "scriptId":"u16"},
    "2743d53b66d24057a780f9075c4d4178":{
      "scriptId":"u17"},
    "9e7fd01fa2b94eb08e32f840bf229380":{
      "scriptId":"u18"},
    "40fa26342d4946d2b0acc915ffd828b5":{
      "scriptId":"u19"},
    "7d58fe882141489aa4f09a3bbecc8c29":{
      "scriptId":"u20"},
    "c16d4e746bef4dbbb4f2d94729c11043":{
      "scriptId":"u21"},
    "2bf1d0e6f25f4b469138ec405051cd73":{
      "scriptId":"u22"},
    "3cdee3cbf4a446338d40c8419da82250":{
      "scriptId":"u23"},
    "0069b4567bd7402cb6b519c3a364b18d":{
      "scriptId":"u24"},
    "8707160639a040b8a16da557b94fa6e5":{
      "scriptId":"u25"},
    "741d911ca5844be88d42fe30e895d718":{
      "scriptId":"u26"},
    "244967caa57e4d5fba05ea9a8cfe445e":{
      "scriptId":"u27"},
    "adce98624fb34ee59ae41ffd6d276087":{
      "scriptId":"u28"},
    "97602c1a0a334c8c97ca5ae376a3ff40":{
      "scriptId":"u29"},
    "d1a06a9ae4b945179272e236d7225717":{
      "scriptId":"u30"},
    "1b0db10f0c3a465fbd27427764ffa91d":{
      "scriptId":"u31"},
    "e4ea90addd9d42f5917fbc110295e1e5":{
      "scriptId":"u32"},
    "2f0a84d9ea554e33aa0cb6ae22e90853":{
      "scriptId":"u33"},
    "7bf4eb09f28d4114a62466ea1b5e7976":{
      "scriptId":"u34"},
    "5431e9e8ba6b4077a8723d0863b95578":{
      "scriptId":"u35"},
    "8a69239a150f48fabd4211a60481dc55":{
      "scriptId":"u36"},
    "289f1d56fbd14977af8f659d15da93e9":{
      "scriptId":"u37"},
    "4556b9e8e7e2450c8ae944299a63529a":{
      "scriptId":"u38"},
    "f0c72a1a864844b8b691fd56b94f92a0":{
      "scriptId":"u39"},
    "306dccd852ec4e54967417de36c16655":{
      "scriptId":"u40"},
    "aa479f8e5318471e80cabe85a01b01e9":{
      "scriptId":"u41"},
    "9586431e11eb4f46bcbcb456ba187d9a":{
      "scriptId":"u42"},
    "30b59ff0f8fe4202a0ccecd7098da139":{
      "scriptId":"u43"},
    "8744bcac1859421182dc9523d2162145":{
      "scriptId":"u44"},
    "152fdea13f674ea289c01a1a66a747fe":{
      "scriptId":"u45"},
    "2b3f535daf66401b81f23d812f3cf5f5":{
      "scriptId":"u46"},
    "0963d9d9ca0b42e6b63a8b2cdf8cd40b":{
      "scriptId":"u47"},
    "23a33afe01fc45c5a1062e6c30c72c13":{
      "scriptId":"u48"},
    "79b029bc764243bfb3653d4c31d32dba":{
      "scriptId":"u49"},
    "68d6cbadb79241ffb688e1d81d965ecd":{
      "scriptId":"u50"},
    "2375d6a7cf73474a84f7ef4c3ac7d5c0":{
      "scriptId":"u51"},
    "bd2119700f794e3893e01ec26298ee31":{
      "scriptId":"u52"},
    "f03f405b283e4044b3afb73bd641f994":{
      "scriptId":"u53"},
    "8d162eabc57944f7b5e0e16131cd4614":{
      "scriptId":"u54"},
    "04b476744a4b40d1988290f036eeec73":{
      "scriptId":"u55"},
    "0d2e65167974444090d454cd2b2137d0":{
      "scriptId":"u56"},
    "a0f4fb228a4447d4befcffe0cf0e97f6":{
      "scriptId":"u57"},
    "c1d2e9118b034da292b8cc6acd13497e":{
      "scriptId":"u58"},
    "3d9590ae42f14c9ebb9638317bd1c6c5":{
      "scriptId":"u59"},
    "c06e506b1b2f4029a3d1bcfb58651ebc":{
      "scriptId":"u60"},
    "48f0bfaaeb18454aa7c92b0e31dde171":{
      "scriptId":"u61"}}});