$axure.loadCurrentPage({
  "url":"已办事项_1.html",
  "generationDate":new Date(1515736339425),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"05b479cac62943c4bb54cfd66e79beab",
    "type":"Axure:Page",
    "name":"已办事项",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8da3483e71ea466785719de2209222d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":130,
              "y":169},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367830018b0b4163ac2d9bd44e528aff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":130,
                  "y":169},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u198.png"}},
{
          "id":"4a4a0b26edfa4827aa5b8843cc4df2b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "verticalAlignment":"top",
            "location":{
              "x":130,
              "y":80},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2eab10bd57c4ba981731e3fdc4ef0ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "verticalAlignment":"top",
                "location":{
                  "x":130,
                  "y":80},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"8e5a1b1acfff4a61943388a9e4241d99",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":101},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"176e06b435db4ce4afa2513e8e94bdd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":101},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的事项",
                      "target":{
                        "targetType":"page",
                        "url":"我的事项_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"44d19e08c12f4cedbbe92bf9d70fe270",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":130,
              "y":40},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4722da04b5ff425595b1aec63733c801",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":130,
                  "y":40},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"618ef09dc2824a6d8915921870c50e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":135,
              "y":173},
            "size":{
              "width":742,
              "height":132},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f7b141fffb54d02a10943c27eae4e6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135,
                  "y":173},
                "size":{
                  "width":742,
                  "height":132},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u8.png"}},
{
          "id":"c8e12c82dcf14d959d6646894df07394",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":227,
              "y":182},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72dc20d814824ab2b02bdf47c9885ab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":227,
                  "y":182},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda22f5b08694cb9aa7b4082f3aab322",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":145,
              "y":203},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bcd3ad970874409885b22f327baf076",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":145,
                  "y":203},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"2675bb8dced74263902e3c1b1f474c05",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":335},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"813aecc0f21d43aa87075695933a6fd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":335},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"83c7eabb4950420ebd73f00f2668be35",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":747,
              "y":199},
            "size":{
              "width":128,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3a9c22e16940f9b2fa249e96c3b181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":747,
                  "y":199},
                "size":{
                  "width":128,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f88bac990754b15afad815e62a9c069",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":728,
              "y":366},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba134a47bf5c4faf9539902a77737fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":728,
                  "y":366},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a07d0e935ff418bb7fd5d9ee0d4b5c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":225,
              "y":345},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6d8b5daec794b119bb41f57652d50d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":225,
                  "y":345},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfbd5ffe4e454fc78231b4392ccb2a66",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":145,
              "y":372},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff48c13aac5b46e9809caf36e57c2c40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":145,
                  "y":372},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"219c8288047b4c43ac837201c3b09ac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":504},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fa912df0b8045c39287d339bbb4784f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":504},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"b9a4ad90d35f4adbb4f5899d562baeeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":227,
              "y":520},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f7dde6dd0074c91b08ddecb4c798e6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":227,
                  "y":520},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1390374738c453180d745ce84ad911e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":143,
              "y":541},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0dda07d053664a99b49c7857bc0e613a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":143,
                  "y":541},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"c396296edc344705a6b71d71908a16d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":739,
              "y":543},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43572c5826894c4e889a9ffbc94cf0f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":739,
                  "y":543},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"895bb4ae82dc4a158829365737796766",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":414,
              "y":130},
            "size":{
              "width":164,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b4e0d1d00a34f41aa03599484b97219",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":414,
                  "y":130},
                "size":{
                  "width":164,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/已办事项_1/u32.png"}},
{
          "id":"47038be96ef3477f8601fd0ef995de18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":549,
              "y":139},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf950aad06b349a2bb80be168fa83b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":549,
                  "y":139},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u34.png"}},
{
          "id":"d28bf1af7f5b4a4995c552b7c750c4b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":227,
              "y":240},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827c6506cbdb45c8b7fdfe8864c96263",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":227,
                  "y":240},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2ce610ab13e42008040fa657cf606ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":225,
              "y":410},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c2c11fd7fd54a138b0afed04b25b95a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":225,
                  "y":410},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc6534302b9b403f882dbaf557175fdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":227,
              "y":580},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b90f3a4562324eca97068f23691807d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":227,
                  "y":580},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9fcda98fdd67456f95c7e5351655252b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":819,
              "y":106},
            "size":{
              "width":41,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6032aae5e8f44ed8a1641910d226898d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":819,
                  "y":106},
                "size":{
                  "width":41,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u42.png"}},
{
          "id":"1a20b64188df47dfb372b8217947fe3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":600,
              "y":535},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0346a542dcac43d0990be462acbead39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":600,
                  "y":535},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a637d6e1a4e4adf929b89d0b0347984",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":240},
            "size":{
              "width":105,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项_1/u42_line.png"}},
{
          "id":"aaae26615ec7483aa32896ff5a31468a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "lineSpacing":"36px",
            "location":{
              "x":990,
              "y":195},
            "size":{
              "width":300,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"414efe2551854005aab22b065804cbed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "lineSpacing":"36px",
                "location":{
                  "x":990,
                  "y":195},
                "size":{
                  "width":300,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项_1/u43.png"}},
{
          "id":"2845fe6301314638ae7c7aaefca3451d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":599,
              "y":364},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16e74f762c1a40d896abd897bfb21320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":599,
                  "y":364},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52a698d4b2bf480ca598052aeb62bbf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":608,
              "y":204},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04cc764afb914346a05c5110cdcf1752",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":608,
                  "y":204},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "8da3483e71ea466785719de2209222d1":{
      "scriptId":"u0"},
    "367830018b0b4163ac2d9bd44e528aff":{
      "scriptId":"u1"},
    "4a4a0b26edfa4827aa5b8843cc4df2b2":{
      "scriptId":"u2"},
    "e2eab10bd57c4ba981731e3fdc4ef0ba":{
      "scriptId":"u3"},
    "8e5a1b1acfff4a61943388a9e4241d99":{
      "scriptId":"u4"},
    "176e06b435db4ce4afa2513e8e94bdd9":{
      "scriptId":"u5"},
    "44d19e08c12f4cedbbe92bf9d70fe270":{
      "scriptId":"u6"},
    "4722da04b5ff425595b1aec63733c801":{
      "scriptId":"u7"},
    "618ef09dc2824a6d8915921870c50e15":{
      "scriptId":"u8"},
    "7f7b141fffb54d02a10943c27eae4e6e":{
      "scriptId":"u9"},
    "c8e12c82dcf14d959d6646894df07394":{
      "scriptId":"u10"},
    "72dc20d814824ab2b02bdf47c9885ab7":{
      "scriptId":"u11"},
    "dda22f5b08694cb9aa7b4082f3aab322":{
      "scriptId":"u12"},
    "6bcd3ad970874409885b22f327baf076":{
      "scriptId":"u13"},
    "2675bb8dced74263902e3c1b1f474c05":{
      "scriptId":"u14"},
    "813aecc0f21d43aa87075695933a6fd2":{
      "scriptId":"u15"},
    "83c7eabb4950420ebd73f00f2668be35":{
      "scriptId":"u16"},
    "1d3a9c22e16940f9b2fa249e96c3b181":{
      "scriptId":"u17"},
    "8f88bac990754b15afad815e62a9c069":{
      "scriptId":"u18"},
    "ba134a47bf5c4faf9539902a77737fd0":{
      "scriptId":"u19"},
    "0a07d0e935ff418bb7fd5d9ee0d4b5c5":{
      "scriptId":"u20"},
    "c6d8b5daec794b119bb41f57652d50d6":{
      "scriptId":"u21"},
    "cfbd5ffe4e454fc78231b4392ccb2a66":{
      "scriptId":"u22"},
    "ff48c13aac5b46e9809caf36e57c2c40":{
      "scriptId":"u23"},
    "219c8288047b4c43ac837201c3b09ac7":{
      "scriptId":"u24"},
    "8fa912df0b8045c39287d339bbb4784f":{
      "scriptId":"u25"},
    "b9a4ad90d35f4adbb4f5899d562baeeb":{
      "scriptId":"u26"},
    "1f7dde6dd0074c91b08ddecb4c798e6d":{
      "scriptId":"u27"},
    "a1390374738c453180d745ce84ad911e":{
      "scriptId":"u28"},
    "0dda07d053664a99b49c7857bc0e613a":{
      "scriptId":"u29"},
    "c396296edc344705a6b71d71908a16d5":{
      "scriptId":"u30"},
    "43572c5826894c4e889a9ffbc94cf0f8":{
      "scriptId":"u31"},
    "895bb4ae82dc4a158829365737796766":{
      "scriptId":"u32"},
    "9b4e0d1d00a34f41aa03599484b97219":{
      "scriptId":"u33"},
    "47038be96ef3477f8601fd0ef995de18":{
      "scriptId":"u34"},
    "cf950aad06b349a2bb80be168fa83b60":{
      "scriptId":"u35"},
    "d28bf1af7f5b4a4995c552b7c750c4b1":{
      "scriptId":"u36"},
    "827c6506cbdb45c8b7fdfe8864c96263":{
      "scriptId":"u37"},
    "c2ce610ab13e42008040fa657cf606ef":{
      "scriptId":"u38"},
    "4c2c11fd7fd54a138b0afed04b25b95a":{
      "scriptId":"u39"},
    "bc6534302b9b403f882dbaf557175fdd":{
      "scriptId":"u40"},
    "b90f3a4562324eca97068f23691807d2":{
      "scriptId":"u41"},
    "9fcda98fdd67456f95c7e5351655252b":{
      "scriptId":"u42"},
    "6032aae5e8f44ed8a1641910d226898d":{
      "scriptId":"u43"},
    "1a20b64188df47dfb372b8217947fe3b":{
      "scriptId":"u44"},
    "0346a542dcac43d0990be462acbead39":{
      "scriptId":"u45"},
    "7a637d6e1a4e4adf929b89d0b0347984":{
      "scriptId":"u46"},
    "aaae26615ec7483aa32896ff5a31468a":{
      "scriptId":"u47"},
    "414efe2551854005aab22b065804cbed":{
      "scriptId":"u48"},
    "2845fe6301314638ae7c7aaefca3451d":{
      "scriptId":"u49"},
    "16e74f762c1a40d896abd897bfb21320":{
      "scriptId":"u50"},
    "52a698d4b2bf480ca598052aeb62bbf3":{
      "scriptId":"u51"},
    "04cc764afb914346a05c5110cdcf1752":{
      "scriptId":"u52"}}});