$axure.loadCurrentPage({
  "url":"计算期末分.html",
  "generationDate":new Date(1515736337165),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4e2dd820df2d4a64a2c87bf5b8fa5419",
    "type":"Axure:Page",
    "name":"计算期末分",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"73d94156497d4ac9af2ba392a04db9a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":179},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6abb48bc34284336b26b998e34a39694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":179},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u24.png"}},
{
          "id":"321f172d3f7b4a57bbee3b565e97c29e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":90},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10bf89c513f84c08bff0693bafdd1b74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":90},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"a7dc1afa7e4848fabc58e2b2310642b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":111},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f57e603834d4914ba6c6118d86a0571",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":111},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"25549d0af9d34503ba04f6b92529c222",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":50},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd41810f9da4052a5972e71affd994e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":50},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"0ff74f1ff1d04a49a7bece668e965f65",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":330,
              "y":116},
            "size":{
              "width":178,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcddb51b1a944a28a4c3b34f85b1814d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":330,
                  "y":116},
                "size":{
                  "width":178,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"525062ac13ab473eba008784cb79d148",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":504,
              "y":125.5},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3fa0a10f3dfe4e7daaf58a8930ef8d0b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":504,
                  "y":125.5},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u42.png"}},
{
          "id":"1d494104de134a63a9f014a087ce29c7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":380,
              "y":470},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18938ce0c9c341e6b7c43ce305b04852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":380,
                  "y":470},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"0d47f03ee48442c0b283c87f80630f8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":282,
              "y":660},
            "size":{
              "width":346,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0740e9ce8f734adfa05a1cd33eedca1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":282,
                  "y":660},
                "size":{
                  "width":346,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ed8e466379c4a939ce02a8f15eb86ae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":565},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"1722ea65f47b41c6802b0caff6ee18b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":1020,
              "y":520},
            "size":{
              "width":690,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12723d3d14dc41c386d24a9f910ee820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":1020,
                  "y":520},
                "size":{
                  "width":690,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/计算期末分/u17.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "73d94156497d4ac9af2ba392a04db9a1":{
      "scriptId":"u0"},
    "6abb48bc34284336b26b998e34a39694":{
      "scriptId":"u1"},
    "321f172d3f7b4a57bbee3b565e97c29e":{
      "scriptId":"u2"},
    "10bf89c513f84c08bff0693bafdd1b74":{
      "scriptId":"u3"},
    "a7dc1afa7e4848fabc58e2b2310642b4":{
      "scriptId":"u4"},
    "5f57e603834d4914ba6c6118d86a0571":{
      "scriptId":"u5"},
    "25549d0af9d34503ba04f6b92529c222":{
      "scriptId":"u6"},
    "dbd41810f9da4052a5972e71affd994e":{
      "scriptId":"u7"},
    "0ff74f1ff1d04a49a7bece668e965f65":{
      "scriptId":"u8"},
    "fcddb51b1a944a28a4c3b34f85b1814d":{
      "scriptId":"u9"},
    "525062ac13ab473eba008784cb79d148":{
      "scriptId":"u10"},
    "3fa0a10f3dfe4e7daaf58a8930ef8d0b":{
      "scriptId":"u11"},
    "1d494104de134a63a9f014a087ce29c7":{
      "scriptId":"u12"},
    "18938ce0c9c341e6b7c43ce305b04852":{
      "scriptId":"u13"},
    "0d47f03ee48442c0b283c87f80630f8d":{
      "scriptId":"u14"},
    "0740e9ce8f734adfa05a1cd33eedca1e":{
      "scriptId":"u15"},
    "9ed8e466379c4a939ce02a8f15eb86ae":{
      "scriptId":"u16"},
    "1722ea65f47b41c6802b0caff6ee18b0":{
      "scriptId":"u17"},
    "12723d3d14dc41c386d24a9f910ee820":{
      "scriptId":"u18"}}});