$axure.loadCurrentPage({
  "url":"任务名称1_1.html",
  "generationDate":new Date(1515736337907),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8da283b48cbb4d9db02997874c3ac392",
    "type":"Axure:Page",
    "name":"任务名称1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"188d4d586ee4470b9d0c4b57e33c8bb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":66},
            "size":{
              "width":750,
              "height":1294}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ec79d55d0154839b0073e163a2a947a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":66},
                "size":{
                  "width":750,
                  "height":1294}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u0.png"}},
{
          "id":"af762f3045b448c7b4629e12ebc8abf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":80,
              "y":66},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f23fe017f2db4465978eda2fcbf2c99c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":80,
                  "y":66},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"2c7f7645de3a4631b05ba9bcf40b5e2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":86},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8306c46c66e24b0c94ddd319013cc761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":86},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的事项",
                      "target":{
                        "targetType":"page",
                        "url":"我的事项_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"b0a7adf69adf4a5284dc4c8efa4a5fdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":26},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe3d3d1ad8244e97926bbaa619c0f96f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":26},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"45709e240f4a4687bb8d64c412e4926a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":336},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3159700a9274b31b74cc914ff600d08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":336},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"e64b7e707c4d4743bd0369c96a738438",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":180,
              "y":514},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5710b232cf8b424eb9541b4be9e1e2e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":180,
                  "y":514},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed258f39893244e083c7aafec499edac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":336},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42b8b7bd4c89424b81c78b329857e888",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":336},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交作业",
                      "target":{
                        "targetType":"page",
                        "url":"交作业_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"18b21d1ad0d047c08913df6953c8c846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":580,
              "y":514},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ac07c2f72134db98cf7d60d9fc61b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":580,
                  "y":514},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"385ed29bf199455ea35e68b44f1a02c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":640},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe36f680b37946d898510d130feab059",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":590,
                  "y":640},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 组长评分",
                      "target":{
                        "targetType":"page",
                        "url":"组长评分.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"995922764496464abb49e2cf4c3af1a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":580,
              "y":818},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e19a8b404aa407586d31e06ecc775c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":580,
                  "y":818},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2fbab66001b40dcb03ab717af1e2529",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":98,
              "y":156},
            "size":{
              "width":652,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93259048376e4e7eb77170209dbafd00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":98,
                  "y":156},
                "size":{
                  "width":652,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务详情",
                      "target":{
                        "targetType":"page",
                        "url":"任务详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3464cf4c83942f49b1f0150baefa0d0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":80,
              "y":280},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"1bb1585643c041cd8d2d6075c42b5d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":640},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b20195b11ff64dc28f114b47ed7dd7de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":640},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 学生互评",
                      "target":{
                        "targetType":"page",
                        "url":"学生互评.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"fc87d2325eb546dcaa07d3f8f294f750",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":180,
              "y":818},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b4fa827558540b1854e567fff5e475d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":180,
                  "y":818},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4744cacff68c48cc8471ac1cdfad62e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":940},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2a3319b6f4b4582a234e9e36d9b7ac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":940},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 作业打分",
                      "target":{
                        "targetType":"page",
                        "url":"作业打分.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"615b147c2fe140ab8fa901d5cc98f44c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":180,
              "y":1118},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c326e2d3e1c6468a9a0cca30edaf7baf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":180,
                  "y":1118},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5568c278a6a4446e947040b77f48893a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":760,
              "y":199},
            "size":{
              "width":31,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d08710fa418c4161970af1ec131790b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":760,
                  "y":199},
                "size":{
                  "width":31,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务详情",
                      "target":{
                        "targetType":"page",
                        "url":"任务详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "188d4d586ee4470b9d0c4b57e33c8bb0":{
      "scriptId":"u0"},
    "0ec79d55d0154839b0073e163a2a947a":{
      "scriptId":"u1"},
    "af762f3045b448c7b4629e12ebc8abf8":{
      "scriptId":"u2"},
    "f23fe017f2db4465978eda2fcbf2c99c":{
      "scriptId":"u3"},
    "2c7f7645de3a4631b05ba9bcf40b5e2e":{
      "scriptId":"u4"},
    "8306c46c66e24b0c94ddd319013cc761":{
      "scriptId":"u5"},
    "b0a7adf69adf4a5284dc4c8efa4a5fdb":{
      "scriptId":"u6"},
    "fe3d3d1ad8244e97926bbaa619c0f96f":{
      "scriptId":"u7"},
    "45709e240f4a4687bb8d64c412e4926a":{
      "scriptId":"u8"},
    "b3159700a9274b31b74cc914ff600d08":{
      "scriptId":"u9"},
    "e64b7e707c4d4743bd0369c96a738438":{
      "scriptId":"u10"},
    "5710b232cf8b424eb9541b4be9e1e2e4":{
      "scriptId":"u11"},
    "ed258f39893244e083c7aafec499edac":{
      "scriptId":"u12"},
    "42b8b7bd4c89424b81c78b329857e888":{
      "scriptId":"u13"},
    "18b21d1ad0d047c08913df6953c8c846":{
      "scriptId":"u14"},
    "1ac07c2f72134db98cf7d60d9fc61b44":{
      "scriptId":"u15"},
    "385ed29bf199455ea35e68b44f1a02c1":{
      "scriptId":"u16"},
    "fe36f680b37946d898510d130feab059":{
      "scriptId":"u17"},
    "995922764496464abb49e2cf4c3af1a6":{
      "scriptId":"u18"},
    "6e19a8b404aa407586d31e06ecc775c3":{
      "scriptId":"u19"},
    "e2fbab66001b40dcb03ab717af1e2529":{
      "scriptId":"u20"},
    "93259048376e4e7eb77170209dbafd00":{
      "scriptId":"u21"},
    "d3464cf4c83942f49b1f0150baefa0d0":{
      "scriptId":"u22"},
    "1bb1585643c041cd8d2d6075c42b5d2c":{
      "scriptId":"u23"},
    "b20195b11ff64dc28f114b47ed7dd7de":{
      "scriptId":"u24"},
    "fc87d2325eb546dcaa07d3f8f294f750":{
      "scriptId":"u25"},
    "8b4fa827558540b1854e567fff5e475d":{
      "scriptId":"u26"},
    "4744cacff68c48cc8471ac1cdfad62e6":{
      "scriptId":"u27"},
    "c2a3319b6f4b4582a234e9e36d9b7ac2":{
      "scriptId":"u28"},
    "615b147c2fe140ab8fa901d5cc98f44c":{
      "scriptId":"u29"},
    "c326e2d3e1c6468a9a0cca30edaf7baf":{
      "scriptId":"u30"},
    "5568c278a6a4446e947040b77f48893a":{
      "scriptId":"u31"},
    "d08710fa418c4161970af1ec131790b4":{
      "scriptId":"u32"}}});