$axure.loadCurrentPage({
  "url":"考勤.html",
  "generationDate":new Date(1515736332477),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"030069f4b7fe4ae4bf677f8f0f64c70f",
    "type":"Axure:Page",
    "name":"考勤",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ba30c9a0af50456eb783977b1d48b269",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":175,
              "y":73},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a3c897efa7343b7806a953f6db73d99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":175,
                  "y":73},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"7a2e6970b3c34085b53f01566672a4f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":175,
              "y":113},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"270af57b95ac4d6f84a751843d8ba71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":175,
                  "y":113},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"0571c89951734b788b6bcbb739f07d04",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":191,
              "y":134},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d3a2b0ce2b3491f8b9d9084a6882bd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":191,
                  "y":134},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"112a84dca3174764bead66bd4c4250be",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":175,
              "y":73},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cbd031b50224cc787e00a2e91a24ac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":175,
                  "y":73},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"6fbdf6fccf6740019c3c27f7106a9640",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":175,
              "y":203},
            "size":{
              "width":750,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c0c204439141e98fc29ab3b266a997",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":175,
                  "y":203},
                "size":{
                  "width":750,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 开始签到",
                      "target":{
                        "targetType":"page",
                        "url":"开始签到.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a02336fd4e94bdf823f891cd6f3d8ed",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":865,
              "y":256},
            "size":{
              "width":140,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u18_end.png",
            "line~":"images/管理员、老师/u35_line.png"}},
{
          "id":"cd0dead47f8440cc90b668c80a42fa8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":1015,
              "y":166},
            "size":{
              "width":695,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fcee60337a842fd888c01d99ee9d8dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":1015,
                  "y":166},
                "size":{
                  "width":695,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u11.png"}},
{
          "id":"99526a61e2d846c0b942d86f2f3220d3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":301},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"cc73001f8bb1444f93287294f68c1c92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "location":{
              "x":175,
              "y":307},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfaf6b4b201a4884a7fcee6ea915aeeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "location":{
                  "x":175,
                  "y":307},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"587f2dad31dd48fa8110fa9bd38d5e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":1000,
              "y":736},
            "size":{
              "width":550,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1717ba4ea24f4226b47507bd4ea3e69f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":1000,
                  "y":736},
                "size":{
                  "width":550,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u16.png"}},
{
          "id":"936e86717187400c871902216755c50f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1590,
              "y":736},
            "size":{
              "width":550,
              "height":390}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"333e31c6e76f48b4b36f2f83f97ab18f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1590,
                  "y":736},
                "size":{
                  "width":550,
                  "height":390}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u18.png"}},
{
          "id":"02219735c4b34b87b2e049a2ebe2b7b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":1610,
              "y":759},
            "size":{
              "width":470,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f7c33e438e044dda8a319c8b6033d4a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":1610,
                  "y":759},
                "size":{
                  "width":470,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee2fa0bbcc2a4ae0864192c9bee0b206",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1650,
              "y":861},
            "size":{
              "width":230,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbb5d60e5378441fbba22a8a1b8b1a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1650,
                  "y":861},
                "size":{
                  "width":230,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"8ae15bba883e49fb801cc01aae122e44",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1910,
              "y":861},
            "size":{
              "width":230,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bae77b4687664b6298da6cc3118f6ada",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1910,
                  "y":861},
                "size":{
                  "width":230,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"810ecd7d5c48464fb6eb1751e4c6e456",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1650,
              "y":961},
            "size":{
              "width":230,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b3a08e8357496d9e08b63d686230c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1650,
                  "y":961},
                "size":{
                  "width":230,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"a8436386c60149c28584465d636a8c6e",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1910,
              "y":961},
            "size":{
              "width":230,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e56db739564fc6a0bec2698cf7b32e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1910,
                  "y":961},
                "size":{
                  "width":230,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"57fae8238f7a4d91993388202e33e7d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1590,
              "y":1056},
            "size":{
              "width":270,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5735e48210884231b5e3828dc98e595f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1590,
                  "y":1056},
                "size":{
                  "width":270,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u30.png"}},
{
          "id":"40d305a75f464db08fd36060f8469536",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1860,
              "y":1056},
            "size":{
              "width":280,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec1aaefa91d745209825171f350da553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1860,
                  "y":1056},
                "size":{
                  "width":280,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u32.png"}},
{
          "id":"92db8db3bdb848e699522a3cef4bad7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":1000,
              "y":537},
            "size":{
              "width":550,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1896ebcd60604a4aacd35ee484fbdd4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":1000,
                  "y":537},
                "size":{
                  "width":550,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u16.png"}},
{
          "id":"2fa3240abe564c20b7acc656cffff660",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":412},
            "size":{
              "width":180,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c39b15b343340a19fe5d6b82318a336",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":412},
                "size":{
                  "width":180,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca929bff8e684df79370093437a618f7",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":446,
              "y":412},
            "size":{
              "width":209,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8724ccfaa5e24499b4f02293ab8bfb19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":446,
                  "y":412},
                "size":{
                  "width":209,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77d3164eb1794bcf9d5b14f6025f4d8e",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":783,
              "y":412},
            "size":{
              "width":142,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3928c837e17b432eab8791beadd5457d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":783,
                  "y":412},
                "size":{
                  "width":142,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a0aedbeb652402aa44a35399152aa9f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":606,
              "y":434},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7e195c1f36948c0a1aa0f328d3f0501",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":606,
                  "y":434},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u42.png"}},
{
          "id":"d1b96ec8ba754254b7a08c04b230f917",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":488},
            "size":{
              "width":180,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c068aa211124fd88c48f35c69685b77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":488},
                "size":{
                  "width":180,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e9542fb2502442f80d7ae21d2529ffa",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":542},
            "size":{
              "width":195,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1cd856594f042f6a6a130cebc8453ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":542},
                "size":{
                  "width":195,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f8d0d2d37b45480eb22a9d6aef58b439",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":446,
              "y":520},
            "size":{
              "width":209,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45a33393219948be87bf7f90cec9df07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":446,
                  "y":520},
                "size":{
                  "width":209,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9344730bf2394bb0a938af79a851092e",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":410},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cae6f46d4ce478ab3d9cf41165b59f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":560,
                  "y":410},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"95e4f51b9bda40a4a641e6e7d6cc87fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":807},
            "size":{
              "width":410,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/考勤/u52_line.png"}},
{
          "id":"b315d0a8f6584b2b9f28de2541461f60",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":479},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"e637dfd376fe4b76b6156d578ec9f8a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":604},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"735028ef823149a8b3a73f340603821a",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":624},
            "size":{
              "width":180,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c6a0082b0d043edadae28c679ecfa1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":624},
                "size":{
                  "width":180,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"40dae59852e444f88ba65e7fdd79e8d9",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":678},
            "size":{
              "width":195,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef4e90aa516456a8f8b12dc1b5cbe21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":678},
                "size":{
                  "width":195,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"779016652bc04f86925cb2356aa49bfa",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":446,
              "y":656},
            "size":{
              "width":209,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6fe278d6d524f7a97cce37fcb1a85bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":446,
                  "y":656},
                "size":{
                  "width":209,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"880d44ff279d4896ba7316468f3a484a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":740},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"2fd941c88ea045738121762e526fdde2",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":750},
            "size":{
              "width":180,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa8b18ad545c46908ae21e1a2e13e8e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":750},
                "size":{
                  "width":180,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b601e38a518445fa865e6b362b7d21f2",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":804},
            "size":{
              "width":195,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11034ecfda1645be8118dea213ba1491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":804},
                "size":{
                  "width":195,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80121655877347c4aa5dc21d8a7077a9",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":446,
              "y":782},
            "size":{
              "width":209,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c586397d58784bb8a61b3d1264ece9fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":446,
                  "y":782},
                "size":{
                  "width":209,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebc64394147c4f1682145b1ac89f2da8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":866},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"153952d3f06940b0bfb6bcee77cd6409",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":876},
            "size":{
              "width":180,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"841c6b79cd144cc8b0a18fc5cbd2c7e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":876},
                "size":{
                  "width":180,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a6c44a52cd84a1f9018729e5a5bcea8",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":930},
            "size":{
              "width":195,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e366f68e659746da9c2b905ebbe024c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":930},
                "size":{
                  "width":195,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3b6fdc21cf84cdeab85f0d39d666723",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":446,
              "y":908},
            "size":{
              "width":209,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e434344e304649de9a20e6f9aa11ad82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":446,
                  "y":908},
                "size":{
                  "width":209,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3733f5e567df4b088e71f184df26dbc0",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":992},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"4852bcc38b2946f99f2fff7cb860e15f",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":1012},
            "size":{
              "width":180,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b662586d60d9444e817e5decccfc90bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":1012},
                "size":{
                  "width":180,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6181477c407c4b118836556e9edc6702",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":175,
              "y":1066},
            "size":{
              "width":195,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34eb346c893849fd8a75b1f9944b5b6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":175,
                  "y":1066},
                "size":{
                  "width":195,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da7f3a1f9ac54d10842090ce22074f80",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":446,
              "y":1044},
            "size":{
              "width":209,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"63f0b0f8137548ec887caa15798d2701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":446,
                  "y":1044},
                "size":{
                  "width":209,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c8bc69467124150b895c7c8a3d4482e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":175,
              "y":1128},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"f918cd95e4c54ef3b210e1da17bf0c40",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":792,
              "y":520},
            "size":{
              "width":125,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a167d405955a4833b9cb71e06bd9eb60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":792,
                  "y":520},
                "size":{
                  "width":125,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/所在班级_u83.png"}},
{
          "id":"52c0e0c482a649498708818a37d360a6",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":792,
              "y":908},
            "size":{
              "width":125,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e9fdb3b3a84043b7ab694c176e2d0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":792,
                  "y":908},
                "size":{
                  "width":125,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/所在班级_u83.png"}},
{
          "id":"0dbb32fec0ec45c89ed317604cc9e2c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":748.266235351563,
              "y":1183.56396484375},
            "size":{
              "width":460,
              "height":10},
            "rotation":"65",
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u18_end.png",
            "line~":"images/考勤/u87_line.png"}},
{
          "id":"42777108f64b43238edb34e521e4175f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":1090,
              "y":1320},
            "size":{
              "width":535,
              "height":189}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2793e9895e94906a12ed7e27939325e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":1090,
                  "y":1320},
                "size":{
                  "width":535,
                  "height":189}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u88.png"}},
{
          "id":"194030c9c1464586b2c002fd9357583a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1635,
              "y":1320},
            "size":{
              "width":550,
              "height":800}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0307e3ec862845419eaa5897fa9237c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1635,
                  "y":1320},
                "size":{
                  "width":550,
                  "height":800}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u90.png"}},
{
          "id":"48ce586fd8d9469181078492a183236c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":1668,
              "y":1441},
            "size":{
              "width":185,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab9873177b5949d6ac0e34879b5bfc6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":1668,
                  "y":1441},
                "size":{
                  "width":185,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86f825b4f85442b789d94586527ddfea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":1668,
              "y":1519},
            "size":{
              "width":205,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f346055904245cf9d77554a76ecfaac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":1668,
                  "y":1519},
                "size":{
                  "width":205,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d533fa36092422885f82e36bd839f4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":1835,
              "y":1441},
            "size":{
              "width":185,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d181ee8ed40546a3b47d3cf5f6b8548a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":1835,
                  "y":1441},
                "size":{
                  "width":185,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d961f4aacc2b4039a119ab0c6ca1efcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":1703,
              "y":1654},
            "size":{
              "width":427,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88b11a35049c4f57a02cf789daabdf07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":1703,
                  "y":1654},
                "size":{
                  "width":427,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f499fd4dffd404bbaa757566d53f453",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1635,
              "y":1407},
            "size":{
              "width":550,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/考勤/u100_line.png"}},
{
          "id":"114f5990fe4748c1a09430c2465b801d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":1650,
              "y":1325},
            "size":{
              "width":185,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d8f0a3566c474aa34afaf3e63ccb0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":1650,
                  "y":1325},
                "size":{
                  "width":185,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dea416d4b6a74ef7b2a52edb272fde95",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":782,
              "y":1044},
            "size":{
              "width":135,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"913b7aa52f864609b6d3fcc28d141535",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":782,
                  "y":1044},
                "size":{
                  "width":135,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d73f76a7abf54211afe19676ea4c29da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1635,
              "y":1820},
            "size":{
              "width":550,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/考勤/u100_line.png"}},
{
          "id":"82975551169a4f5a8bfcdafdab9d3089",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":1668,
              "y":1855},
            "size":{
              "width":205,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a80e614299574493ba4a152a288af72f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":1668,
                  "y":1855},
                "size":{
                  "width":205,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efc488b7ec3641ea91dbb5327a86b0d3",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1703,
              "y":1955},
            "size":{
              "width":230,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27d1d590d5f74d229a0a8f3b7b8a5ccc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1703,
                  "y":1955},
                "size":{
                  "width":230,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"438f59362dee4545bc0ce5b5e65b7e22",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1980,
              "y":1955},
            "size":{
              "width":137,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"074d56d77a4c4d2d9a4fb417e1d33334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1980,
                  "y":1955},
                "size":{
                  "width":137,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"911852d5d29a49a09c2874adeee39588",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1635,
              "y":2050},
            "size":{
              "width":270,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5218f9a954f94f09b66a9bb3e35e0d04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1635,
                  "y":2050},
                "size":{
                  "width":270,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u30.png"}},
{
          "id":"6d04264a456c4bc0be18dd74a4029f3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1905,
              "y":2050},
            "size":{
              "width":280,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45b05cbb24ad4630b545c243d536de58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1905,
                  "y":2050},
                "size":{
                  "width":280,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u32.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ba30c9a0af50456eb783977b1d48b269":{
      "scriptId":"u0"},
    "8a3c897efa7343b7806a953f6db73d99":{
      "scriptId":"u1"},
    "7a2e6970b3c34085b53f01566672a4f7":{
      "scriptId":"u2"},
    "270af57b95ac4d6f84a751843d8ba71d":{
      "scriptId":"u3"},
    "0571c89951734b788b6bcbb739f07d04":{
      "scriptId":"u4"},
    "0d3a2b0ce2b3491f8b9d9084a6882bd7":{
      "scriptId":"u5"},
    "112a84dca3174764bead66bd4c4250be":{
      "scriptId":"u6"},
    "5cbd031b50224cc787e00a2e91a24ac0":{
      "scriptId":"u7"},
    "6fbdf6fccf6740019c3c27f7106a9640":{
      "scriptId":"u8"},
    "69c0c204439141e98fc29ab3b266a997":{
      "scriptId":"u9"},
    "8a02336fd4e94bdf823f891cd6f3d8ed":{
      "scriptId":"u10"},
    "cd0dead47f8440cc90b668c80a42fa8a":{
      "scriptId":"u11"},
    "9fcee60337a842fd888c01d99ee9d8dd":{
      "scriptId":"u12"},
    "99526a61e2d846c0b942d86f2f3220d3":{
      "scriptId":"u13"},
    "cc73001f8bb1444f93287294f68c1c92":{
      "scriptId":"u14"},
    "dfaf6b4b201a4884a7fcee6ea915aeeb":{
      "scriptId":"u15"},
    "587f2dad31dd48fa8110fa9bd38d5e97":{
      "scriptId":"u16"},
    "1717ba4ea24f4226b47507bd4ea3e69f":{
      "scriptId":"u17"},
    "936e86717187400c871902216755c50f":{
      "scriptId":"u18"},
    "333e31c6e76f48b4b36f2f83f97ab18f":{
      "scriptId":"u19"},
    "02219735c4b34b87b2e049a2ebe2b7b7":{
      "scriptId":"u20"},
    "0f7c33e438e044dda8a319c8b6033d4a":{
      "scriptId":"u21"},
    "ee2fa0bbcc2a4ae0864192c9bee0b206":{
      "scriptId":"u22"},
    "bbb5d60e5378441fbba22a8a1b8b1a17":{
      "scriptId":"u23"},
    "8ae15bba883e49fb801cc01aae122e44":{
      "scriptId":"u24"},
    "bae77b4687664b6298da6cc3118f6ada":{
      "scriptId":"u25"},
    "810ecd7d5c48464fb6eb1751e4c6e456":{
      "scriptId":"u26"},
    "93b3a08e8357496d9e08b63d686230c5":{
      "scriptId":"u27"},
    "a8436386c60149c28584465d636a8c6e":{
      "scriptId":"u28"},
    "e6e56db739564fc6a0bec2698cf7b32e":{
      "scriptId":"u29"},
    "57fae8238f7a4d91993388202e33e7d3":{
      "scriptId":"u30"},
    "5735e48210884231b5e3828dc98e595f":{
      "scriptId":"u31"},
    "40d305a75f464db08fd36060f8469536":{
      "scriptId":"u32"},
    "ec1aaefa91d745209825171f350da553":{
      "scriptId":"u33"},
    "92db8db3bdb848e699522a3cef4bad7f":{
      "scriptId":"u34"},
    "1896ebcd60604a4aacd35ee484fbdd4f":{
      "scriptId":"u35"},
    "2fa3240abe564c20b7acc656cffff660":{
      "scriptId":"u36"},
    "7c39b15b343340a19fe5d6b82318a336":{
      "scriptId":"u37"},
    "ca929bff8e684df79370093437a618f7":{
      "scriptId":"u38"},
    "8724ccfaa5e24499b4f02293ab8bfb19":{
      "scriptId":"u39"},
    "77d3164eb1794bcf9d5b14f6025f4d8e":{
      "scriptId":"u40"},
    "3928c837e17b432eab8791beadd5457d":{
      "scriptId":"u41"},
    "5a0aedbeb652402aa44a35399152aa9f":{
      "scriptId":"u42"},
    "c7e195c1f36948c0a1aa0f328d3f0501":{
      "scriptId":"u43"},
    "d1b96ec8ba754254b7a08c04b230f917":{
      "scriptId":"u44"},
    "7c068aa211124fd88c48f35c69685b77":{
      "scriptId":"u45"},
    "3e9542fb2502442f80d7ae21d2529ffa":{
      "scriptId":"u46"},
    "f1cd856594f042f6a6a130cebc8453ee":{
      "scriptId":"u47"},
    "f8d0d2d37b45480eb22a9d6aef58b439":{
      "scriptId":"u48"},
    "45a33393219948be87bf7f90cec9df07":{
      "scriptId":"u49"},
    "9344730bf2394bb0a938af79a851092e":{
      "scriptId":"u50"},
    "4cae6f46d4ce478ab3d9cf41165b59f4":{
      "scriptId":"u51"},
    "95e4f51b9bda40a4a641e6e7d6cc87fb":{
      "scriptId":"u52"},
    "b315d0a8f6584b2b9f28de2541461f60":{
      "scriptId":"u53"},
    "e637dfd376fe4b76b6156d578ec9f8a8":{
      "scriptId":"u54"},
    "735028ef823149a8b3a73f340603821a":{
      "scriptId":"u55"},
    "2c6a0082b0d043edadae28c679ecfa1a":{
      "scriptId":"u56"},
    "40dae59852e444f88ba65e7fdd79e8d9":{
      "scriptId":"u57"},
    "8ef4e90aa516456a8f8b12dc1b5cbe21":{
      "scriptId":"u58"},
    "779016652bc04f86925cb2356aa49bfa":{
      "scriptId":"u59"},
    "e6fe278d6d524f7a97cce37fcb1a85bc":{
      "scriptId":"u60"},
    "880d44ff279d4896ba7316468f3a484a":{
      "scriptId":"u61"},
    "2fd941c88ea045738121762e526fdde2":{
      "scriptId":"u62"},
    "fa8b18ad545c46908ae21e1a2e13e8e6":{
      "scriptId":"u63"},
    "b601e38a518445fa865e6b362b7d21f2":{
      "scriptId":"u64"},
    "11034ecfda1645be8118dea213ba1491":{
      "scriptId":"u65"},
    "80121655877347c4aa5dc21d8a7077a9":{
      "scriptId":"u66"},
    "c586397d58784bb8a61b3d1264ece9fd":{
      "scriptId":"u67"},
    "ebc64394147c4f1682145b1ac89f2da8":{
      "scriptId":"u68"},
    "153952d3f06940b0bfb6bcee77cd6409":{
      "scriptId":"u69"},
    "841c6b79cd144cc8b0a18fc5cbd2c7e6":{
      "scriptId":"u70"},
    "7a6c44a52cd84a1f9018729e5a5bcea8":{
      "scriptId":"u71"},
    "e366f68e659746da9c2b905ebbe024c2":{
      "scriptId":"u72"},
    "e3b6fdc21cf84cdeab85f0d39d666723":{
      "scriptId":"u73"},
    "e434344e304649de9a20e6f9aa11ad82":{
      "scriptId":"u74"},
    "3733f5e567df4b088e71f184df26dbc0":{
      "scriptId":"u75"},
    "4852bcc38b2946f99f2fff7cb860e15f":{
      "scriptId":"u76"},
    "b662586d60d9444e817e5decccfc90bd":{
      "scriptId":"u77"},
    "6181477c407c4b118836556e9edc6702":{
      "scriptId":"u78"},
    "34eb346c893849fd8a75b1f9944b5b6c":{
      "scriptId":"u79"},
    "da7f3a1f9ac54d10842090ce22074f80":{
      "scriptId":"u80"},
    "63f0b0f8137548ec887caa15798d2701":{
      "scriptId":"u81"},
    "7c8bc69467124150b895c7c8a3d4482e":{
      "scriptId":"u82"},
    "f918cd95e4c54ef3b210e1da17bf0c40":{
      "scriptId":"u83"},
    "a167d405955a4833b9cb71e06bd9eb60":{
      "scriptId":"u84"},
    "52c0e0c482a649498708818a37d360a6":{
      "scriptId":"u85"},
    "c1e9fdb3b3a84043b7ab694c176e2d0c":{
      "scriptId":"u86"},
    "0dbb32fec0ec45c89ed317604cc9e2c4":{
      "scriptId":"u87"},
    "42777108f64b43238edb34e521e4175f":{
      "scriptId":"u88"},
    "b2793e9895e94906a12ed7e27939325e":{
      "scriptId":"u89"},
    "194030c9c1464586b2c002fd9357583a":{
      "scriptId":"u90"},
    "0307e3ec862845419eaa5897fa9237c4":{
      "scriptId":"u91"},
    "48ce586fd8d9469181078492a183236c":{
      "scriptId":"u92"},
    "ab9873177b5949d6ac0e34879b5bfc6f":{
      "scriptId":"u93"},
    "86f825b4f85442b789d94586527ddfea":{
      "scriptId":"u94"},
    "8f346055904245cf9d77554a76ecfaac":{
      "scriptId":"u95"},
    "6d533fa36092422885f82e36bd839f4d":{
      "scriptId":"u96"},
    "d181ee8ed40546a3b47d3cf5f6b8548a":{
      "scriptId":"u97"},
    "d961f4aacc2b4039a119ab0c6ca1efcd":{
      "scriptId":"u98"},
    "88b11a35049c4f57a02cf789daabdf07":{
      "scriptId":"u99"},
    "1f499fd4dffd404bbaa757566d53f453":{
      "scriptId":"u100"},
    "114f5990fe4748c1a09430c2465b801d":{
      "scriptId":"u101"},
    "36d8f0a3566c474aa34afaf3e63ccb0c":{
      "scriptId":"u102"},
    "dea416d4b6a74ef7b2a52edb272fde95":{
      "scriptId":"u103"},
    "913b7aa52f864609b6d3fcc28d141535":{
      "scriptId":"u104"},
    "d73f76a7abf54211afe19676ea4c29da":{
      "scriptId":"u105"},
    "82975551169a4f5a8bfcdafdab9d3089":{
      "scriptId":"u106"},
    "a80e614299574493ba4a152a288af72f":{
      "scriptId":"u107"},
    "efc488b7ec3641ea91dbb5327a86b0d3":{
      "scriptId":"u108"},
    "27d1d590d5f74d229a0a8f3b7b8a5ccc":{
      "scriptId":"u109"},
    "438f59362dee4545bc0ce5b5e65b7e22":{
      "scriptId":"u110"},
    "074d56d77a4c4d2d9a4fb417e1d33334":{
      "scriptId":"u111"},
    "911852d5d29a49a09c2874adeee39588":{
      "scriptId":"u112"},
    "5218f9a954f94f09b66a9bb3e35e0d04":{
      "scriptId":"u113"},
    "6d04264a456c4bc0be18dd74a4029f3f":{
      "scriptId":"u114"},
    "45b05cbb24ad4630b545c243d536de58":{
      "scriptId":"u115"}}});