$axure.loadCurrentPage({
  "url":"签到.html",
  "generationDate":new Date(1515736338163),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"442e1092745d4499a2e44a913f951539",
    "type":"Axure:Page",
    "name":"签到",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a946ad31c494d3481d055f5e7b29b32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":166},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee6be87f55c542d2940f23f4ce66e401",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":166},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"7b333e1c206841debce5e9fa5ee25385",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":60,
              "y":206},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75710d2d4bd843de94029860a3210389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":60,
                  "y":206},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"a29eb77d0b544a54b576ae815f9866df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":227},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecadccb711244b91bd479d63b3800afd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":227},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"1a96392c4d2348edb381a9528e4fa848",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":60,
              "y":166},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e06b9c3ca70347078e422fd7db1637da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":60,
                  "y":166},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"5025eb20bfdc41f885b76462de127393",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":910,
              "y":166},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97a85b92ec774e5f8f4bfed89c869e35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":910,
                  "y":166},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"5248382a675746d1af64b75b05284333",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":910,
              "y":206},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3570d54b42a74b9f98501081371c8528",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":910,
                  "y":206},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"aaa9a6bffedf45578f2f7307b64cd5af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":926,
              "y":227},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05063cec016e4eaba79a5b7dcb8150f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":926,
                  "y":227},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"8f37d0f37f2048b09be8e22c221a9992",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":910,
              "y":166},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6377b0a460ba47a4a4b4a53a00c2193f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":910,
                  "y":166},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"75ff7bc971e34fc1b37c79d975fd7410",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":580},
            "size":{
              "width":526,
              "height":514}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2ffbf20c0a64d6388d61d87e88b85e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":580},
                "size":{
                  "width":526,
                  "height":514}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签到/u16.png"}},
{
          "id":"6b20670ef58041efba86aace5737aa02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"72px",
            "location":{
              "x":179,
              "y":358},
            "size":{
              "width":512,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596b90c0c1054f40807fd534141213f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"72px",
                "location":{
                  "x":179,
                  "y":358},
                "size":{
                  "width":512,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"637f1b4bcef940ba981e1eb784da2367",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":171,
              "y":450},
            "size":{
              "width":528,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e2dd7cc7a944bb89d47478b3d38e50e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":171,
                  "y":450},
                "size":{
                  "width":528,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"84228c6b8092436091d4ee4ec255793e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"72px",
            "location":{
              "x":994,
              "y":358},
            "size":{
              "width":581,
              "height":102}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d910e1bf1f1046d697eff664cabfce13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"72px",
                "location":{
                  "x":994,
                  "y":358},
                "size":{
                  "width":581,
                  "height":102}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d39a504c1bf4dd4b89410fe5c68c7a6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "horizontalAlignment":"center",
            "location":{
              "x":994,
              "y":580},
            "size":{
              "width":581,
              "height":160}},
          "adaptiveStyles":{
}},
{
          "id":"ee25efd090da42da84b5f2be88d3345a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1020,
              "y":450},
            "size":{
              "width":528,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e10a62c560b7471aa23f1dc9bc6775cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":450},
                "size":{
                  "width":528,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b666d498702479da28c8a066c834d42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1730,
              "y":166},
            "size":{
              "width":690,
              "height":814}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a6ca6e5975d4468a869658665d74890",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1730,
                  "y":166},
                "size":{
                  "width":690,
                  "height":814}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签到/u27.png"}},
{
          "id":"21e1dc1342f44fdf86c21e28e8fc5e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC33,
                  "opacity":1}}},
            "location":{
              "x":2020,
              "y":206},
            "size":{
              "width":110,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10d78c71d2314b33bdde9994a97cb4fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF00CC33,
                      "opacity":1}}},
                "location":{
                  "x":2020,
                  "y":206},
                "size":{
                  "width":110,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"1e6e10f9170a477791e18d70a3b9b693",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":1740,
              "y":474},
            "size":{
              "width":671,
              "height":240},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0132653bc711451693361a75dacd3add",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":1740,
                  "y":474},
                "size":{
                  "width":671,
                  "height":240},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"184a8a5494074fbe82553bf3d2845062",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"72px",
            "horizontalAlignment":"center",
            "location":{
              "x":1740,
              "y":736},
            "size":{
              "width":581,
              "height":160}},
          "adaptiveStyles":{
}},
{
          "id":"f4f973ad6d4e49649f91d4359884f0af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":60,
              "y":59},
            "size":{
              "width":760,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eb7b367e5b844648c9afae9eef7279e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":60,
                  "y":59},
                "size":{
                  "width":760,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a946ad31c494d3481d055f5e7b29b32":{
      "scriptId":"u0"},
    "ee6be87f55c542d2940f23f4ce66e401":{
      "scriptId":"u1"},
    "7b333e1c206841debce5e9fa5ee25385":{
      "scriptId":"u2"},
    "75710d2d4bd843de94029860a3210389":{
      "scriptId":"u3"},
    "a29eb77d0b544a54b576ae815f9866df":{
      "scriptId":"u4"},
    "ecadccb711244b91bd479d63b3800afd":{
      "scriptId":"u5"},
    "1a96392c4d2348edb381a9528e4fa848":{
      "scriptId":"u6"},
    "e06b9c3ca70347078e422fd7db1637da":{
      "scriptId":"u7"},
    "5025eb20bfdc41f885b76462de127393":{
      "scriptId":"u8"},
    "97a85b92ec774e5f8f4bfed89c869e35":{
      "scriptId":"u9"},
    "5248382a675746d1af64b75b05284333":{
      "scriptId":"u10"},
    "3570d54b42a74b9f98501081371c8528":{
      "scriptId":"u11"},
    "aaa9a6bffedf45578f2f7307b64cd5af":{
      "scriptId":"u12"},
    "05063cec016e4eaba79a5b7dcb8150f6":{
      "scriptId":"u13"},
    "8f37d0f37f2048b09be8e22c221a9992":{
      "scriptId":"u14"},
    "6377b0a460ba47a4a4b4a53a00c2193f":{
      "scriptId":"u15"},
    "75ff7bc971e34fc1b37c79d975fd7410":{
      "scriptId":"u16"},
    "f2ffbf20c0a64d6388d61d87e88b85e0":{
      "scriptId":"u17"},
    "6b20670ef58041efba86aace5737aa02":{
      "scriptId":"u18"},
    "596b90c0c1054f40807fd534141213f0":{
      "scriptId":"u19"},
    "637f1b4bcef940ba981e1eb784da2367":{
      "scriptId":"u20"},
    "0e2dd7cc7a944bb89d47478b3d38e50e":{
      "scriptId":"u21"},
    "84228c6b8092436091d4ee4ec255793e":{
      "scriptId":"u22"},
    "d910e1bf1f1046d697eff664cabfce13":{
      "scriptId":"u23"},
    "9d39a504c1bf4dd4b89410fe5c68c7a6":{
      "scriptId":"u24"},
    "ee25efd090da42da84b5f2be88d3345a":{
      "scriptId":"u25"},
    "e10a62c560b7471aa23f1dc9bc6775cc":{
      "scriptId":"u26"},
    "3b666d498702479da28c8a066c834d42":{
      "scriptId":"u27"},
    "4a6ca6e5975d4468a869658665d74890":{
      "scriptId":"u28"},
    "21e1dc1342f44fdf86c21e28e8fc5e08":{
      "scriptId":"u29"},
    "10d78c71d2314b33bdde9994a97cb4fc":{
      "scriptId":"u30"},
    "1e6e10f9170a477791e18d70a3b9b693":{
      "scriptId":"u31"},
    "0132653bc711451693361a75dacd3add":{
      "scriptId":"u32"},
    "184a8a5494074fbe82553bf3d2845062":{
      "scriptId":"u33"},
    "f4f973ad6d4e49649f91d4359884f0af":{
      "scriptId":"u34"},
    "4eb7b367e5b844648c9afae9eef7279e":{
      "scriptId":"u35"}}});