$axure.loadCurrentPage({
  "url":"我的事项.html",
  "generationDate":new Date(1515736332050),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"be099bd72dde4933af9157d3877fd922",
    "type":"Axure:Page",
    "name":"我的事项",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"872718b64bcc45a6b3af7fef42e5604d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":70,
              "y":186},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3949cea2caea419f88829693c3d2c684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":70,
                  "y":186},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u198.png"}},
{
          "id":"d304b7e553374c79bb38b5241eac2c1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "verticalAlignment":"top",
            "location":{
              "x":70,
              "y":97},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85922177c43c4516a473da68046b6c78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "verticalAlignment":"top",
                "location":{
                  "x":70,
                  "y":97},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"7d4d15205b4b4503935982b80e1852b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":86,
              "y":118},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5eca4ad3fa4c32baa3a351ebfb6e33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":86,
                  "y":118},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理员、老师",
                      "target":{
                        "targetType":"page",
                        "url":"管理员、老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"f8782ef7abfd4fd9b6b408d3c0f69765",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":70,
              "y":57},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be1626d6a1846cc966ab2e25ec0c4a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":70,
                  "y":57},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"e131bc165e3249f99439556b4155b509",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":74,
              "y":188},
            "size":{
              "width":742,
              "height":132},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3881c2cb2194cf9b67401f145a32701",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":74,
                  "y":188},
                "size":{
                  "width":742,
                  "height":132},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u8.png"}},
{
          "id":"b084def28f4d4a5e9670a520571feca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":166,
              "y":197},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20ede27dd4cc4832aa37982ec06f81ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":166,
                  "y":197},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"55cf3c9b48c148fd9d29d7065cb5f604",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":84,
              "y":218},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b0cc5deae8942d99ba4e0ae9d99f234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":84,
                  "y":218},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"abe63b1c9ebb492586911d6af7ca37eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":350},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29cb871ce5974d3ba11e16eaaf481bbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":350},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"7ed786681fe44d7d99c69e66784d0745",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":678,
              "y":213},
            "size":{
              "width":128,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5e6e95e1874a89abc84f4d55e93e51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":678,
                  "y":213},
                "size":{
                  "width":128,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6c4db8c55d74db3811bf606b2aa83e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":675,
              "y":380},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ec281cb9376480f8f843907116d07c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":675,
                  "y":380},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5181f9dedf7b41b08c01caeaf185923f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":164,
              "y":360},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fa2a57a3d09454a959199f53df930d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":360},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfd6527af3694e2793ecc643a21b16a4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":84,
              "y":387},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dad926a36b443c4b89de6aa0c0cf1d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":84,
                  "y":387},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"bf11b827c75c42e58b6eeb877ee0d9d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":519},
            "size":{
              "width":746,
              "height":141},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3817de52d073489cb249318a400d576c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":519},
                "size":{
                  "width":746,
                  "height":141},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u14.png"}},
{
          "id":"8c50accd6b7f481fb8f6a767283aa710",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":166,
              "y":535},
            "size":{
              "width":202,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b6f0f89b5914459ac79487a2c025f27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":166,
                  "y":535},
                "size":{
                  "width":202,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0d18547f90443dfab9f2fb81d571acf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":82,
              "y":556},
            "size":{
              "width":64,
              "height":69}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a46e3c22bcc44da90d3a70353003a6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":82,
                  "y":556},
                "size":{
                  "width":64,
                  "height":69}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u12.png"}},
{
          "id":"3c74e83db6cc4f95955588dd4cba37de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":678,
              "y":558},
            "size":{
              "width":139,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd566ded5e5448c0927ccd799dced825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":678,
                  "y":558},
                "size":{
                  "width":139,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa768e3d21464594b831399a9858234f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":354,
              "y":136},
            "size":{
              "width":164,
              "height":48},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a6bd18e3921440588f1a697f2448f15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":354,
                  "y":136},
                "size":{
                  "width":164,
                  "height":48},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 全部活动动态面板 向下滑动 500 ms 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["b229525f56754625be5295426393deb8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"lightbox",
                              "lightbox":{
                                "r":228,
                                "g":228,
                                "b":228,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u32.png"}},
{
          "id":"5aea069844db4959863d509403841fe0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":489,
              "y":150},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"078bc956bacd4598a3f829b79ed6c7dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489,
                  "y":150},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 全部活动动态面板 向下滑动 500 ms 灯箱效果",
                      "objectsToFades":[{
                          "objectPath":["b229525f56754625be5295426393deb8"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"lightbox",
                              "lightbox":{
                                "r":228,
                                "g":228,
                                "b":228,
                                "a":155}}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的事项/u34.png"}},
{
          "id":"a056805a7a244769b1486fbbddd6a2d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":166,
              "y":255},
            "size":{
              "width":352,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02e1f8da514a4ca884a1dc05f72c3765",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":166,
                  "y":255},
                "size":{
                  "width":352,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7e785a7186b469780f63c47ffb4931d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":164,
              "y":425},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd9f8e5e7d8745b4902874a3dccb6580",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":164,
                  "y":425},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c2399b6fc8e469ba683a4c8264fc8a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":166,
              "y":595},
            "size":{
              "width":364,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5c9f149a5314b6e8d953fb264bab1ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":166,
                  "y":595},
                "size":{
                  "width":364,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f5733014d09412ea6bd3de07c92af91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":659,
              "y":124},
            "size":{
              "width":41,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbed782a8a414e5eb4b0f696c4ef7ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":659,
                  "y":124},
                "size":{
                  "width":41,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u42.png"}},
{
          "id":"29cf7f547660491aaba11cce09175767",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":277},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"95aebfd4eba145efb07dd776c7a3f42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1010,
              "y":253.5},
            "size":{
              "width":290,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8c05a4f28214a8c950fda7ea79785f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1010,
                  "y":253.5},
                "size":{
                  "width":290,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u45.png"}},
{
          "id":"8a363fec131047ce9a28d0a417e48544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":710,
              "y":116},
            "size":{
              "width":90,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"531dca9f0d0f4e8090ac5a8b04c22e6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":710,
                  "y":116},
                "size":{
                  "width":90,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cf1873b7aac401da0928a770795716a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":139},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"ea6099f214c94b73a66bdcdc1f75bc1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "location":{
              "x":1010,
              "y":116},
            "size":{
              "width":450,
              "height":68}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13739b4a74b64fd7840ba30f5e931156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "location":{
                  "x":1010,
                  "y":116},
                "size":{
                  "width":450,
                  "height":68}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u50.png"}},
{
          "id":"b229525f56754625be5295426393deb8",
          "label":"全部活动动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":70,
              "y":188},
            "size":{
              "width":750,
              "height":300},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c1887f7b889c4a7ea92c2d3aee24d916",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"62a23ed91db248b9b2c1a602102ec976",
                  "label":"",
                  "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":300}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42d29b649d614fcfa6a506fecf2d556f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":300}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/我的事项/u53.png"}},
{
                  "id":"6ef0eb4513a14402bb47cfa8cf0963f1",
                  "label":"",
                  "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":750,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd980e2bc8684bd1b4e7117e9ab4265f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":750,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"29992e94836840aba47684c66cea751f",
                  "label":"",
                  "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "location":{
                      "x":0,
                      "y":196},
                    "size":{
                      "width":750,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/管理员、老师/u370_line.png"}},
{
                  "id":"3f3ad3cb6c6d48e29732f0e8461b5d64",
                  "label":"",
                  "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":102},
                    "size":{
                      "width":750,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e3553e8353c4eae8e7e2babeacb0133",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":102},
                        "size":{
                          "width":750,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0de94f12a54a49a68e63187f3f7ffd79",
                  "label":"",
                  "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "location":{
                      "x":0,
                      "y":98},
                    "size":{
                      "width":750,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/管理员、老师/u370_line.png"}},
{
                  "id":"90c22af2323b431982841c163b9426e2",
                  "label":"",
                  "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":4},
                    "size":{
                      "width":750,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a85bf5b556d4bb1bbf71820f1326c74",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b229525f56754625be5295426393deb8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":4},
                        "size":{
                          "width":750,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "872718b64bcc45a6b3af7fef42e5604d":{
      "scriptId":"u0"},
    "3949cea2caea419f88829693c3d2c684":{
      "scriptId":"u1"},
    "d304b7e553374c79bb38b5241eac2c1e":{
      "scriptId":"u2"},
    "85922177c43c4516a473da68046b6c78":{
      "scriptId":"u3"},
    "7d4d15205b4b4503935982b80e1852b2":{
      "scriptId":"u4"},
    "fc5eca4ad3fa4c32baa3a351ebfb6e33":{
      "scriptId":"u5"},
    "f8782ef7abfd4fd9b6b408d3c0f69765":{
      "scriptId":"u6"},
    "4be1626d6a1846cc966ab2e25ec0c4a5":{
      "scriptId":"u7"},
    "e131bc165e3249f99439556b4155b509":{
      "scriptId":"u8"},
    "b3881c2cb2194cf9b67401f145a32701":{
      "scriptId":"u9"},
    "b084def28f4d4a5e9670a520571feca0":{
      "scriptId":"u10"},
    "20ede27dd4cc4832aa37982ec06f81ea":{
      "scriptId":"u11"},
    "55cf3c9b48c148fd9d29d7065cb5f604":{
      "scriptId":"u12"},
    "7b0cc5deae8942d99ba4e0ae9d99f234":{
      "scriptId":"u13"},
    "abe63b1c9ebb492586911d6af7ca37eb":{
      "scriptId":"u14"},
    "29cb871ce5974d3ba11e16eaaf481bbb":{
      "scriptId":"u15"},
    "7ed786681fe44d7d99c69e66784d0745":{
      "scriptId":"u16"},
    "bc5e6e95e1874a89abc84f4d55e93e51":{
      "scriptId":"u17"},
    "c6c4db8c55d74db3811bf606b2aa83e4":{
      "scriptId":"u18"},
    "3ec281cb9376480f8f843907116d07c4":{
      "scriptId":"u19"},
    "5181f9dedf7b41b08c01caeaf185923f":{
      "scriptId":"u20"},
    "5fa2a57a3d09454a959199f53df930d8":{
      "scriptId":"u21"},
    "bfd6527af3694e2793ecc643a21b16a4":{
      "scriptId":"u22"},
    "4dad926a36b443c4b89de6aa0c0cf1d9":{
      "scriptId":"u23"},
    "bf11b827c75c42e58b6eeb877ee0d9d0":{
      "scriptId":"u24"},
    "3817de52d073489cb249318a400d576c":{
      "scriptId":"u25"},
    "8c50accd6b7f481fb8f6a767283aa710":{
      "scriptId":"u26"},
    "1b6f0f89b5914459ac79487a2c025f27":{
      "scriptId":"u27"},
    "a0d18547f90443dfab9f2fb81d571acf":{
      "scriptId":"u28"},
    "5a46e3c22bcc44da90d3a70353003a6d":{
      "scriptId":"u29"},
    "3c74e83db6cc4f95955588dd4cba37de":{
      "scriptId":"u30"},
    "fd566ded5e5448c0927ccd799dced825":{
      "scriptId":"u31"},
    "fa768e3d21464594b831399a9858234f":{
      "scriptId":"u32"},
    "5a6bd18e3921440588f1a697f2448f15":{
      "scriptId":"u33"},
    "5aea069844db4959863d509403841fe0":{
      "scriptId":"u34"},
    "078bc956bacd4598a3f829b79ed6c7dd":{
      "scriptId":"u35"},
    "a056805a7a244769b1486fbbddd6a2d1":{
      "scriptId":"u36"},
    "02e1f8da514a4ca884a1dc05f72c3765":{
      "scriptId":"u37"},
    "b7e785a7186b469780f63c47ffb4931d":{
      "scriptId":"u38"},
    "fd9f8e5e7d8745b4902874a3dccb6580":{
      "scriptId":"u39"},
    "2c2399b6fc8e469ba683a4c8264fc8a1":{
      "scriptId":"u40"},
    "c5c9f149a5314b6e8d953fb264bab1ac":{
      "scriptId":"u41"},
    "3f5733014d09412ea6bd3de07c92af91":{
      "scriptId":"u42"},
    "cbed782a8a414e5eb4b0f696c4ef7ac3":{
      "scriptId":"u43"},
    "29cf7f547660491aaba11cce09175767":{
      "scriptId":"u44"},
    "95aebfd4eba145efb07dd776c7a3f42b":{
      "scriptId":"u45"},
    "b8c05a4f28214a8c950fda7ea79785f5":{
      "scriptId":"u46"},
    "8a363fec131047ce9a28d0a417e48544":{
      "scriptId":"u47"},
    "531dca9f0d0f4e8090ac5a8b04c22e6b":{
      "scriptId":"u48"},
    "6cf1873b7aac401da0928a770795716a":{
      "scriptId":"u49"},
    "ea6099f214c94b73a66bdcdc1f75bc1a":{
      "scriptId":"u50"},
    "13739b4a74b64fd7840ba30f5e931156":{
      "scriptId":"u51"},
    "b229525f56754625be5295426393deb8":{
      "scriptId":"u52"},
    "62a23ed91db248b9b2c1a602102ec976":{
      "scriptId":"u53"},
    "42d29b649d614fcfa6a506fecf2d556f":{
      "scriptId":"u54"},
    "6ef0eb4513a14402bb47cfa8cf0963f1":{
      "scriptId":"u55"},
    "cd980e2bc8684bd1b4e7117e9ab4265f":{
      "scriptId":"u56"},
    "29992e94836840aba47684c66cea751f":{
      "scriptId":"u57"},
    "3f3ad3cb6c6d48e29732f0e8461b5d64":{
      "scriptId":"u58"},
    "2e3553e8353c4eae8e7e2babeacb0133":{
      "scriptId":"u59"},
    "0de94f12a54a49a68e63187f3f7ffd79":{
      "scriptId":"u60"},
    "90c22af2323b431982841c163b9426e2":{
      "scriptId":"u61"},
    "3a85bf5b556d4bb1bbf71820f1326c74":{
      "scriptId":"u62"}}});