$axure.loadCurrentPage({
  "url":"数据统计_1.html",
  "generationDate":new Date(1515736339658),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"19d0b6999d3e468cb95887a2908c251b",
    "type":"Axure:Page",
    "name":"数据统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5f6cad2ae7364a9192b75b38c3ed7a9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":90,
              "y":186},
            "size":{
              "width":750,
              "height":1204},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b05926f00d9348fa9584e7d34e58419b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":90,
                  "y":186},
                "size":{
                  "width":750,
                  "height":1204},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u0.png"}},
{
          "id":"768e8a81a47a46c4aea46dddf27ce44f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":90,
              "y":98},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aaf071dadec4673a23ca3240291c5d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":90,
                  "y":98},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"35b831f5239b43369bbe184e9b574f33",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":118},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9035723968b44a9faf10ea418946ff43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":118},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"13c9f8edf009470ca58cc3e9952c13cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":90,
              "y":58},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc5f15753ac94e4792cdc2f973ae208a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":90,
                  "y":58},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"a1cfcce42c4d4a6eb8cabdd25fbcac94",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "lineSpacing":"72px",
            "location":{
              "x":92,
              "y":188},
            "size":{
              "width":746,
              "height":302},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54fe69923bc047efbc1f0b25ccbebd19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"72px",
                "location":{
                  "x":92,
                  "y":188},
                "size":{
                  "width":746,
                  "height":302},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u8.png"}},
{
          "id":"5b50ef7953e946eebcdb8016269b9c3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":179,
              "y":228},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ed78c73da747a7944c35debfa70086",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":179,
                  "y":228},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"98404275fca147b9b0581fadb08ec6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":148,
              "y":397},
            "size":{
              "width":212,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0df9871752e74e5eb5e2c3284183b7de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":148,
                  "y":397},
                "size":{
                  "width":212,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f56187a92eb41cb846a3ce76335d7d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":628},
            "size":{
              "width":746,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b4de52119cb4fdcbd9641846c458c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":628},
                "size":{
                  "width":746,
                  "height":102},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u14.png"}},
{
          "id":"5107e649406f4a35ad6aabe8f6b2d05d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":118,
              "y":642},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b92abb38a0149179435fc5994c4a6ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":118,
                  "y":642},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e0f52c3bc7c84f7aae9a06d26662c4ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":320,
              "y":642},
            "size":{
              "width":200,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6196e3536064db18a4b622ca0126150",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":320,
                  "y":642},
                "size":{
                  "width":200,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cc8079b7c014fe893d901aa59c04abf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":731},
            "size":{
              "width":746,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c660eb5f4aea4e32b9ee46714e7873f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":731},
                "size":{
                  "width":746,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加任务/u117.png"}},
{
          "id":"1f8b445a47d2478a86f4a508e565173f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":118,
              "y":743},
            "size":{
              "width":170,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb3586c1df24a95875231c9ab404982",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":118,
                  "y":743},
                "size":{
                  "width":170,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd954edbb93c4564a7cb68cfd5e999a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":320,
              "y":741},
            "size":{
              "width":200,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f2f928de82145459953fc055e319941",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":320,
                  "y":741},
                "size":{
                  "width":200,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78347154c2fa4485ad28cbddfc4d19b5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":559},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"a3978f519511455db3bb60d042ddcb5d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1800,
              "y":607},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"72edcb099c86451dbd0d86e41ae7878c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":2030,
              "y":562},
            "size":{
              "width":400,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49534555fb241a597c766df960a171e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":2030,
                  "y":562},
                "size":{
                  "width":400,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生/u84.png"}},
{
          "id":"9387fe05545c428e8598a2434e7e74fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1800,
              "y":1333},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"ed4adf2568824edc91042a810eed23a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":2030,
              "y":1288},
            "size":{
              "width":400,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a7c4e6603c4f55ad937c363f1437a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":2030,
                  "y":1288},
                "size":{
                  "width":400,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/学生/u84.png"}},
{
          "id":"0ed1c6cc2e3346bb89189050102decdb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":92,
              "y":1290},
            "size":{
              "width":746,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7db496dfde034a54956382c07e45f56e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":92,
                  "y":1290},
                "size":{
                  "width":746,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/数据统计_1/u33.png"}},
{
          "id":"1fa34fa5fe634f51be6d304efd3664fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":589,
              "y":229},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bce98ba7005434995bb493af3af11e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":589,
                  "y":229},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"a373097e73ff418aab6950d252d22710",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":558,
              "y":397},
            "size":{
              "width":212,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2db4b417502145aa95b5c35ddb92cf07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":558,
                  "y":397},
                "size":{
                  "width":212,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8ce5137f0b14ea4ba3124156aa1e386",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":92,
              "y":538},
            "size":{
              "width":744,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f346f6e02f8447019a9043a9846fd187",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":92,
                  "y":538},
                "size":{
                  "width":744,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u39.png"}},
{
          "id":"6771dc2609fc44188c5c91e8bfbe372a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":123,
              "y":552},
            "size":{
              "width":680,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67aa5311594a4f7084b580488c93b9da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":123,
                  "y":552},
                "size":{
                  "width":680,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73e41689baa044c0b738c341cec3ebd2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":803,
              "y":564.5},
            "size":{
              "width":29,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f24884e6587c4a69ac6456abc65418d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":803,
                  "y":564.5},
                "size":{
                  "width":29,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 得分明细",
                      "target":{
                        "targetType":"page",
                        "url":"得分明细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/数据统计_1/u43.png"}},
{
          "id":"55a9f56ebed245269e9cc6c591cf31e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1070,
              "y":186},
            "size":{
              "width":750,
              "height":1204},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ee6f310e0e445679f992d5e5cbf484b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1070,
                  "y":186},
                "size":{
                  "width":750,
                  "height":1204},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u0.png"}},
{
          "id":"4de3805384534a249492416fb3001784",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":1070,
              "y":98},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3244b75d88948379ce96ea43b425cdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":1070,
                  "y":98},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"160e0b6b392a4f85b11ddbaf784f9d2b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1086,
              "y":118},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e3381de15a4a8eaf2504c54f708b5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1086,
                  "y":118},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"23732b7bb53f4df68b80bd72c0066880",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1070,
              "y":58},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"140dd6f33d164f2fa04f2d193727bf8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1070,
                  "y":58},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"9b3d11255639495184c5c7948d7b510d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "lineSpacing":"72px",
            "location":{
              "x":1072,
              "y":188},
            "size":{
              "width":746,
              "height":302},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb9bef0deaf14a63af43db74ebef080f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"72px",
                "location":{
                  "x":1072,
                  "y":188},
                "size":{
                  "width":746,
                  "height":302},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u8.png"}},
{
          "id":"afe591f9f16c48a4babe00fc739c9630",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1159,
              "y":228},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d8b293df5be46c782aace361665f5d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1159,
                  "y":228},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"26d69fd0610b46d59662ccd4a57f9488",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":1128,
              "y":397},
            "size":{
              "width":212,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7116caa99e548ef90b315c4ee5e0e9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":1128,
                  "y":397},
                "size":{
                  "width":212,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0505a282a10449d4ad00e889f25f45da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1072,
              "y":628},
            "size":{
              "width":746,
              "height":102},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ff2f4bce434dd69b7353e464800c07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1072,
                  "y":628},
                "size":{
                  "width":746,
                  "height":102},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u14.png"}},
{
          "id":"9766b6c37a81484f8ee93e5b5c2d48ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1098,
              "y":642},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea6669d9c30542f0b781c2bba60be7b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1098,
                  "y":642},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9181d4afc37246749c9905a86a9e4873",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1300,
              "y":642},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0392929611324d5693650b9a6790cd31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1300,
                  "y":642},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4abede6f2dbe4378950d96a791426e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1072,
              "y":731},
            "size":{
              "width":746,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1516572ef0ff481ea53ed105ea6a247f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1072,
                  "y":731},
                "size":{
                  "width":746,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加任务/u117.png"}},
{
          "id":"9a69acaccaef4dfcb864c3cc3821e6f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1098,
              "y":743},
            "size":{
              "width":170,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b270c00b2efb474b9b2e510c8e9a70f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1098,
                  "y":743},
                "size":{
                  "width":170,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"817036aff13f4f7ea9389676f5c287a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1300,
              "y":741},
            "size":{
              "width":200,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9250fb1e567346e59e0ea76ab7a01e1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1300,
                  "y":741},
                "size":{
                  "width":200,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de4aade393614550a343eaca54f06119",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1072,
              "y":1290},
            "size":{
              "width":746,
              "height":98},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0f91e4b7604777987fee4e0ca876ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1072,
                  "y":1290},
                "size":{
                  "width":746,
                  "height":98},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/数据统计_1/u33.png"}},
{
          "id":"00af724850f347feb3b7f7e6d3e5eba1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1569,
              "y":229},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12f6d2b20320430baa264a3e437b3b3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1569,
                  "y":229},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"e40f6e2eb34a465d8c023b1aee179557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":1538,
              "y":397},
            "size":{
              "width":212,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f05931a024241688e1007b91fc2bee8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":1538,
                  "y":397},
                "size":{
                  "width":212,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34e09154af4f4cc9b176b20a37141dd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1072,
              "y":538},
            "size":{
              "width":744,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"544d0807b8c64a0c879f1a65b69a2e20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1072,
                  "y":538},
                "size":{
                  "width":744,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u39.png"}},
{
          "id":"08a0ad7aeffd45fb9199429ef78efd05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":1103,
              "y":552},
            "size":{
              "width":680,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5fd4feca1fc45cd86f1e22fd3b09e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":1103,
                  "y":552},
                "size":{
                  "width":680,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3e22688535444ba815f5e9492a26470",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1783,
              "y":564},
            "size":{
              "width":29,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92bc3f65711c4468bbb1b6ca2c5c7c0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1783,
                  "y":564},
                "size":{
                  "width":29,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 得分明细",
                      "target":{
                        "targetType":"page",
                        "url":"得分明细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/数据统计_1/u43.png"}},
{
          "id":"8f9e85cd720047049d54178934e22ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1580,
              "y":643},
            "size":{
              "width":203,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fe3eb63b673439282016536e69a9858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1580,
                  "y":643},
                "size":{
                  "width":203,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9440955ef5504c0e8a84dac23521d900",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"72px",
            "location":{
              "x":1580,
              "y":740},
            "size":{
              "width":203,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ddde19996cb8458f839a0749100bc426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"72px",
                "location":{
                  "x":1580,
                  "y":740},
                "size":{
                  "width":203,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cb2126283ad44b6b10a9adb57328a49",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1800,
              "y":233},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"bcb3f081151145c794d3146f6708b8ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":2030,
              "y":188},
            "size":{
              "width":320,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bd83b8a480d411a8196d1b209d73835",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":2030,
                  "y":188},
                "size":{
                  "width":320,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计_1/u88.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5f6cad2ae7364a9192b75b38c3ed7a9d":{
      "scriptId":"u0"},
    "b05926f00d9348fa9584e7d34e58419b":{
      "scriptId":"u1"},
    "768e8a81a47a46c4aea46dddf27ce44f":{
      "scriptId":"u2"},
    "8aaf071dadec4673a23ca3240291c5d0":{
      "scriptId":"u3"},
    "35b831f5239b43369bbe184e9b574f33":{
      "scriptId":"u4"},
    "9035723968b44a9faf10ea418946ff43":{
      "scriptId":"u5"},
    "13c9f8edf009470ca58cc3e9952c13cf":{
      "scriptId":"u6"},
    "dc5f15753ac94e4792cdc2f973ae208a":{
      "scriptId":"u7"},
    "a1cfcce42c4d4a6eb8cabdd25fbcac94":{
      "scriptId":"u8"},
    "54fe69923bc047efbc1f0b25ccbebd19":{
      "scriptId":"u9"},
    "5b50ef7953e946eebcdb8016269b9c3e":{
      "scriptId":"u10"},
    "f6ed78c73da747a7944c35debfa70086":{
      "scriptId":"u11"},
    "98404275fca147b9b0581fadb08ec6fc":{
      "scriptId":"u12"},
    "0df9871752e74e5eb5e2c3284183b7de":{
      "scriptId":"u13"},
    "7f56187a92eb41cb846a3ce76335d7d9":{
      "scriptId":"u14"},
    "4b4de52119cb4fdcbd9641846c458c37":{
      "scriptId":"u15"},
    "5107e649406f4a35ad6aabe8f6b2d05d":{
      "scriptId":"u16"},
    "8b92abb38a0149179435fc5994c4a6ce":{
      "scriptId":"u17"},
    "e0f52c3bc7c84f7aae9a06d26662c4ff":{
      "scriptId":"u18"},
    "b6196e3536064db18a4b622ca0126150":{
      "scriptId":"u19"},
    "1cc8079b7c014fe893d901aa59c04abf":{
      "scriptId":"u20"},
    "c660eb5f4aea4e32b9ee46714e7873f0":{
      "scriptId":"u21"},
    "1f8b445a47d2478a86f4a508e565173f":{
      "scriptId":"u22"},
    "bfb3586c1df24a95875231c9ab404982":{
      "scriptId":"u23"},
    "fd954edbb93c4564a7cb68cfd5e999a7":{
      "scriptId":"u24"},
    "8f2f928de82145459953fc055e319941":{
      "scriptId":"u25"},
    "78347154c2fa4485ad28cbddfc4d19b5":{
      "scriptId":"u26"},
    "a3978f519511455db3bb60d042ddcb5d":{
      "scriptId":"u27"},
    "72edcb099c86451dbd0d86e41ae7878c":{
      "scriptId":"u28"},
    "a49534555fb241a597c766df960a171e":{
      "scriptId":"u29"},
    "9387fe05545c428e8598a2434e7e74fb":{
      "scriptId":"u30"},
    "ed4adf2568824edc91042a810eed23a4":{
      "scriptId":"u31"},
    "c6a7c4e6603c4f55ad937c363f1437a4":{
      "scriptId":"u32"},
    "0ed1c6cc2e3346bb89189050102decdb":{
      "scriptId":"u33"},
    "7db496dfde034a54956382c07e45f56e":{
      "scriptId":"u34"},
    "1fa34fa5fe634f51be6d304efd3664fa":{
      "scriptId":"u35"},
    "4bce98ba7005434995bb493af3af11e5":{
      "scriptId":"u36"},
    "a373097e73ff418aab6950d252d22710":{
      "scriptId":"u37"},
    "2db4b417502145aa95b5c35ddb92cf07":{
      "scriptId":"u38"},
    "d8ce5137f0b14ea4ba3124156aa1e386":{
      "scriptId":"u39"},
    "f346f6e02f8447019a9043a9846fd187":{
      "scriptId":"u40"},
    "6771dc2609fc44188c5c91e8bfbe372a":{
      "scriptId":"u41"},
    "67aa5311594a4f7084b580488c93b9da":{
      "scriptId":"u42"},
    "73e41689baa044c0b738c341cec3ebd2":{
      "scriptId":"u43"},
    "f24884e6587c4a69ac6456abc65418d9":{
      "scriptId":"u44"},
    "55a9f56ebed245269e9cc6c591cf31e8":{
      "scriptId":"u45"},
    "8ee6f310e0e445679f992d5e5cbf484b":{
      "scriptId":"u46"},
    "4de3805384534a249492416fb3001784":{
      "scriptId":"u47"},
    "e3244b75d88948379ce96ea43b425cdd":{
      "scriptId":"u48"},
    "160e0b6b392a4f85b11ddbaf784f9d2b":{
      "scriptId":"u49"},
    "73e3381de15a4a8eaf2504c54f708b5d":{
      "scriptId":"u50"},
    "23732b7bb53f4df68b80bd72c0066880":{
      "scriptId":"u51"},
    "140dd6f33d164f2fa04f2d193727bf8a":{
      "scriptId":"u52"},
    "9b3d11255639495184c5c7948d7b510d":{
      "scriptId":"u53"},
    "cb9bef0deaf14a63af43db74ebef080f":{
      "scriptId":"u54"},
    "afe591f9f16c48a4babe00fc739c9630":{
      "scriptId":"u55"},
    "1d8b293df5be46c782aace361665f5d9":{
      "scriptId":"u56"},
    "26d69fd0610b46d59662ccd4a57f9488":{
      "scriptId":"u57"},
    "b7116caa99e548ef90b315c4ee5e0e9c":{
      "scriptId":"u58"},
    "0505a282a10449d4ad00e889f25f45da":{
      "scriptId":"u59"},
    "e6ff2f4bce434dd69b7353e464800c07":{
      "scriptId":"u60"},
    "9766b6c37a81484f8ee93e5b5c2d48ab":{
      "scriptId":"u61"},
    "ea6669d9c30542f0b781c2bba60be7b6":{
      "scriptId":"u62"},
    "9181d4afc37246749c9905a86a9e4873":{
      "scriptId":"u63"},
    "0392929611324d5693650b9a6790cd31":{
      "scriptId":"u64"},
    "4abede6f2dbe4378950d96a791426e84":{
      "scriptId":"u65"},
    "1516572ef0ff481ea53ed105ea6a247f":{
      "scriptId":"u66"},
    "9a69acaccaef4dfcb864c3cc3821e6f6":{
      "scriptId":"u67"},
    "b270c00b2efb474b9b2e510c8e9a70f5":{
      "scriptId":"u68"},
    "817036aff13f4f7ea9389676f5c287a0":{
      "scriptId":"u69"},
    "9250fb1e567346e59e0ea76ab7a01e1f":{
      "scriptId":"u70"},
    "de4aade393614550a343eaca54f06119":{
      "scriptId":"u71"},
    "7a0f91e4b7604777987fee4e0ca876ea":{
      "scriptId":"u72"},
    "00af724850f347feb3b7f7e6d3e5eba1":{
      "scriptId":"u73"},
    "12f6d2b20320430baa264a3e437b3b3a":{
      "scriptId":"u74"},
    "e40f6e2eb34a465d8c023b1aee179557":{
      "scriptId":"u75"},
    "2f05931a024241688e1007b91fc2bee8":{
      "scriptId":"u76"},
    "34e09154af4f4cc9b176b20a37141dd6":{
      "scriptId":"u77"},
    "544d0807b8c64a0c879f1a65b69a2e20":{
      "scriptId":"u78"},
    "08a0ad7aeffd45fb9199429ef78efd05":{
      "scriptId":"u79"},
    "d5fd4feca1fc45cd86f1e22fd3b09e40":{
      "scriptId":"u80"},
    "e3e22688535444ba815f5e9492a26470":{
      "scriptId":"u81"},
    "92bc3f65711c4468bbb1b6ca2c5c7c0a":{
      "scriptId":"u82"},
    "8f9e85cd720047049d54178934e22ed0":{
      "scriptId":"u83"},
    "6fe3eb63b673439282016536e69a9858":{
      "scriptId":"u84"},
    "9440955ef5504c0e8a84dac23521d900":{
      "scriptId":"u85"},
    "ddde19996cb8458f839a0749100bc426":{
      "scriptId":"u86"},
    "4cb2126283ad44b6b10a9adb57328a49":{
      "scriptId":"u87"},
    "bcb3f081151145c794d3146f6708b8ad":{
      "scriptId":"u88"},
    "7bd83b8a480d411a8196d1b209d73835":{
      "scriptId":"u89"}}});