$axure.loadCurrentPage({
  "url":"请假.html",
  "generationDate":new Date(1515736338412),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b111426cd962491882378fbf0be3ad4a",
    "type":"Axure:Page",
    "name":"请假",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b788e3185ad342d0a5260146e0536053",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":76},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dea1bf01344049a4b034ad055a78f0dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":76},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"95270d6287174a5891351f77a9aba6ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":240,
              "y":116},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cf9f14dbd474b669d991f8db49679bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":240,
                  "y":116},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"5d5614a26608477496d1cf31438b75ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":256,
              "y":137},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79a42a55bd004fc8a613c8ae25bb02f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":256,
                  "y":137},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"207e4fee092045c683523e25c14790aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":240,
              "y":76},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d3793a6da343dab5e70629e5ee9f80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":240,
                  "y":76},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"eb161324dac74f5d9f0c33af52764cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":206},
            "size":{
              "width":750,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e4f667571284a789f36981635024929",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":206},
                "size":{
                  "width":750,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31cb3926101f444ca58965583974f857",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":269,
              "y":207},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8add866dd1ee4e17a58ce9b1a89de661",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":269,
                  "y":207},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d844bdce54f4cc5a85ea63099c65347",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "opacity":"0.2",
            "location":{
              "x":705,
              "y":207},
            "size":{
              "width":231,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79fe54e7eac6412c8ae781c6932df76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "opacity":"0.2",
                "location":{
                  "x":705,
                  "y":207},
                "size":{
                  "width":231,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2b160486f71c45e6ac5f8057b69cbd32",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":970,
              "y":240.5},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/学生管理/u46_line.png"}},
{
          "id":"b81a48bb8de14a7b9f102b61ca3bd0db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":1170,
              "y":186},
            "size":{
              "width":660,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5338dd27a8ef4e1ba69b442c048b563b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":1170,
                  "y":186},
                "size":{
                  "width":660,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤_1/u19.png"}},
{
          "id":"b09aecae575344878a60baa2ab5317f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":936,
              "y":225},
            "size":{
              "width":24,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4843aaec78c24c68a007ce41599210db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":936,
                  "y":225},
                "size":{
                  "width":24,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u17.png"}},
{
          "id":"1b12e724f1c7431b955d6551c1b7ad82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":270,
              "y":286},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"552988c674ff4b83ad0d82a7f121d5c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":286},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6e08206cec04d5ca47891842239ad4b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":368},
            "size":{
              "width":690,
              "height":250}},
          "adaptiveStyles":{
}},
{
          "id":"d9b4903b24f04876842201e683e59edd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":240,
              "y":1312},
            "size":{
              "width":750,
              "height":98}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f6b8e2c6dd14ff39bcde67e59e9b013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":240,
                  "y":1312},
                "size":{
                  "width":750,
                  "height":98}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u22.png"}},
{
          "id":"fb1c6179a6af44db839e99207f3387f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1000,
              "y":1347},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/学生管理/u46_line.png"}},
{
          "id":"2d04102de82842bbbd9b9767bf26e8a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":1210,
              "y":1312},
            "size":{
              "width":470,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444b23c32b3b41ccaf47d17e068b2a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":1210,
                  "y":1312},
                "size":{
                  "width":470,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u25.png"}},
{
          "id":"653af13b422b4e1abbe6d864f3974f02",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":674,
              "y":628},
            "size":{
              "width":285,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1071f8b98f6d4bc983e99dafa8f4cb08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":674,
                  "y":628},
                "size":{
                  "width":285,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6637391ed834f5eaa6dbd3239bac8c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":270,
              "y":925},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"965902daf8494238bcf806618124399b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":270,
                  "y":925},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b37ad0845c234f2d9cf42de4f2184d34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "opacity":"0.2",
            "location":{
              "x":706,
              "y":920},
            "size":{
              "width":231,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c9eff1070d4bb9a0a536502f477333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "opacity":"0.2",
                "location":{
                  "x":706,
                  "y":920},
                "size":{
                  "width":231,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01acb48fe1bf4c3b9b2477d332f6866f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":936,
              "y":938},
            "size":{
              "width":24,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b9a0aaeb1a64435869430bc4d2db0f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":936,
                  "y":938},
                "size":{
                  "width":24,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u17.png"}},
{
          "id":"3713199b2bb44986b16d2af39c038209",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":240,
              "y":1001},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"d5581bafd18f4d5d983b4449347a87a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":269,
              "y":1026},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"261951e9690e4cb4a81ff6dfa7076ac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":269,
                  "y":1026},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddaca31a1228467ca2a7eba9c9259cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "opacity":"0.2",
            "location":{
              "x":706,
              "y":1021},
            "size":{
              "width":230,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16509482d6084b649acfa31e072393c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "opacity":"0.2",
                "location":{
                  "x":706,
                  "y":1021},
                "size":{
                  "width":230,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d83de73a3c6d4c3493ac24c05a4af8ce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":935,
              "y":1039},
            "size":{
              "width":24,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ae0b01ae50d4abaa24d0778594d8946",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":935,
                  "y":1039},
                "size":{
                  "width":24,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u17.png"}},
{
          "id":"6708830e5cac41db9b8d2ae942201752",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":240,
              "y":280},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"198abf83bc624cb08fbfa2865ee6ad6a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":240,
              "y":688},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"b7cd30adc6dc4bb8bee36d02746398f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":243,
              "y":693},
            "size":{
              "width":746,
              "height":37},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"851dfb0c2d4f441782e09675ef53f52a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":243,
                  "y":693},
                "size":{
                  "width":746,
                  "height":37},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u44.png"}},
{
          "id":"02f94fb63f474cdca525e352136b7a03",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":280,
              "y":766},
            "size":{
              "width":230,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e81ca49b25947fca03488952cadf36d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":280,
                  "y":766},
                "size":{
                  "width":230,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"97a88e6f331f4e16b9eecdc836a9c608",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":280,
              "y":850},
            "size":{
              "width":600,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1196692e8dc948ab887939b13cb72c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":280,
                  "y":850},
                "size":{
                  "width":600,
                  "height":33}},
              "adaptiveStyles":{
}}]},
{
          "id":"572405b5e6634505bb175deecd2f533f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":240,
              "y":907},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"f2fdfa5282a541d58cd699f7436e0cd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":240,
              "y":1107},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"f26b2a423ef24c048b065cc43c59ee8a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":789},
            "size":{
              "width":1080,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/请假/u52_line.png"}},
{
          "id":"2a4ab59684f24c4ca71d2f3732e3dc6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":2200,
              "y":76},
            "size":{
              "width":750,
              "height":1377}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35f985cafeac4cf18b16068cef3aa0d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2200,
                  "y":76},
                "size":{
                  "width":750,
                  "height":1377}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u53.png"}},
{
          "id":"241149b3684c4a889ffccbdfaf40390a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":2200,
              "y":116},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3539effc5bf54d51872ea1c174493c86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":2200,
                  "y":116},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"ecb47782950c4a9299dc0ce926a04a73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2216,
              "y":137},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1055d636a1c4f43a16efe7f648b088c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2216,
                  "y":137},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"20dc1ea59aee48bba7fa9ee281f31ee6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":2200,
              "y":76},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbded98407c748d5941683709a097f40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":2200,
                  "y":76},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"711bee7b39af47adb6ec237221cb60d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":2200,
              "y":206},
            "size":{
              "width":750,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0df1ad2c06504b24bf51089a50f645b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2200,
                  "y":206},
                "size":{
                  "width":750,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95a42dd93cf44363bd8a65631f13afcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":2229,
              "y":207},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7c968f8c18e4fa2ab571d6fbcea97d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2229,
                  "y":207},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c66d03eec294be5a369caf2e400e71d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "opacity":"0.2",
            "location":{
              "x":2790,
              "y":207},
            "size":{
              "width":106,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf79713af58f44e185f519e30a5c7345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "opacity":"0.2",
                "location":{
                  "x":2790,
                  "y":207},
                "size":{
                  "width":106,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90a9c60332744859bf0c20603753a89e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":2230,
              "y":300},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b18248fdd90d4da49139e96f81e6ff0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2230,
                  "y":300},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eed6f3056be74c2fb9bd3175a0b03206",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":2232,
              "y":727},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8bf1eb11d5d4e089d8e5ec4bd5b0b46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2232,
                  "y":727},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ae289a7fd0b4b1686e2962e9aece6e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "opacity":"0.2",
            "location":{
              "x":2668,
              "y":727},
            "size":{
              "width":231,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96c1cf31ab4e428982352598c5ba1f5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "opacity":"0.2",
                "location":{
                  "x":2668,
                  "y":727},
                "size":{
                  "width":231,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae5accc874bf4b9d99ad1be9ad422d08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":2202,
              "y":808},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"0b99ae5bbace473d96b76f6ed41499c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":2231,
              "y":828},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2196c6c53f9342f0a1838c34af7f1448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2231,
                  "y":828},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d24e7e56aaf42c98a1b7c840cf9b195",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "opacity":"0.2",
            "location":{
              "x":2668,
              "y":828},
            "size":{
              "width":230,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5260e810c28948f1b65319137130328f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "opacity":"0.2",
                "location":{
                  "x":2668,
                  "y":828},
                "size":{
                  "width":230,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"164e07d06459434f91c07ea7cd9a5407",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":2200,
              "y":280},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"0b9acfd7444244b5b01bb8fa43a002e1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":2202,
              "y":613},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"f15e2f4663b64f2dbdadd46c33af54af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":2202,
              "y":480},
            "size":{
              "width":746,
              "height":138},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9164e0c4df4e4f5f96a2733d41bbdd71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":2202,
                  "y":480},
                "size":{
                  "width":746,
                  "height":138},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u80.png"}},
{
          "id":"fe8a93e848ab4fbbb93ab8b04b6adc13",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":2202,
              "y":714},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"bcfc3adab29343e9817febde56961ae7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":2202,
              "y":909},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"771b576815d14b8fb705678a800d19a8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":2201,
              "y":1260},
            "size":{
              "width":748,
              "height":90}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 取消动态面板",
                      "objectsToFades":[{
                          "objectPath":["3b2c6529311b4feaacbd2d2f9ed1063a"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"19f69a9ae06542b59b342e72b640999d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":243,
              "y":1116},
            "size":{
              "width":746,
              "height":91},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fdd085dc2014449a63110ee95cd6f8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":243,
                  "y":1116},
                "size":{
                  "width":746,
                  "height":91},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u85.png"}},
{
          "id":"dca4c636dbcf47129b07ab9d297b26ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":269,
              "y":1116},
            "size":{
              "width":711,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d14dd929ca44e6796b2022c87c0f8dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":269,
                  "y":1116},
                "size":{
                  "width":711,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9754b5655b1742fdb74451555a6daae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":2242,
              "y":633},
            "size":{
              "width":620,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90b80ed0c9ca414cb5d6b579ccb976a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2242,
                  "y":633},
                "size":{
                  "width":620,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc551712f5704c789cff0217537039cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":2202,
              "y":1350},
            "size":{
              "width":746,
              "height":103},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"471904dc3b4f481ba9d9d19538728432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":2202,
                  "y":1350},
                "size":{
                  "width":746,
                  "height":103},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u91.png"}},
{
          "id":"3b2c6529311b4feaacbd2d2f9ed1063a",
          "label":"取消动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":2202,
              "y":1219},
            "size":{
              "width":746,
              "height":233},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9c0a6ee43fc04232a98c0192b2215d50",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e0451a36221e45f8b366e3f31dc00e01",
                  "label":"",
                  "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":746,
                      "height":233},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc395ac5688e420daf9c874172221a08",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":746,
                          "height":233},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/管理员、老师/u397.png"}},
{
                  "id":"d2e4b7c8c672491db1a7727e9027613c",
                  "label":"",
                  "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "size":{
                      "width":746,
                      "height":71},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4caadbd6597b40fbbb849873249177ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "size":{
                          "width":746,
                          "height":71},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 编辑活动",
                              "target":{
                                "targetType":"page",
                                "url":"编辑活动.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/管理员、老师/u382.png"}},
{
                  "id":"7b070c20be454b6ebe4ec6f71a2f9fe6",
                  "label":"",
                  "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":81},
                    "size":{
                      "width":746,
                      "height":71},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9a4ed67d67140fe9f2a11eb32743e19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":81},
                        "size":{
                          "width":746,
                          "height":71},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/管理员、老师/u382.png"}},
{
                  "id":"ec2a42150f9245489c04bba798a38dc4",
                  "label":"",
                  "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":162},
                    "size":{
                      "width":746,
                      "height":71},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"499f512a9a214e568d71c00d764a675f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b2c6529311b4feaacbd2d2f9ed1063a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":162},
                        "size":{
                          "width":746,
                          "height":71},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/管理员、老师/u382.png"}}]}]},
{
          "id":"cb0a6fd2d2254e1696135fa82d1afbce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":2949,
              "y":1305},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/学生管理/u46_line.png"}},
{
          "id":"d32110932b144ce2b966642cda1cb615",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":3159,
              "y":1270},
            "size":{
              "width":530,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f92aad5282f3437d8a3baee630215dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":3159,
                  "y":1270},
                "size":{
                  "width":530,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u103.png"}},
{
          "id":"ce5f82bfe5c946dea5b1fec559ba9c1b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":2229,
              "y":381},
            "size":{
              "width":170,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1934a6e8182401e8b1cfa91104378da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2229,
                  "y":381},
                "size":{
                  "width":170,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b580573daef4760a6ce2536745dcd00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":2230,
              "y":510},
            "size":{
              "width":360,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17b2da110a864134a33ae65bae8e5968",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":2230,
                  "y":510},
                "size":{
                  "width":360,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"533c1a89ca36460fb5c03f849463a65f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":2990,
              "y":480},
            "size":{
              "width":630,
              "height":101}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"20f1c05e3d1b4dc0acdf48ebbf216519",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":2990,
                  "y":480},
                "size":{
                  "width":630,
                  "height":101}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fc03311cec84d819d499d5da65a14ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "lineSpacing":"36px",
            "location":{
              "x":1460,
              "y":634},
            "size":{
              "width":330,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ad8a37454f0436ab235cfd0a375d0fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "lineSpacing":"36px",
                "location":{
                  "x":1460,
                  "y":634},
                "size":{
                  "width":330,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u111.png"}},
{
          "id":"3fc624ddf72f4d829c04c4f1591437a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":3159,
              "y":1411},
            "size":{
              "width":531,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e2919f1760043a0944b0cc5bbc9bc36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":3159,
                  "y":1411},
                "size":{
                  "width":531,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/请假/u113.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b788e3185ad342d0a5260146e0536053":{
      "scriptId":"u0"},
    "dea1bf01344049a4b034ad055a78f0dc":{
      "scriptId":"u1"},
    "95270d6287174a5891351f77a9aba6ce":{
      "scriptId":"u2"},
    "5cf9f14dbd474b669d991f8db49679bc":{
      "scriptId":"u3"},
    "5d5614a26608477496d1cf31438b75ab":{
      "scriptId":"u4"},
    "79a42a55bd004fc8a613c8ae25bb02f4":{
      "scriptId":"u5"},
    "207e4fee092045c683523e25c14790aa":{
      "scriptId":"u6"},
    "c4d3793a6da343dab5e70629e5ee9f80":{
      "scriptId":"u7"},
    "eb161324dac74f5d9f0c33af52764cf1":{
      "scriptId":"u8"},
    "8e4f667571284a789f36981635024929":{
      "scriptId":"u9"},
    "31cb3926101f444ca58965583974f857":{
      "scriptId":"u10"},
    "8add866dd1ee4e17a58ce9b1a89de661":{
      "scriptId":"u11"},
    "1d844bdce54f4cc5a85ea63099c65347":{
      "scriptId":"u12"},
    "79fe54e7eac6412c8ae781c6932df76b":{
      "scriptId":"u13"},
    "2b160486f71c45e6ac5f8057b69cbd32":{
      "scriptId":"u14"},
    "b81a48bb8de14a7b9f102b61ca3bd0db":{
      "scriptId":"u15"},
    "5338dd27a8ef4e1ba69b442c048b563b":{
      "scriptId":"u16"},
    "b09aecae575344878a60baa2ab5317f5":{
      "scriptId":"u17"},
    "4843aaec78c24c68a007ce41599210db":{
      "scriptId":"u18"},
    "1b12e724f1c7431b955d6551c1b7ad82":{
      "scriptId":"u19"},
    "552988c674ff4b83ad0d82a7f121d5c9":{
      "scriptId":"u20"},
    "e6e08206cec04d5ca47891842239ad4b":{
      "scriptId":"u21"},
    "d9b4903b24f04876842201e683e59edd":{
      "scriptId":"u22"},
    "0f6b8e2c6dd14ff39bcde67e59e9b013":{
      "scriptId":"u23"},
    "fb1c6179a6af44db839e99207f3387f1":{
      "scriptId":"u24"},
    "2d04102de82842bbbd9b9767bf26e8a1":{
      "scriptId":"u25"},
    "444b23c32b3b41ccaf47d17e068b2a00":{
      "scriptId":"u26"},
    "653af13b422b4e1abbe6d864f3974f02":{
      "scriptId":"u27"},
    "1071f8b98f6d4bc983e99dafa8f4cb08":{
      "scriptId":"u28"},
    "c6637391ed834f5eaa6dbd3239bac8c3":{
      "scriptId":"u29"},
    "965902daf8494238bcf806618124399b":{
      "scriptId":"u30"},
    "b37ad0845c234f2d9cf42de4f2184d34":{
      "scriptId":"u31"},
    "a2c9eff1070d4bb9a0a536502f477333":{
      "scriptId":"u32"},
    "01acb48fe1bf4c3b9b2477d332f6866f":{
      "scriptId":"u33"},
    "0b9a0aaeb1a64435869430bc4d2db0f4":{
      "scriptId":"u34"},
    "3713199b2bb44986b16d2af39c038209":{
      "scriptId":"u35"},
    "d5581bafd18f4d5d983b4449347a87a3":{
      "scriptId":"u36"},
    "261951e9690e4cb4a81ff6dfa7076ac2":{
      "scriptId":"u37"},
    "ddaca31a1228467ca2a7eba9c9259cf8":{
      "scriptId":"u38"},
    "16509482d6084b649acfa31e072393c6":{
      "scriptId":"u39"},
    "d83de73a3c6d4c3493ac24c05a4af8ce":{
      "scriptId":"u40"},
    "9ae0b01ae50d4abaa24d0778594d8946":{
      "scriptId":"u41"},
    "6708830e5cac41db9b8d2ae942201752":{
      "scriptId":"u42"},
    "198abf83bc624cb08fbfa2865ee6ad6a":{
      "scriptId":"u43"},
    "b7cd30adc6dc4bb8bee36d02746398f9":{
      "scriptId":"u44"},
    "851dfb0c2d4f441782e09675ef53f52a":{
      "scriptId":"u45"},
    "02f94fb63f474cdca525e352136b7a03":{
      "scriptId":"u46"},
    "0e81ca49b25947fca03488952cadf36d":{
      "scriptId":"u47"},
    "97a88e6f331f4e16b9eecdc836a9c608":{
      "scriptId":"u48"},
    "1196692e8dc948ab887939b13cb72c37":{
      "scriptId":"u49"},
    "572405b5e6634505bb175deecd2f533f":{
      "scriptId":"u50"},
    "f2fdfa5282a541d58cd699f7436e0cd8":{
      "scriptId":"u51"},
    "f26b2a423ef24c048b065cc43c59ee8a":{
      "scriptId":"u52"},
    "2a4ab59684f24c4ca71d2f3732e3dc6b":{
      "scriptId":"u53"},
    "35f985cafeac4cf18b16068cef3aa0d4":{
      "scriptId":"u54"},
    "241149b3684c4a889ffccbdfaf40390a":{
      "scriptId":"u55"},
    "3539effc5bf54d51872ea1c174493c86":{
      "scriptId":"u56"},
    "ecb47782950c4a9299dc0ce926a04a73":{
      "scriptId":"u57"},
    "c1055d636a1c4f43a16efe7f648b088c":{
      "scriptId":"u58"},
    "20dc1ea59aee48bba7fa9ee281f31ee6":{
      "scriptId":"u59"},
    "fbded98407c748d5941683709a097f40":{
      "scriptId":"u60"},
    "711bee7b39af47adb6ec237221cb60d1":{
      "scriptId":"u61"},
    "0df1ad2c06504b24bf51089a50f645b2":{
      "scriptId":"u62"},
    "95a42dd93cf44363bd8a65631f13afcd":{
      "scriptId":"u63"},
    "d7c968f8c18e4fa2ab571d6fbcea97d6":{
      "scriptId":"u64"},
    "2c66d03eec294be5a369caf2e400e71d":{
      "scriptId":"u65"},
    "cf79713af58f44e185f519e30a5c7345":{
      "scriptId":"u66"},
    "90a9c60332744859bf0c20603753a89e":{
      "scriptId":"u67"},
    "b18248fdd90d4da49139e96f81e6ff0e":{
      "scriptId":"u68"},
    "eed6f3056be74c2fb9bd3175a0b03206":{
      "scriptId":"u69"},
    "d8bf1eb11d5d4e089d8e5ec4bd5b0b46":{
      "scriptId":"u70"},
    "9ae289a7fd0b4b1686e2962e9aece6e7":{
      "scriptId":"u71"},
    "96c1cf31ab4e428982352598c5ba1f5a":{
      "scriptId":"u72"},
    "ae5accc874bf4b9d99ad1be9ad422d08":{
      "scriptId":"u73"},
    "0b99ae5bbace473d96b76f6ed41499c8":{
      "scriptId":"u74"},
    "2196c6c53f9342f0a1838c34af7f1448":{
      "scriptId":"u75"},
    "1d24e7e56aaf42c98a1b7c840cf9b195":{
      "scriptId":"u76"},
    "5260e810c28948f1b65319137130328f":{
      "scriptId":"u77"},
    "164e07d06459434f91c07ea7cd9a5407":{
      "scriptId":"u78"},
    "0b9acfd7444244b5b01bb8fa43a002e1":{
      "scriptId":"u79"},
    "f15e2f4663b64f2dbdadd46c33af54af":{
      "scriptId":"u80"},
    "9164e0c4df4e4f5f96a2733d41bbdd71":{
      "scriptId":"u81"},
    "fe8a93e848ab4fbbb93ab8b04b6adc13":{
      "scriptId":"u82"},
    "bcfc3adab29343e9817febde56961ae7":{
      "scriptId":"u83"},
    "771b576815d14b8fb705678a800d19a8":{
      "scriptId":"u84"},
    "19f69a9ae06542b59b342e72b640999d":{
      "scriptId":"u85"},
    "2fdd085dc2014449a63110ee95cd6f8c":{
      "scriptId":"u86"},
    "dca4c636dbcf47129b07ab9d297b26ee":{
      "scriptId":"u87"},
    "7d14dd929ca44e6796b2022c87c0f8dd":{
      "scriptId":"u88"},
    "9754b5655b1742fdb74451555a6daae0":{
      "scriptId":"u89"},
    "90b80ed0c9ca414cb5d6b579ccb976a4":{
      "scriptId":"u90"},
    "cc551712f5704c789cff0217537039cd":{
      "scriptId":"u91"},
    "471904dc3b4f481ba9d9d19538728432":{
      "scriptId":"u92"},
    "3b2c6529311b4feaacbd2d2f9ed1063a":{
      "scriptId":"u93"},
    "e0451a36221e45f8b366e3f31dc00e01":{
      "scriptId":"u94"},
    "dc395ac5688e420daf9c874172221a08":{
      "scriptId":"u95"},
    "d2e4b7c8c672491db1a7727e9027613c":{
      "scriptId":"u96"},
    "4caadbd6597b40fbbb849873249177ce":{
      "scriptId":"u97"},
    "7b070c20be454b6ebe4ec6f71a2f9fe6":{
      "scriptId":"u98"},
    "d9a4ed67d67140fe9f2a11eb32743e19":{
      "scriptId":"u99"},
    "ec2a42150f9245489c04bba798a38dc4":{
      "scriptId":"u100"},
    "499f512a9a214e568d71c00d764a675f":{
      "scriptId":"u101"},
    "cb0a6fd2d2254e1696135fa82d1afbce":{
      "scriptId":"u102"},
    "d32110932b144ce2b966642cda1cb615":{
      "scriptId":"u103"},
    "f92aad5282f3437d8a3baee630215dfb":{
      "scriptId":"u104"},
    "ce5f82bfe5c946dea5b1fec559ba9c1b":{
      "scriptId":"u105"},
    "c1934a6e8182401e8b1cfa91104378da":{
      "scriptId":"u106"},
    "9b580573daef4760a6ce2536745dcd00":{
      "scriptId":"u107"},
    "17b2da110a864134a33ae65bae8e5968":{
      "scriptId":"u108"},
    "533c1a89ca36460fb5c03f849463a65f":{
      "scriptId":"u109"},
    "20f1c05e3d1b4dc0acdf48ebbf216519":{
      "scriptId":"u110"},
    "0fc03311cec84d819d499d5da65a14ba":{
      "scriptId":"u111"},
    "4ad8a37454f0436ab235cfd0a375d0fd":{
      "scriptId":"u112"},
    "3fc624ddf72f4d829c04c4f1591437a1":{
      "scriptId":"u113"},
    "1e2919f1760043a0944b0cc5bbc9bc36":{
      "scriptId":"u114"}}});