$axure.loadCurrentPage({
  "url":"开始签到.html",
  "generationDate":new Date(1515736332677),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9962a3397d12419692da8edbd0ee46a9",
    "type":"Axure:Page",
    "name":"开始签到",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"affc5082ac684dec9a6e87c662159662",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "location":{
              "x":60,
              "y":20},
            "size":{
              "width":640,
              "height":81},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5e34b50ef0f483f9d0aa433dece0a5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "location":{
                  "x":60,
                  "y":20},
                "size":{
                  "width":640,
                  "height":81},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u0.png"}},
{
          "id":"0093871864cd4ecf8c46748b531966ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":159},
            "size":{
              "width":640,
              "height":1101}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e754f99b8b96448e87927056cc757359",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":159},
                "size":{
                  "width":640,
                  "height":1101}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u2.png"}},
{
          "id":"bce844c745854c9294acd3ab5be14d46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":60,
              "y":143},
            "size":{
              "width":640,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d7fe060a6fb4b68959e5fde7911eec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":60,
                  "y":143},
                "size":{
                  "width":640,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u4.png"}},
{
          "id":"bb6ccb145eb7406ebc45a808bd6488a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":60,
              "y":183},
            "size":{
              "width":640,
              "height":74}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19d12ee40c58432ab90738d5d4609289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":60,
                  "y":183},
                "size":{
                  "width":640,
                  "height":74}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u6.png"}},
{
          "id":"11c96b8a14b24d608e320eea0b8901a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":73,
              "y":201},
            "size":{
              "width":38,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5a1a7fa42334470b372adfac9d7c92f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":73,
                  "y":201},
                "size":{
                  "width":38,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"206530e8ded24c12854d67b3a1f2ed54",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontWeight":"400",
            "location":{
              "x":316,
              "y":201},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb0a7d2284054c7b803c88cb99a25af0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"400",
                "location":{
                  "x":316,
                  "y":201},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4278200148214beb89a96e1f04db2bbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":257},
            "size":{
              "width":640,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb8c48df5f484e5888a8f0e90910d976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":257},
                "size":{
                  "width":640,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u12.png"}},
{
          "id":"edf7b22d30a14ee5b59784f8a09e11ae",
          "label":"签到动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":563},
            "size":{
              "width":640,
              "height":696}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b111fa1fc2bb440abd235bbf2d7336bf",
              "label":"数字",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3ef49b273de447f88be4b2049b7d9812",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":630}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8309c620fd04b74b55b5f8a4398281e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":630}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u15.png"}},
{
                  "id":"9777d2afe3994d999ddc844def922d65",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"left",
                    "lineSpacing":"72px",
                    "location":{
                      "x":25,
                      "y":20},
                    "size":{
                      "width":585,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c446da1279104e1b8b612350f4af6970",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"left",
                        "lineSpacing":"72px",
                        "location":{
                          "x":25,
                          "y":20},
                        "size":{
                          "width":585,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cb334b85a3fd4995990fad596f4b64cb",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":0,
                      "y":606},
                    "size":{
                      "width":640,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35db4bee19f745fca7d161d2fdad95b0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":0,
                          "y":606},
                        "size":{
                          "width":640,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u19.png"}},
{
                  "id":"638ba12753ed4b6db71b7da1d2aff2a2",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"72px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":92,
                      "y":246},
                    "size":{
                      "width":450,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8a3008214bb45c9be83274e40e025d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"72px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":92,
                          "y":246},
                        "size":{
                          "width":450,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u21.png"}},
{
                  "id":"1538fe780faa4d579ff8d2eaa10cb28d",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "horizontalAlignment":"right",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF009900,
                      "opacity":1},
                    "location":{
                      "x":422,
                      "y":369},
                    "size":{
                      "width":120,
                      "height":55}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0e30c400c6b4f54818ffc3be34df8f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "horizontalAlignment":"right",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF009900,
                          "opacity":1},
                        "location":{
                          "x":422,
                          "y":369},
                        "size":{
                          "width":120,
                          "height":55}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"ef2be9163073470aa51136a5c66fd234",
              "label":"手势",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"92df0dc47a334d62bb21a3775896e2ad",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":640,
                      "height":630}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe638491ee684bc9929e5ce6f418ac7c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":640,
                          "height":630}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u15.png"}},
{
                  "id":"1e24af0ad31f4d5783652d6ab640fcfe",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":146,
                      "y":202},
                    "size":{
                      "width":348,
                      "height":318}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f5e4e33b5914c27ba0c68bb08caee18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":146,
                          "y":202},
                        "size":{
                          "width":348,
                          "height":318}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u27.png"}},
{
                  "id":"b114b76ba5b4443383694cb5b01e15ec",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "horizontalAlignment":"left",
                    "lineSpacing":"72px",
                    "location":{
                      "x":25,
                      "y":20},
                    "size":{
                      "width":595,
                      "height":102}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c3cdab5c87b4a1691c42f8f89d7721d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "horizontalAlignment":"left",
                        "lineSpacing":"72px",
                        "location":{
                          "x":25,
                          "y":20},
                        "size":{
                          "width":595,
                          "height":102}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"52546e67936c4725bf4daec272ae8299",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":320,
                      "y":606},
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a55f3b40d404f8f95eac3ecddc5e6ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":320,
                          "y":606},
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u31.png"}},
{
                  "id":"b700183f353a429494cfe5790d55d155",
                  "label":"",
                  "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":0,
                      "y":606},
                    "size":{
                      "width":320,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d79bf1085ca4883aaf02ee44da696ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"edf7b22d30a14ee5b59784f8a09e11ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":0,
                          "y":606},
                        "size":{
                          "width":320,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/开始签到/u31.png"}}]}]},
{
          "id":"d4616b02843540188067070b4eddc6a5",
          "label":"选中3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":136,
              "y":375},
            "size":{
              "width":110,
              "height":108},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"faef28d6e77d4585b03c74b7b9d02c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":136,
                  "y":375},
                "size":{
                  "width":110,
                  "height":108},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/选中3_u35.png"}},
{
          "id":"d8f66d2f80c14b3db76089d300d759e4",
          "label":"选中2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009900,
              "opacity":1},
            "location":{
              "x":480,
              "y":375},
            "size":{
              "width":110,
              "height":108},
            "visible":false,
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe8465d5604f4f8098c94f13d4b06f37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009900,
                  "opacity":1},
                "location":{
                  "x":480,
                  "y":375},
                "size":{
                  "width":110,
                  "height":108},
                "visible":false,
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/选中3_u35.png"}},
{
          "id":"58ad20491d9d41ae9d401e2f2172a51a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":379},
            "size":{
              "width":80,
              "height":94}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d79a380ae744f1e9e6a7ff1433ef4a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":379},
                "size":{
                  "width":80,
                  "height":94}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u39.png"}},
{
          "id":"7391bfc1702244f58af6ad104924e50f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":387},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80c2b4d28f7f4f1798ac8a2614bcae3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":387},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"a77058e8da0a4da49fbb740d90efb178",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":387},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"907d256a2df94ce9af42edcf381aeaf5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":387},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"4bdd21e2019d48e0b1c96c74524920a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":387},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"826be2a3d62b43f0bb1cb7cce3f16f72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":387},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"e234a0e1775c4fbf835d3efa6d1f0c57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":417},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5677e9a1d8b484fbfe42b15879e0197",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":417},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"96194826aa274158b8ff9ef5c431aa56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":417},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e6b2463834a4c6fb77e7f86dd09ae04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":417},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"8367c0833e204d3f82d8fec820a5e5de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":417},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f07970c275db4d7ea9c8f153ac79b657",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":417},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"1158077e9c154d13a7994522a7832f68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":447},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9416f6039c054efbad36a170a0754463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":447},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"f2132ae3b9864646bdf6235ab1460ee8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":528,
              "y":447},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"215803da56194cec8c4f3d9b2ac98125",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":528,
                  "y":447},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"d241bc7694e24f48a6e761a4f18ed5af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":556,
              "y":447},
            "size":{
              "width":19,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e59b2746c104d72bdfc0e1177eab28a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":556,
                  "y":447},
                "size":{
                  "width":19,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开始签到/u41.png"}},
{
          "id":"f6563c97d52e47a1942d0570b6e3dec3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":480,
              "y":483},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad09c609162d4516a856854cc2e67dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":480,
                  "y":483},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58961b6e034b45939604a85e07b8f7e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":130,
              "y":483},
            "size":{
              "width":120,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19ecf05f8a3b4f64b7bd0ae54f19213e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":130,
                  "y":483},
                "size":{
                  "width":120,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"959938a5d03b4d2dbc24814b174731f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":375},
            "size":{
              "width":110,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b5cb022990e4e78949735f847626287",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":375},
                "size":{
                  "width":110,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 选中2,<br>隐藏 选中3",
                      "objectsToFades":[{
                          "objectPath":["d4616b02843540188067070b4eddc6a5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d8f66d2f80c14b3db76089d300d759e4"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 签到动态面板 to 手势",
                      "panelsToStates":[{
                          "panelPath":["edf7b22d30a14ee5b59784f8a09e11ae"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"993fb345e8f040c5a149948699b0b743",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":375},
            "size":{
              "width":110,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b75298e391d4bdea79b64c47e4f9a4c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":375},
                "size":{
                  "width":110,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 选中3,<br>隐藏 选中2",
                      "objectsToFades":[{
                          "objectPath":["d4616b02843540188067070b4eddc6a5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["d8f66d2f80c14b3db76089d300d759e4"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"setPanelState",
                      "description":"设置 签到动态面板 to 数字",
                      "panelsToStates":[{
                          "panelPath":["edf7b22d30a14ee5b59784f8a09e11ae"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "affc5082ac684dec9a6e87c662159662":{
      "scriptId":"u0"},
    "e5e34b50ef0f483f9d0aa433dece0a5c":{
      "scriptId":"u1"},
    "0093871864cd4ecf8c46748b531966ac":{
      "scriptId":"u2"},
    "e754f99b8b96448e87927056cc757359":{
      "scriptId":"u3"},
    "bce844c745854c9294acd3ab5be14d46":{
      "scriptId":"u4"},
    "1d7fe060a6fb4b68959e5fde7911eec3":{
      "scriptId":"u5"},
    "bb6ccb145eb7406ebc45a808bd6488a7":{
      "scriptId":"u6"},
    "19d12ee40c58432ab90738d5d4609289":{
      "scriptId":"u7"},
    "11c96b8a14b24d608e320eea0b8901a2":{
      "scriptId":"u8"},
    "d5a1a7fa42334470b372adfac9d7c92f":{
      "scriptId":"u9"},
    "206530e8ded24c12854d67b3a1f2ed54":{
      "scriptId":"u10"},
    "eb0a7d2284054c7b803c88cb99a25af0":{
      "scriptId":"u11"},
    "4278200148214beb89a96e1f04db2bbb":{
      "scriptId":"u12"},
    "eb8c48df5f484e5888a8f0e90910d976":{
      "scriptId":"u13"},
    "edf7b22d30a14ee5b59784f8a09e11ae":{
      "scriptId":"u14"},
    "3ef49b273de447f88be4b2049b7d9812":{
      "scriptId":"u15"},
    "e8309c620fd04b74b55b5f8a4398281e":{
      "scriptId":"u16"},
    "9777d2afe3994d999ddc844def922d65":{
      "scriptId":"u17"},
    "c446da1279104e1b8b612350f4af6970":{
      "scriptId":"u18"},
    "cb334b85a3fd4995990fad596f4b64cb":{
      "scriptId":"u19"},
    "35db4bee19f745fca7d161d2fdad95b0":{
      "scriptId":"u20"},
    "638ba12753ed4b6db71b7da1d2aff2a2":{
      "scriptId":"u21"},
    "a8a3008214bb45c9be83274e40e025d4":{
      "scriptId":"u22"},
    "1538fe780faa4d579ff8d2eaa10cb28d":{
      "scriptId":"u23"},
    "a0e30c400c6b4f54818ffc3be34df8f8":{
      "scriptId":"u24"},
    "92df0dc47a334d62bb21a3775896e2ad":{
      "scriptId":"u25"},
    "fe638491ee684bc9929e5ce6f418ac7c":{
      "scriptId":"u26"},
    "1e24af0ad31f4d5783652d6ab640fcfe":{
      "scriptId":"u27"},
    "0f5e4e33b5914c27ba0c68bb08caee18":{
      "scriptId":"u28"},
    "b114b76ba5b4443383694cb5b01e15ec":{
      "scriptId":"u29"},
    "2c3cdab5c87b4a1691c42f8f89d7721d":{
      "scriptId":"u30"},
    "52546e67936c4725bf4daec272ae8299":{
      "scriptId":"u31"},
    "5a55f3b40d404f8f95eac3ecddc5e6ba":{
      "scriptId":"u32"},
    "b700183f353a429494cfe5790d55d155":{
      "scriptId":"u33"},
    "5d79bf1085ca4883aaf02ee44da696ea":{
      "scriptId":"u34"},
    "d4616b02843540188067070b4eddc6a5":{
      "scriptId":"u35"},
    "faef28d6e77d4585b03c74b7b9d02c9d":{
      "scriptId":"u36"},
    "d8f66d2f80c14b3db76089d300d759e4":{
      "scriptId":"u37"},
    "fe8465d5604f4f8098c94f13d4b06f37":{
      "scriptId":"u38"},
    "58ad20491d9d41ae9d401e2f2172a51a":{
      "scriptId":"u39"},
    "0d79a380ae744f1e9e6a7ff1433ef4a0":{
      "scriptId":"u40"},
    "7391bfc1702244f58af6ad104924e50f":{
      "scriptId":"u41"},
    "80c2b4d28f7f4f1798ac8a2614bcae3c":{
      "scriptId":"u42"},
    "a77058e8da0a4da49fbb740d90efb178":{
      "scriptId":"u43"},
    "907d256a2df94ce9af42edcf381aeaf5":{
      "scriptId":"u44"},
    "4bdd21e2019d48e0b1c96c74524920a9":{
      "scriptId":"u45"},
    "826be2a3d62b43f0bb1cb7cce3f16f72":{
      "scriptId":"u46"},
    "e234a0e1775c4fbf835d3efa6d1f0c57":{
      "scriptId":"u47"},
    "e5677e9a1d8b484fbfe42b15879e0197":{
      "scriptId":"u48"},
    "96194826aa274158b8ff9ef5c431aa56":{
      "scriptId":"u49"},
    "6e6b2463834a4c6fb77e7f86dd09ae04":{
      "scriptId":"u50"},
    "8367c0833e204d3f82d8fec820a5e5de":{
      "scriptId":"u51"},
    "f07970c275db4d7ea9c8f153ac79b657":{
      "scriptId":"u52"},
    "1158077e9c154d13a7994522a7832f68":{
      "scriptId":"u53"},
    "9416f6039c054efbad36a170a0754463":{
      "scriptId":"u54"},
    "f2132ae3b9864646bdf6235ab1460ee8":{
      "scriptId":"u55"},
    "215803da56194cec8c4f3d9b2ac98125":{
      "scriptId":"u56"},
    "d241bc7694e24f48a6e761a4f18ed5af":{
      "scriptId":"u57"},
    "1e59b2746c104d72bdfc0e1177eab28a":{
      "scriptId":"u58"},
    "f6563c97d52e47a1942d0570b6e3dec3":{
      "scriptId":"u59"},
    "ad09c609162d4516a856854cc2e67dae":{
      "scriptId":"u60"},
    "58961b6e034b45939604a85e07b8f7e1":{
      "scriptId":"u61"},
    "19ecf05f8a3b4f64b7bd0ae54f19213e":{
      "scriptId":"u62"},
    "959938a5d03b4d2dbc24814b174731f8":{
      "scriptId":"u63"},
    "6b5cb022990e4e78949735f847626287":{
      "scriptId":"u64"},
    "993fb345e8f040c5a149948699b0b743":{
      "scriptId":"u65"},
    "6b75298e391d4bdea79b64c47e4f9a4c":{
      "scriptId":"u66"}}});