$axure.loadCurrentPage({
  "url":"打分.html",
  "generationDate":new Date(1515736333178),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"381166e9ee63473e96221e857c160310",
    "type":"Axure:Page",
    "name":"打分",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9de7a37adf1c407692a40abcd9370cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":90,
              "y":156},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6ae2d057e5c40e382bed3159b380034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":90,
                  "y":156},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u68.png"}},
{
          "id":"553c476b4ca74db3a36147d568076db7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":90,
              "y":66},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe20f777d3ec46a28bbfd600975628a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":90,
                  "y":66},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"140222019ff941cbb3c81244396fd9cb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":88},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39644890c8a24c3989061f42d9b657b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":88},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交作业",
                      "target":{
                        "targetType":"page",
                        "url":"交作业.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"701d126da8a94c0cb839690cec3745c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":90,
              "y":26},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23fb11da7a1f4ba9899f8b17d184d526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":90,
                  "y":26},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"ff48ab63bf554258a44f073af89b7be4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":91,
              "y":156},
            "size":{
              "width":748,
              "height":1204},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb760d4abe6c4eaa8b0538e1bc77d4ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":91,
                  "y":156},
                "size":{
                  "width":748,
                  "height":1204},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u8.png"}},
{
          "id":"858cead9bb2d4c798f287625f67a26e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":106,
              "y":465},
            "size":{
              "width":704,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b36e7b4155148908bb271823628b90e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":106,
                  "y":465},
                "size":{
                  "width":704,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db0db03ad00043269b5e8c95138af817",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":826},
            "size":{
              "width":138,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e765b2adbce41fc99f63d71ac380cb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":826},
                "size":{
                  "width":138,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u12.png"}},
{
          "id":"7049f4de92b846109e1857692c1abf1e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":1016},
            "size":{
              "width":241,
              "height":75},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0d5779b2f7e490189c729bc1f6226b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":1016},
                "size":{
                  "width":241,
                  "height":75},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u14.png"}},
{
          "id":"ddd941dd110d43e0825b249cf1fec68a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":826},
            "size":{
              "width":138,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4d6686087ef4af4b94f6b35ad40a88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":826},
                "size":{
                  "width":138,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u12.png"}},
{
          "id":"c78ad4e4d7374916a3c938e5b294df4d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":826},
            "size":{
              "width":138,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea5f8f074254562b3e5b15d8e17931e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":826},
                "size":{
                  "width":138,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u12.png"}},
{
          "id":"91ce7b7a47bd4e34a927ba8ee6bdcdbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":140,
              "y":194},
            "size":{
              "width":90,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b77cb843b39b4530ab02c568e73e15ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":140,
                  "y":194},
                "size":{
                  "width":90,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"013da519215d490a9b39d97117d6fe81",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":240,
              "y":200},
            "size":{
              "width":160,
              "height":45}},
          "adaptiveStyles":{
},
          "placeholderText":"0-5"},
{
          "id":"f9f1cd98e024488392b78f5e23eb3c46",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":460,
              "y":197},
            "size":{
              "width":56,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"157247774b1546208d606f14b3a0013d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":197},
                "size":{
                  "width":56,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u23.png"}},
{
          "id":"ae67695d3835400fb6e93567cd617898",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":90,
              "y":268},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"17b600346b6249b895cf6ac60fc1eb6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":567,
              "y":193},
            "size":{
              "width":155,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cef6e0bf08184ded810a81a17cf341e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":567,
                  "y":193},
                "size":{
                  "width":155,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u26.png"}},
{
          "id":"041118d2a030432d91e7393aaca47919",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":217},
            "size":{
              "width":110,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/交作业/u12_line.png"}},
{
          "id":"226c27bb5fce44efb3b74e65eb93d8c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":890,
              "y":168},
            "size":{
              "width":660,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693faaf6315e4f529bb93240964b9a5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":890,
                  "y":168},
                "size":{
                  "width":660,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9de7a37adf1c407692a40abcd9370cf1":{
      "scriptId":"u0"},
    "e6ae2d057e5c40e382bed3159b380034":{
      "scriptId":"u1"},
    "553c476b4ca74db3a36147d568076db7":{
      "scriptId":"u2"},
    "fe20f777d3ec46a28bbfd600975628a4":{
      "scriptId":"u3"},
    "140222019ff941cbb3c81244396fd9cb":{
      "scriptId":"u4"},
    "39644890c8a24c3989061f42d9b657b4":{
      "scriptId":"u5"},
    "701d126da8a94c0cb839690cec3745c8":{
      "scriptId":"u6"},
    "23fb11da7a1f4ba9899f8b17d184d526":{
      "scriptId":"u7"},
    "ff48ab63bf554258a44f073af89b7be4":{
      "scriptId":"u8"},
    "eb760d4abe6c4eaa8b0538e1bc77d4ce":{
      "scriptId":"u9"},
    "858cead9bb2d4c798f287625f67a26e4":{
      "scriptId":"u10"},
    "8b36e7b4155148908bb271823628b90e":{
      "scriptId":"u11"},
    "db0db03ad00043269b5e8c95138af817":{
      "scriptId":"u12"},
    "9e765b2adbce41fc99f63d71ac380cb6":{
      "scriptId":"u13"},
    "7049f4de92b846109e1857692c1abf1e":{
      "scriptId":"u14"},
    "b0d5779b2f7e490189c729bc1f6226b8":{
      "scriptId":"u15"},
    "ddd941dd110d43e0825b249cf1fec68a":{
      "scriptId":"u16"},
    "f4d6686087ef4af4b94f6b35ad40a88d":{
      "scriptId":"u17"},
    "c78ad4e4d7374916a3c938e5b294df4d":{
      "scriptId":"u18"},
    "fea5f8f074254562b3e5b15d8e17931e":{
      "scriptId":"u19"},
    "91ce7b7a47bd4e34a927ba8ee6bdcdbe":{
      "scriptId":"u20"},
    "b77cb843b39b4530ab02c568e73e15ae":{
      "scriptId":"u21"},
    "013da519215d490a9b39d97117d6fe81":{
      "scriptId":"u22"},
    "f9f1cd98e024488392b78f5e23eb3c46":{
      "scriptId":"u23"},
    "157247774b1546208d606f14b3a0013d":{
      "scriptId":"u24"},
    "ae67695d3835400fb6e93567cd617898":{
      "scriptId":"u25"},
    "17b600346b6249b895cf6ac60fc1eb6a":{
      "scriptId":"u26"},
    "cef6e0bf08184ded810a81a17cf341e8":{
      "scriptId":"u27"},
    "041118d2a030432d91e7393aaca47919":{
      "scriptId":"u28"},
    "226c27bb5fce44efb3b74e65eb93d8c2":{
      "scriptId":"u29"},
    "693faaf6315e4f529bb93240964b9a5d":{
      "scriptId":"u30"}}});