$axure.loadCurrentPage({
  "url":"晨训任务_1.html",
  "generationDate":new Date(1515736336460),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"37629da1f42345a8afd7886f7f03ca5d",
    "type":"Axure:Page",
    "name":"晨训任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"03a3a3f3796643af96719cd3d0c16c62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24dc5d7c86a44950a2a6f46fa6532aeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":60},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"3845ca89da834e6aa113180ebc009169",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5541348e42e4fa2a6aa5335cb4583de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":60},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"c12c0c43c38745aa84b4d771ab5894c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64f8a5be06974be982f14e0d1cdc7873",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":100},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"23b32c7b9c464468a0fc5114cff464ac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":121},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b119fa4928974066b45afd165b75f4e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":121},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择任务",
                      "target":{
                        "targetType":"page",
                        "url":"选择任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"2a9994beb9474042a266e3893767af06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":110,
              "y":204},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9902c65e16a4e869aabc4027033fa28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":110,
                  "y":204},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"05e38b9329b149c6a711b1b611717402",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":110,
              "y":324},
            "size":{
              "width":680,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2c1346b142a4cffa879b208fa489c28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":110,
                  "y":324},
                "size":{
                  "width":680,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c217d67381b4b408d6dd299750d6feb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":80,
              "y":539},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"e5ad43372d564cf0831133ab49b949c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":283},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a02fb508745648dfa92d404b9978ca03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":283},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"ce8404f080b747559d2a37f02d83402c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":440},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4115199f2bc34eb997bb84fc3c391808",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":440},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"899344538ffd4f86855c72a4cdcebd1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":110,
              "y":479},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b515ca6803fe4c3584f0952d305af656",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":110,
                  "y":479},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77f1fc08717a43ceb35481545e90b9d7",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":545},
            "size":{
              "width":746,
              "height":400}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6113b78aa5494b389061825f5842f0a7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a8e93be1eec844d78b6538db95839766",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b2c8853d97e493b95f864920317f4d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"7252ddb0c22f48439ba377b33a611fa6",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"26dd745fc70a46f085dc88b4205509bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"7977c4646c0b4264a12d39583cb266ea",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"027c1f614bf942a29ab96668c5a611fa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"4646021b56d347278b26f3ad4b627e84",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":90},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"87a38244ee7c4e0eb39214517361d501",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":90},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"08fead0248954bf28d375f357f792617",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a62ae1b7d2a4da7b7ab0ed29f2e309a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":240},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"f5d8e055a9e148b8ab50ae282f07e35c",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"125df708dcfd403aa5b048fb3bbde1c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":320},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"88f97b06b60140cdbe43584e2d63c017",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":14},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7c0c99601dd45d8b4edcb8ff8564cc4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":14},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"57bd1d8a3f9f45c5b3bea70f52d8f7c9",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":14},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23f839d6482046e18ffcaab923ca67f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":14},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"06456a0318084e549fa841491b9eaf29",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2b08a882bf1343c98d417fbaa5851364",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":90},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"462d81c0cee34f5c9ed291d616db286b",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":170},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d8b02666d17436ea3606e8b3776e334",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":170},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"99f8d87ea12f4f4f8332ade5cda2327d",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec319255d9d0471380051c9e10f16492",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"131b1226cbe6409989573b5f9065fab3",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":330},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"792ddfe34eba47d58e886cd8eafeea56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":330},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ebf686ee586949469e4b3c00b64c5eda",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":90},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5d81b181535148c89370cbe681cc6a22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":90},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8b8685919d654d09a1b47f9fc4e0c51d",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":170},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ffcaa19eb7d740fa98e7e5f0a01f89ba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":170},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"255bc5f8a9d9444badb644111e2db0b8",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":249.999984741211},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee634c3b23eb406aad341c9e3ab5eb11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":249.999984741211},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e75a9b9db131415f939c6068289c5b8e",
                  "label":"",
                  "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":340},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7b8c7e807f24f3ba86aaff48343489f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"77f1fc08717a43ceb35481545e90b9d7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":340},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"116ab65bfda446e3a72804a1941c455d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":80,
              "y":1324},
            "size":{
              "width":750,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07a4334bd40d48bab0b65f0a3a0ad729",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":80,
                  "y":1324},
                "size":{
                  "width":750,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u26.png"}},
{
          "id":"b9f3a831e9c343ad8389a5d7282a33d2",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":1354.5},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9ed525f16ac421aa911d1cff79899f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":1354.5},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"a0d1756b38ae44c591b8a34365b54b0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":930,
              "y":1310},
            "size":{
              "width":774,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ce7c4cf75dd41edb3a2da87f6587cb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":930,
                  "y":1310},
                "size":{
                  "width":774,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "03a3a3f3796643af96719cd3d0c16c62":{
      "scriptId":"u0"},
    "24dc5d7c86a44950a2a6f46fa6532aeb":{
      "scriptId":"u1"},
    "3845ca89da834e6aa113180ebc009169":{
      "scriptId":"u2"},
    "a5541348e42e4fa2a6aa5335cb4583de":{
      "scriptId":"u3"},
    "c12c0c43c38745aa84b4d771ab5894c3":{
      "scriptId":"u4"},
    "64f8a5be06974be982f14e0d1cdc7873":{
      "scriptId":"u5"},
    "23b32c7b9c464468a0fc5114cff464ac":{
      "scriptId":"u6"},
    "b119fa4928974066b45afd165b75f4e5":{
      "scriptId":"u7"},
    "2a9994beb9474042a266e3893767af06":{
      "scriptId":"u8"},
    "e9902c65e16a4e869aabc4027033fa28":{
      "scriptId":"u9"},
    "05e38b9329b149c6a711b1b611717402":{
      "scriptId":"u10"},
    "d2c1346b142a4cffa879b208fa489c28":{
      "scriptId":"u11"},
    "7c217d67381b4b408d6dd299750d6feb":{
      "scriptId":"u12"},
    "e5ad43372d564cf0831133ab49b949c5":{
      "scriptId":"u13"},
    "a02fb508745648dfa92d404b9978ca03":{
      "scriptId":"u14"},
    "ce8404f080b747559d2a37f02d83402c":{
      "scriptId":"u15"},
    "4115199f2bc34eb997bb84fc3c391808":{
      "scriptId":"u16"},
    "899344538ffd4f86855c72a4cdcebd1a":{
      "scriptId":"u17"},
    "b515ca6803fe4c3584f0952d305af656":{
      "scriptId":"u18"},
    "77f1fc08717a43ceb35481545e90b9d7":{
      "scriptId":"u19"},
    "a8e93be1eec844d78b6538db95839766":{
      "scriptId":"u20"},
    "1b2c8853d97e493b95f864920317f4d2":{
      "scriptId":"u21"},
    "7252ddb0c22f48439ba377b33a611fa6":{
      "scriptId":"u22"},
    "26dd745fc70a46f085dc88b4205509bb":{
      "scriptId":"u23"},
    "7977c4646c0b4264a12d39583cb266ea":{
      "scriptId":"u24"},
    "027c1f614bf942a29ab96668c5a611fa":{
      "scriptId":"u25"},
    "4646021b56d347278b26f3ad4b627e84":{
      "scriptId":"u26"},
    "87a38244ee7c4e0eb39214517361d501":{
      "scriptId":"u27"},
    "08fead0248954bf28d375f357f792617":{
      "scriptId":"u28"},
    "7a62ae1b7d2a4da7b7ab0ed29f2e309a":{
      "scriptId":"u29"},
    "f5d8e055a9e148b8ab50ae282f07e35c":{
      "scriptId":"u30"},
    "125df708dcfd403aa5b048fb3bbde1c8":{
      "scriptId":"u31"},
    "88f97b06b60140cdbe43584e2d63c017":{
      "scriptId":"u32"},
    "b7c0c99601dd45d8b4edcb8ff8564cc4":{
      "scriptId":"u33"},
    "57bd1d8a3f9f45c5b3bea70f52d8f7c9":{
      "scriptId":"u34"},
    "23f839d6482046e18ffcaab923ca67f3":{
      "scriptId":"u35"},
    "06456a0318084e549fa841491b9eaf29":{
      "scriptId":"u36"},
    "2b08a882bf1343c98d417fbaa5851364":{
      "scriptId":"u37"},
    "462d81c0cee34f5c9ed291d616db286b":{
      "scriptId":"u38"},
    "0d8b02666d17436ea3606e8b3776e334":{
      "scriptId":"u39"},
    "99f8d87ea12f4f4f8332ade5cda2327d":{
      "scriptId":"u40"},
    "ec319255d9d0471380051c9e10f16492":{
      "scriptId":"u41"},
    "131b1226cbe6409989573b5f9065fab3":{
      "scriptId":"u42"},
    "792ddfe34eba47d58e886cd8eafeea56":{
      "scriptId":"u43"},
    "ebf686ee586949469e4b3c00b64c5eda":{
      "scriptId":"u44"},
    "5d81b181535148c89370cbe681cc6a22":{
      "scriptId":"u45"},
    "8b8685919d654d09a1b47f9fc4e0c51d":{
      "scriptId":"u46"},
    "ffcaa19eb7d740fa98e7e5f0a01f89ba":{
      "scriptId":"u47"},
    "255bc5f8a9d9444badb644111e2db0b8":{
      "scriptId":"u48"},
    "ee634c3b23eb406aad341c9e3ab5eb11":{
      "scriptId":"u49"},
    "e75a9b9db131415f939c6068289c5b8e":{
      "scriptId":"u50"},
    "d7b8c7e807f24f3ba86aaff48343489f":{
      "scriptId":"u51"},
    "116ab65bfda446e3a72804a1941c455d":{
      "scriptId":"u52"},
    "07a4334bd40d48bab0b65f0a3a0ad729":{
      "scriptId":"u53"},
    "b9f3a831e9c343ad8389a5d7282a33d2":{
      "scriptId":"u54"},
    "c9ed525f16ac421aa911d1cff79899f9":{
      "scriptId":"u55"},
    "a0d1756b38ae44c591b8a34365b54b0e":{
      "scriptId":"u56"},
    "4ce7c4cf75dd41edb3a2da87f6587cb4":{
      "scriptId":"u57"}}});