$axure.loadCurrentPage({
  "url":"任务库.html",
  "generationDate":new Date(1515736333949),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6f167f6992224a60ae83a48fa1a57de5",
    "type":"Axure:Page",
    "name":"任务库",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7aacd9dc383b41678c44e71ed3e322b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d5164607ae34540985e9c128d285047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"54f9daea1ab0423397f14480284d78d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f4c4abbcf84b47b1f8dbc7ef15b70b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"7e5a53379d5d43e88c6a134dd7d69daa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"156f30047b5849528fb01fd1178c1448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"c934ed5c39c942c29bcf501c02f47e73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":131},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f12f200a549426b94a19b3e83e24b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":131},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理员、老师",
                      "target":{
                        "targetType":"page",
                        "url":"管理员、老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"f1e80ecdcd0a47119eef7cb49ef70123",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":210},
            "size":{
              "width":244,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c358e7943594b4487af7c95becc0fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":210},
                "size":{
                  "width":244,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69f0307a2e6343dfa1e7275dbe29cdb0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":270},
            "size":{
              "width":554,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8fd801e42d14d9989d97bd157ab559e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":270},
                "size":{
                  "width":554,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"304b3ef7a4594d1ea954f265ff94fc14",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":336},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"78ce242759674fb38cc08f7972317efc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":218},
            "size":{
              "width":108,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb631704972f4568b5ad0f1f3cf38f81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":218},
                "size":{
                  "width":108,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u13.png"}},
{
          "id":"cab45df92c3f42a98c5b65fbfa53a544",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":364},
            "size":{
              "width":234,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fec4c65aea6943f3b9d8efe4fbf6a116",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":364},
                "size":{
                  "width":234,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f84956816924081a7a0d3614290b4ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":424},
            "size":{
              "width":564,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ff099caa9764e9e92bb5dc36b3711d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":424},
                "size":{
                  "width":564,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7132ac68af4d45098de457561a71a595",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":490},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"e0534bf33f764fb2a0d5de8fbced9229",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":372},
            "size":{
              "width":108,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09b79cfb5339429aa613c424eb74dcc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":372},
                "size":{
                  "width":108,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u13.png"}},
{
          "id":"e833b7de202346c5931923b4e3eff6df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":520},
            "size":{
              "width":224,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f04910c093d4e1dae8481df1864cdd7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":520},
                "size":{
                  "width":224,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dfbd90f3de34940a657633922cf139a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":106,
              "y":580},
            "size":{
              "width":574,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b274d09f84a742459de2c98210807fc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":106,
                  "y":580},
                "size":{
                  "width":574,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9bb1953ab5847a1a56fdd8e7ad6ae19",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":646},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"168bc724e4444f43982a48e46b6a95d0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":528},
            "size":{
              "width":108,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d727bacac6d144c0bb4a83a712f549bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":528},
                "size":{
                  "width":108,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u13.png"}},
{
          "id":"c673d93a6da84d3685d38fd977ef741b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":755,
              "y":134},
            "size":{
              "width":45,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b971d42f033473a89225b3b1d986e98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":755,
                  "y":134},
                "size":{
                  "width":45,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建任务",
                      "target":{
                        "targetType":"page",
                        "url":"创建任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务库/u29.png"}},
{
          "id":"475a208e27b549b1adc86e144bad009c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":669},
            "size":{
              "width":224,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4751f54f278b42688e34b50da619a055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":669},
                "size":{
                  "width":224,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3628cdaa27a748cbb93779eab751c7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":106,
              "y":729},
            "size":{
              "width":574,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"156d54f7d88e484f887c62d152a07bcf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":106,
                  "y":729},
                "size":{
                  "width":574,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b5d0b0468c4445aa426e010b3a28834",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":795},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"8788fd84a54744388915f8f2ac8d53cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":692,
              "y":677},
            "size":{
              "width":108,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f7d025617c44f9c9eea63048e4385eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":692,
                  "y":677},
                "size":{
                  "width":108,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u13.png"}},
{
          "id":"72a183737f0d4cb0809960c83c5f9ef1",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":269},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49428e6ece884fa293a3c491bd824cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":269},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"8a36a0803b8b4327959f396cb65b6bb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":936,
              "y":233},
            "size":{
              "width":574,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50d6f7130a27442e931458e6075e763f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":936,
                  "y":233},
                "size":{
                  "width":574,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u40.png"}},
{
          "id":"a5c35c2f296d4ee485c69be3d6567083",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":200},
            "size":{
              "width":750,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6202908a2f94cffa79d43345ea50775",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":200},
                "size":{
                  "width":750,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 晨训任务",
                      "target":{
                        "targetType":"page",
                        "url":"晨训任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eb484503a344fcdbff49bcef938faf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":350},
            "size":{
              "width":750,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4742b18c4c5a4653a90bc9f8bf612cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":350},
                "size":{
                  "width":750,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 阅读任务",
                      "target":{
                        "targetType":"page",
                        "url":"阅读任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"62f94b5a4d7a4c26bc5b7771e6a240ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":500.000030517578},
            "size":{
              "width":750,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb0b1bfff3e7482881b43c57a63624b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":500.000030517578},
                "size":{
                  "width":750,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评分任务",
                      "target":{
                        "targetType":"page",
                        "url":"评分任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1813309075a4b6cabe3363f270aee98",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":424},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36601f07d8184f90896299aca170e10c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":424},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"0410e6d24bfa4aed83dbb20539f6db8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":936,
              "y":388},
            "size":{
              "width":574,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d0beb1e0ee04e8bad374e50ab5ccce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":936,
                  "y":388},
                "size":{
                  "width":574,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u40.png"}},
{
          "id":"72dafaef9c95454bb8730e5468d4f2fb",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":579},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1374e42f4ec48a1a8eb5ec890ed8006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":579},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"f0208939795f47f68dfb318d229e1b89",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":936,
              "y":543},
            "size":{
              "width":574,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ef7b76abe864c48bc9bcfdbc74894ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":936,
                  "y":543},
                "size":{
                  "width":574,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务库/u40.png"}},
{
          "id":"edf0f181d69d41bdbb624ca99c13a358",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":495.000030517578,
              "y":242},
            "size":{
              "width":175,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d239dd5b04e449efb887852f6321f8bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":495.000030517578,
                  "y":242},
                "size":{
                  "width":175,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3fd77e9667654bcc8eeb798be7756754",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":540,
              "y":677},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22db403feb5845bface5a73e2ce09475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":540,
                  "y":677},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"485ceedda643463c95c72abab8a737fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":495,
              "y":385},
            "size":{
              "width":175,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30851b8d3bdb4a9599fd7ff16676e5c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":495,
                  "y":385},
                "size":{
                  "width":175,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7aacd9dc383b41678c44e71ed3e322b7":{
      "scriptId":"u0"},
    "9d5164607ae34540985e9c128d285047":{
      "scriptId":"u1"},
    "54f9daea1ab0423397f14480284d78d7":{
      "scriptId":"u2"},
    "13f4c4abbcf84b47b1f8dbc7ef15b70b":{
      "scriptId":"u3"},
    "7e5a53379d5d43e88c6a134dd7d69daa":{
      "scriptId":"u4"},
    "156f30047b5849528fb01fd1178c1448":{
      "scriptId":"u5"},
    "c934ed5c39c942c29bcf501c02f47e73":{
      "scriptId":"u6"},
    "9f12f200a549426b94a19b3e83e24b81":{
      "scriptId":"u7"},
    "f1e80ecdcd0a47119eef7cb49ef70123":{
      "scriptId":"u8"},
    "2c358e7943594b4487af7c95becc0fa1":{
      "scriptId":"u9"},
    "69f0307a2e6343dfa1e7275dbe29cdb0":{
      "scriptId":"u10"},
    "f8fd801e42d14d9989d97bd157ab559e":{
      "scriptId":"u11"},
    "304b3ef7a4594d1ea954f265ff94fc14":{
      "scriptId":"u12"},
    "78ce242759674fb38cc08f7972317efc":{
      "scriptId":"u13"},
    "cb631704972f4568b5ad0f1f3cf38f81":{
      "scriptId":"u14"},
    "cab45df92c3f42a98c5b65fbfa53a544":{
      "scriptId":"u15"},
    "fec4c65aea6943f3b9d8efe4fbf6a116":{
      "scriptId":"u16"},
    "1f84956816924081a7a0d3614290b4ed":{
      "scriptId":"u17"},
    "2ff099caa9764e9e92bb5dc36b3711d2":{
      "scriptId":"u18"},
    "7132ac68af4d45098de457561a71a595":{
      "scriptId":"u19"},
    "e0534bf33f764fb2a0d5de8fbced9229":{
      "scriptId":"u20"},
    "09b79cfb5339429aa613c424eb74dcc6":{
      "scriptId":"u21"},
    "e833b7de202346c5931923b4e3eff6df":{
      "scriptId":"u22"},
    "9f04910c093d4e1dae8481df1864cdd7":{
      "scriptId":"u23"},
    "9dfbd90f3de34940a657633922cf139a":{
      "scriptId":"u24"},
    "b274d09f84a742459de2c98210807fc1":{
      "scriptId":"u25"},
    "e9bb1953ab5847a1a56fdd8e7ad6ae19":{
      "scriptId":"u26"},
    "168bc724e4444f43982a48e46b6a95d0":{
      "scriptId":"u27"},
    "d727bacac6d144c0bb4a83a712f549bb":{
      "scriptId":"u28"},
    "c673d93a6da84d3685d38fd977ef741b":{
      "scriptId":"u29"},
    "0b971d42f033473a89225b3b1d986e98":{
      "scriptId":"u30"},
    "475a208e27b549b1adc86e144bad009c":{
      "scriptId":"u31"},
    "4751f54f278b42688e34b50da619a055":{
      "scriptId":"u32"},
    "3628cdaa27a748cbb93779eab751c7cd":{
      "scriptId":"u33"},
    "156d54f7d88e484f887c62d152a07bcf":{
      "scriptId":"u34"},
    "6b5d0b0468c4445aa426e010b3a28834":{
      "scriptId":"u35"},
    "8788fd84a54744388915f8f2ac8d53cd":{
      "scriptId":"u36"},
    "6f7d025617c44f9c9eea63048e4385eb":{
      "scriptId":"u37"},
    "72a183737f0d4cb0809960c83c5f9ef1":{
      "scriptId":"u38"},
    "49428e6ece884fa293a3c491bd824cb1":{
      "scriptId":"u39"},
    "8a36a0803b8b4327959f396cb65b6bb9":{
      "scriptId":"u40"},
    "50d6f7130a27442e931458e6075e763f":{
      "scriptId":"u41"},
    "a5c35c2f296d4ee485c69be3d6567083":{
      "scriptId":"u42"},
    "a6202908a2f94cffa79d43345ea50775":{
      "scriptId":"u43"},
    "2eb484503a344fcdbff49bcef938faf7":{
      "scriptId":"u44"},
    "4742b18c4c5a4653a90bc9f8bf612cd9":{
      "scriptId":"u45"},
    "62f94b5a4d7a4c26bc5b7771e6a240ce":{
      "scriptId":"u46"},
    "bb0b1bfff3e7482881b43c57a63624b2":{
      "scriptId":"u47"},
    "a1813309075a4b6cabe3363f270aee98":{
      "scriptId":"u48"},
    "36601f07d8184f90896299aca170e10c":{
      "scriptId":"u49"},
    "0410e6d24bfa4aed83dbb20539f6db8d":{
      "scriptId":"u50"},
    "5d0beb1e0ee04e8bad374e50ab5ccce3":{
      "scriptId":"u51"},
    "72dafaef9c95454bb8730e5468d4f2fb":{
      "scriptId":"u52"},
    "c1374e42f4ec48a1a8eb5ec890ed8006":{
      "scriptId":"u53"},
    "f0208939795f47f68dfb318d229e1b89":{
      "scriptId":"u54"},
    "0ef7b76abe864c48bc9bcfdbc74894ad":{
      "scriptId":"u55"},
    "edf0f181d69d41bdbb624ca99c13a358":{
      "scriptId":"u56"},
    "d239dd5b04e449efb887852f6321f8bb":{
      "scriptId":"u57"},
    "3fd77e9667654bcc8eeb798be7756754":{
      "scriptId":"u58"},
    "22db403feb5845bface5a73e2ce09475":{
      "scriptId":"u59"},
    "485ceedda643463c95c72abab8a737fa":{
      "scriptId":"u60"},
    "30851b8d3bdb4a9599fd7ff16676e5c3":{
      "scriptId":"u61"}}});