$axure.loadCurrentPage({
  "url":"活动详情.html",
  "generationDate":new Date(1515736336601),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"49085ba7a8f140bfab8571847292f3b1",
    "type":"Axure:Page",
    "name":"活动详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"154aa18fc7fd423d9ed5b66f8147b31d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":185},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"649dea3c3a814253a5d4d1205e86ca4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":185},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u198.png"}},
{
          "id":"4a83fea970fa407d971f58383866084d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"30px",
            "location":{
              "x":100,
              "y":96},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eedef6e058354842a170732e2c9baf97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"30px",
                "location":{
                  "x":100,
                  "y":96},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"914f053b350b40d483e63f4c89de87b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":116,
              "y":117},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee467bc2d0cd4fdb9300b64615cebdd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":116,
                  "y":117},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理员、老师",
                      "target":{
                        "targetType":"page",
                        "url":"管理员、老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"882462c880a540ce848d00ecbcc27fed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":100,
              "y":56},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ec8d4b36714e468bc07aae8ed9b324",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":100,
                  "y":56},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"fc138dac675e4d4aa3abe4b83f8214eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":102,
              "y":187},
            "size":{
              "width":746,
              "height":75},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1073ea3c4ab74d638be4b4c304973ba4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":102,
                  "y":187},
                "size":{
                  "width":746,
                  "height":75},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u343.png"}},
{
          "id":"f4d1696560024d30aafb9b7a2cb9854f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA1A1A1,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":117,
              "y":936},
            "size":{
              "width":714,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b37220472084bdeaf0a29bcc554711f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA1A1A1,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":117,
                  "y":936},
                "size":{
                  "width":714,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16a1bcef74cf499b9b495cb1b5b0d224",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":103,
              "y":280},
            "size":{
              "width":746,
              "height":170},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cc9b4b591f846edb53ebfeefc6faae8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":280},
                "size":{
                  "width":746,
                  "height":170},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u12.png"}},
{
          "id":"a0abb19aef1247cabbf4c22db0eea851",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":116,
              "y":300},
            "size":{
              "width":715,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f69eaaec212147be9cc1aa7d3f3c0d53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":116,
                  "y":300},
                "size":{
                  "width":715,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"922f13a4a69d4875b6bd7aebd16914ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":103,
              "y":469},
            "size":{
              "width":746,
              "height":185},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4ff53c46dcd47c7b633eef8196d2972",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":103,
                  "y":469},
                "size":{
                  "width":746,
                  "height":185},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u16.png"}},
{
          "id":"4ed78d6e72404f7099c22c9fc8d70101",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":116,
              "y":496},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9071e2a4d0234926832a7076f0070423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":116,
                  "y":496},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8a424d2a7a80451c82b4da144f098713",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":326,
              "y":496},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d07c5bd03aa49839c40678b7aa2e737",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":326,
                  "y":496},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d85c0d6ec784079b1fffb8ec6564700",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":116,
              "y":566},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e95cc518a047afbd5d31eaeb9a2416",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":116,
                  "y":566},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8646032179ef4ee29ee9ee3d8a0e55e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":546,
              "y":496},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d46b1c0eca74a44b9e699ca00d73c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":546,
                  "y":496},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"433646cb336942fca75422f8fb07682a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":103,
              "y":769},
            "size":{
              "width":746,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b23b8a1ddf104c0da396b3680c70c055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":769},
                "size":{
                  "width":746,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑活动",
                      "target":{
                        "targetType":"page",
                        "url":"编辑活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u382.png"}},
{
          "id":"8703259b61dd4ff0a4410fa8c480eec4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":103,
              "y":859},
            "size":{
              "width":746,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24862d934fea47ba861c5b724728836f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":103,
                  "y":859},
                "size":{
                  "width":746,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u382.png"}},
{
          "id":"1be0fd99df8d4cafbb86c2c60076ddf4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":894},
            "size":{
              "width":99,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/管理员、老师/u390_line.png"}},
{
          "id":"123da1f076bc431c8bcdb381d2bbd990",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":921,
              "y":820},
            "size":{
              "width":630,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"307016f854ce49e295e1398a310eca56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":921,
                  "y":820},
                "size":{
                  "width":630,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u31.png"}},
{
          "id":"5b38d8381e8d490aa3011e2856f81bde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":921,
              "y":971},
            "size":{
              "width":630,
              "height":169}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f713e9f181147429e20a69f716c4234",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":921,
                  "y":971},
                "size":{
                  "width":630,
                  "height":169}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/活动详情/u33.png"}},
{
          "id":"4a2c34d9f9d94dc5bbb40c3b303101ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":921,
              "y":1081},
            "size":{
              "width":315,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7965da39547497aab28f5f266e5368c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":921,
                  "y":1081},
                "size":{
                  "width":315,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建育人活动/u42.png"}},
{
          "id":"2d32ccc9cf664eceb361d857d742c86f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":1235,
              "y":1081},
            "size":{
              "width":315,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c5aec809c6e4081840709eedde9f02f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":1235,
                  "y":1081},
                "size":{
                  "width":315,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建育人活动/u44.png"}},
{
          "id":"45c711743161410da277f0067034408e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":939,
              "y":988},
            "size":{
              "width":592,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"320bf901c5214ac0a8013f5990aa025d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":939,
                  "y":988},
                "size":{
                  "width":592,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c37fb05f8ad441eaa8f92cb0f3c9232",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":101,
              "y":679},
            "size":{
              "width":746,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"266885dc90144fc8bed1754dd07c4bf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":101,
                  "y":679},
                "size":{
                  "width":746,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 编辑活动",
                      "target":{
                        "targetType":"page",
                        "url":"编辑活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u382.png"}},
{
          "id":"aa9769f5df3f41df878493bb55c4720f",
          "label":"未选",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":692.5},
            "size":{
              "width":41,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81a15d5714e34316a21f30d8b3d8e98e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":692.5},
                "size":{
                  "width":41,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 已选,<br>隐藏 未选",
                      "objectsToFades":[{
                          "objectPath":["aa9769f5df3f41df878493bb55c4720f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4fe6c08fed2142d8b72d23ddb8a30eeb"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/活动详情/未选_u43.png"}},
{
          "id":"4fe6c08fed2142d8b72d23ddb8a30eeb",
          "label":"已选",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":764,
              "y":691},
            "size":{
              "width":50,
              "height":46},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"640b64e8fa1c4d71bd740527cc10dc00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":764,
                  "y":691},
                "size":{
                  "width":50,
                  "height":46},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 未选,<br>隐藏 已选",
                      "objectsToFades":[{
                          "objectPath":["aa9769f5df3f41df878493bb55c4720f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["4fe6c08fed2142d8b72d23ddb8a30eeb"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/活动详情/已选_u45.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "154aa18fc7fd423d9ed5b66f8147b31d":{
      "scriptId":"u0"},
    "649dea3c3a814253a5d4d1205e86ca4d":{
      "scriptId":"u1"},
    "4a83fea970fa407d971f58383866084d":{
      "scriptId":"u2"},
    "eedef6e058354842a170732e2c9baf97":{
      "scriptId":"u3"},
    "914f053b350b40d483e63f4c89de87b7":{
      "scriptId":"u4"},
    "ee467bc2d0cd4fdb9300b64615cebdd9":{
      "scriptId":"u5"},
    "882462c880a540ce848d00ecbcc27fed":{
      "scriptId":"u6"},
    "73ec8d4b36714e468bc07aae8ed9b324":{
      "scriptId":"u7"},
    "fc138dac675e4d4aa3abe4b83f8214eb":{
      "scriptId":"u8"},
    "1073ea3c4ab74d638be4b4c304973ba4":{
      "scriptId":"u9"},
    "f4d1696560024d30aafb9b7a2cb9854f":{
      "scriptId":"u10"},
    "6b37220472084bdeaf0a29bcc554711f":{
      "scriptId":"u11"},
    "16a1bcef74cf499b9b495cb1b5b0d224":{
      "scriptId":"u12"},
    "0cc9b4b591f846edb53ebfeefc6faae8":{
      "scriptId":"u13"},
    "a0abb19aef1247cabbf4c22db0eea851":{
      "scriptId":"u14"},
    "f69eaaec212147be9cc1aa7d3f3c0d53":{
      "scriptId":"u15"},
    "922f13a4a69d4875b6bd7aebd16914ae":{
      "scriptId":"u16"},
    "d4ff53c46dcd47c7b633eef8196d2972":{
      "scriptId":"u17"},
    "4ed78d6e72404f7099c22c9fc8d70101":{
      "scriptId":"u18"},
    "9071e2a4d0234926832a7076f0070423":{
      "scriptId":"u19"},
    "8a424d2a7a80451c82b4da144f098713":{
      "scriptId":"u20"},
    "4d07c5bd03aa49839c40678b7aa2e737":{
      "scriptId":"u21"},
    "5d85c0d6ec784079b1fffb8ec6564700":{
      "scriptId":"u22"},
    "48e95cc518a047afbd5d31eaeb9a2416":{
      "scriptId":"u23"},
    "8646032179ef4ee29ee9ee3d8a0e55e9":{
      "scriptId":"u24"},
    "9d46b1c0eca74a44b9e699ca00d73c52":{
      "scriptId":"u25"},
    "433646cb336942fca75422f8fb07682a":{
      "scriptId":"u26"},
    "b23b8a1ddf104c0da396b3680c70c055":{
      "scriptId":"u27"},
    "8703259b61dd4ff0a4410fa8c480eec4":{
      "scriptId":"u28"},
    "24862d934fea47ba861c5b724728836f":{
      "scriptId":"u29"},
    "1be0fd99df8d4cafbb86c2c60076ddf4":{
      "scriptId":"u30"},
    "123da1f076bc431c8bcdb381d2bbd990":{
      "scriptId":"u31"},
    "307016f854ce49e295e1398a310eca56":{
      "scriptId":"u32"},
    "5b38d8381e8d490aa3011e2856f81bde":{
      "scriptId":"u33"},
    "1f713e9f181147429e20a69f716c4234":{
      "scriptId":"u34"},
    "4a2c34d9f9d94dc5bbb40c3b303101ae":{
      "scriptId":"u35"},
    "e7965da39547497aab28f5f266e5368c":{
      "scriptId":"u36"},
    "2d32ccc9cf664eceb361d857d742c86f":{
      "scriptId":"u37"},
    "8c5aec809c6e4081840709eedde9f02f":{
      "scriptId":"u38"},
    "45c711743161410da277f0067034408e":{
      "scriptId":"u39"},
    "320bf901c5214ac0a8013f5990aa025d":{
      "scriptId":"u40"},
    "0c37fb05f8ad441eaa8f92cb0f3c9232":{
      "scriptId":"u41"},
    "266885dc90144fc8bed1754dd07c4bf2":{
      "scriptId":"u42"},
    "aa9769f5df3f41df878493bb55c4720f":{
      "scriptId":"u43"},
    "81a15d5714e34316a21f30d8b3d8e98e":{
      "scriptId":"u44"},
    "4fe6c08fed2142d8b72d23ddb8a30eeb":{
      "scriptId":"u45"},
    "640b64e8fa1c4d71bd740527cc10dc00":{
      "scriptId":"u46"}}});