$axure.loadCurrentPage({
  "url":"打分_1.html",
  "generationDate":new Date(1515736338543),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d790b742c8834610bd8eb5b84f8c1883",
    "type":"Axure:Page",
    "name":"打分",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6a256fade9c64ac9b29acf84b3b65426",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":140,
              "y":170},
            "size":{
              "width":750,
              "height":1204}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"acb78965831e4084a7712e72fe1ffd68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":140,
                  "y":170},
                "size":{
                  "width":750,
                  "height":1204}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u68.png"}},
{
          "id":"956bec083e7f479593861de70b565b42",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":140,
              "y":80},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0328c7c128b147138e2fa785acbf3510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":140,
                  "y":80},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"185675d0d81a4d98ba0b1da7340b3ba0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":102},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ec532ecea9a4937b2b7f93c52572548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":102},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"e382e2b6f626408788fb5dca9d77992a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":140,
              "y":40},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0819ec381c7f4bf9aa3cc2aacd4386a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":140,
                  "y":40},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"42e282a3b0b840e7ad12738468a0ec26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":170},
            "size":{
              "width":748,
              "height":1200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29bf271aa8604e0a9dadffacc2fb122c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":170},
                "size":{
                  "width":748,
                  "height":1200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分_1/u8.png"}},
{
          "id":"86cb87301c004294b9ff68080f099a6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":166,
              "y":479},
            "size":{
              "width":704,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b209629b41254165bd299ae0053fc601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":166,
                  "y":479},
                "size":{
                  "width":704,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b197e2bba8c487f925e70fe05cdc586",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":840},
            "size":{
              "width":138,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7004969147d41caa961ed2a9c0a88f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":840},
                "size":{
                  "width":138,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u12.png"}},
{
          "id":"e3a93a1dc9264a9b8271ddcfc9487b55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":1030},
            "size":{
              "width":241,
              "height":75},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0792da0a4db54a9485d4c7101f197a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":1030},
                "size":{
                  "width":241,
                  "height":75},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u14.png"}},
{
          "id":"41169027a0f94bbf864c62dae5fdacd1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":840},
            "size":{
              "width":138,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"718c25c8dfd6478a81370d928cecc82a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":840},
                "size":{
                  "width":138,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u12.png"}},
{
          "id":"10f0089652184f74b29e7fae9eafae31",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":320,
              "y":840},
            "size":{
              "width":138,
              "height":143},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07f26670be364fceb89f86be745fc0be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":320,
                  "y":840},
                "size":{
                  "width":138,
                  "height":143},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u12.png"}},
{
          "id":"8725c5efccb644438d1bff1e63cb4135",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":166,
              "y":210},
            "size":{
              "width":155,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49cf712643274489ad445ed140919ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":166,
                  "y":210},
                "size":{
                  "width":155,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"35fe745155a74c0a8e5b89f201406c7e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":307,
              "y":214},
            "size":{
              "width":117,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"c057ae786bd643d189632a9557bf8d9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":424,
              "y":211},
            "size":{
              "width":56,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a7d73ffbcbd4e159836daa940407ae5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":424,
                  "y":211},
                "size":{
                  "width":56,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u23.png"}},
{
          "id":"2d127d15d49d4298b0c5ae262be7d880",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":140,
              "y":282},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"50b383584ed647e7bf057a0daf8fb8ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9900},
            "location":{
              "x":525,
              "y":210},
            "size":{
              "width":155,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4aff67111fb34b24bd166270a8dd9999",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9900},
                "location":{
                  "x":525,
                  "y":210},
                "size":{
                  "width":155,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u26.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a256fade9c64ac9b29acf84b3b65426":{
      "scriptId":"u0"},
    "acb78965831e4084a7712e72fe1ffd68":{
      "scriptId":"u1"},
    "956bec083e7f479593861de70b565b42":{
      "scriptId":"u2"},
    "0328c7c128b147138e2fa785acbf3510":{
      "scriptId":"u3"},
    "185675d0d81a4d98ba0b1da7340b3ba0":{
      "scriptId":"u4"},
    "9ec532ecea9a4937b2b7f93c52572548":{
      "scriptId":"u5"},
    "e382e2b6f626408788fb5dca9d77992a":{
      "scriptId":"u6"},
    "0819ec381c7f4bf9aa3cc2aacd4386a3":{
      "scriptId":"u7"},
    "42e282a3b0b840e7ad12738468a0ec26":{
      "scriptId":"u8"},
    "29bf271aa8604e0a9dadffacc2fb122c":{
      "scriptId":"u9"},
    "86cb87301c004294b9ff68080f099a6d":{
      "scriptId":"u10"},
    "b209629b41254165bd299ae0053fc601":{
      "scriptId":"u11"},
    "9b197e2bba8c487f925e70fe05cdc586":{
      "scriptId":"u12"},
    "d7004969147d41caa961ed2a9c0a88f4":{
      "scriptId":"u13"},
    "e3a93a1dc9264a9b8271ddcfc9487b55":{
      "scriptId":"u14"},
    "0792da0a4db54a9485d4c7101f197a15":{
      "scriptId":"u15"},
    "41169027a0f94bbf864c62dae5fdacd1":{
      "scriptId":"u16"},
    "718c25c8dfd6478a81370d928cecc82a":{
      "scriptId":"u17"},
    "10f0089652184f74b29e7fae9eafae31":{
      "scriptId":"u18"},
    "07f26670be364fceb89f86be745fc0be":{
      "scriptId":"u19"},
    "8725c5efccb644438d1bff1e63cb4135":{
      "scriptId":"u20"},
    "49cf712643274489ad445ed140919ed2":{
      "scriptId":"u21"},
    "35fe745155a74c0a8e5b89f201406c7e":{
      "scriptId":"u22"},
    "c057ae786bd643d189632a9557bf8d9b":{
      "scriptId":"u23"},
    "1a7d73ffbcbd4e159836daa940407ae5":{
      "scriptId":"u24"},
    "2d127d15d49d4298b0c5ae262be7d880":{
      "scriptId":"u25"},
    "50b383584ed647e7bf057a0daf8fb8ff":{
      "scriptId":"u26"},
    "4aff67111fb34b24bd166270a8dd9999":{
      "scriptId":"u27"}}});