$axure.loadCurrentPage({
  "url":"晨训任务.html",
  "generationDate":new Date(1515736334744),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e17bf873633a43418ff7f3a89cd94b2e",
    "type":"Axure:Page",
    "name":"晨训任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8499ae55228c431ebcaeb9988837eb5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51797cc80ba0459da7e62d617576d1df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":60},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"73c1b8ff6f8e48a0adfe0ac9a41cdfc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":60},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f06628f3f5ba4c9d8404eae2ec83ffb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":60},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"7aac969641774e0b937efb7d242193c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":100},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"902cd3b50e1949fab1fb895296ec4838",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":100},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"041cd372a617467ba0ae48cc9f54813b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":121},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2b31d8d08f94b2f83bda77016f1533b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":121},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务库",
                      "target":{
                        "targetType":"page",
                        "url":"任务库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"53e1fb1f6c66484f968ee58ac9f96736",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":110,
              "y":204},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7e9ddfb1f43421dadada9874b51d1d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":110,
                  "y":204},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"559abaf665a54260b3ff9e3f1bbc6dad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":110,
              "y":324},
            "size":{
              "width":680,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bfd0533cd1c44bc993fe791e326954a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":110,
                  "y":324},
                "size":{
                  "width":680,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"64161935293b467596140e2f086bb7fc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":80,
              "y":539},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"30d16f9c4bb4460388b4102abfeea686",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":283},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae1a266bb347478b8c096b0759e67437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":283},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"e8ed501d61c1401dac33b7449bc1ae60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":440},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c56f1a5a864a4081a52fa11304be6307",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":440},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"3d13431524034f35aa986aa04a9aca97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":110,
              "y":479},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d31deeca05104fab9b1db5a12ace802f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":110,
                  "y":479},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7393abb262e4bc781808eb4d1600979",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":545},
            "size":{
              "width":746,
              "height":400}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1f57c62541594ec9a861cd99b4d86593",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f83b15c978ef42a1b922d01abd365d87",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba00e1a012754f439c81ead9eaa1285d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"5a67a2b82b3d4dbdbc704e3b79a053eb",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e7512b79b5914c1e9ccb45f01201b1a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"8c23efad3a5d427c98019ea97c0fba5d",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"024053fc16674930b11476fff68ba0ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"743bf0f336e549d9b29cbcd426d3260c",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":90},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e2a601d503948749ca93d124eda4729",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":90},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c05e084c0f7347e2ae80dcfa85302040",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8b428df77fed40e0aaab350e0289eed7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":240},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"9af2cd6863b24664b0be729e2e893ec0",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00e18c03c6b1442eb67bd392a1e6f1bc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":320},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"e88489e36d084542918d7b11cfb488e2",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":14},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02ccdd650244409e907a456fdb8184eb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":14},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c20f71dbd2c4f87b4261d2cbb094f38",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":14},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df0eb9771f19464a94b5f11480ac9342",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":14},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2f12a980f31e40f989e14740491bd379",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96ca7ace31614aca90b2cd2927b4a268",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":90},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f58388e8d30400ba51878cc7311a361",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":170},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"716494b1985d4882ad49e97a08b30619",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":170},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"70bc3871b49b496eba14e65b169e9d00",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35b58e57aaae4dcc89884582e5bb2dfa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1d300eb5f3664f90b60471048273d2a0",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":330},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c3a6abfc040141a089679912815feceb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":330},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bc3eef06acab4cce86771486b24fa3ad",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":90},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbb60d4dc90c4658b6eea942e8a9dcfe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":90},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3d53e9a9b1cc4cbc8ab93077fe955543",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":170},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4fb903f4eb67471686156021752c7628",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":170},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5c6740dc55554a2dbe7194fe76d5b624",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":249.999984741211},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4bf65d80def4ef39d895cd7a7ff521a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":249.999984741211},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"562b009d95c84d8a99e6a5a582c69033",
                  "label":"",
                  "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":400,
                      "y":340},
                    "size":{
                      "width":60,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"389b754262ad414a9417ad68f1cee483",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7393abb262e4bc781808eb4d1600979",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":400,
                          "y":340},
                        "size":{
                          "width":60,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"a70a3f86370f4682a469565a2b7a6953",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":82,
              "y":982},
            "size":{
              "width":746,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3aee171285d443d8f2351db7fbb51f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":982},
                "size":{
                  "width":746,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u382.png"}},
{
          "id":"11f990a0b93046ae932d3c811870189b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":82,
              "y":1086},
            "size":{
              "width":746,
              "height":87},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60509fdf81b1444f8b8e713e615429f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":82,
                  "y":1086},
                "size":{
                  "width":746,
                  "height":87},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u54.png"}},
{
          "id":"95a962cf02d2496a8471820b3128e018",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":946},
            "size":{
              "width":746,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba320a1d81a402689d5cc34f273786a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":946},
                "size":{
                  "width":746,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u56.png"}},
{
          "id":"60b20c446b86481682066a7fa07ef064",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":1053},
            "size":{
              "width":746,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f018ea80aa2743d18ee6a06c7638f85f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":1053},
                "size":{
                  "width":746,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u56.png"}},
{
          "id":"f48cc4b3e21b4f5ea6683ae574978231",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":82,
              "y":1173},
            "size":{
              "width":746,
              "height":217},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5916dc2f16014c8596f7462de996bda9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":82,
                  "y":1173},
                "size":{
                  "width":746,
                  "height":217},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u60.png"}},
{
          "id":"8082d778ae1e4a849ef626dadaeb85bb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":862,
              "y":650},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"e398a536e8d6445ba81d2331f1b3016b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1070,
              "y":60},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"695afab4d6784e92a1114b8bed608364",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1070,
                  "y":60},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"bf5d478daea1497aa63f52c8acc7a76a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1070,
              "y":60},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"498db7fc52554ac5bbb3b9a2aed00615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1070,
                  "y":60},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"a804271300fb41478c12173e59d6cc11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":1070,
              "y":100},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0fbe7dee234ea9b7b6bd009f133033",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":1070,
                  "y":100},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"e7d4c2df2636477d9e0055caef7a13f0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1086,
              "y":121},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac748d7cc684a33ad5f73f95759c57c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1086,
                  "y":121},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"cc6e2b07c28b4b50b205f2d5f4b3bb9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1100,
              "y":204},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b437674c8e94d9cba7eb32329696411",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1100,
                  "y":204},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cc8cf0c6d90418b8f654ad2f94e1392",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":1229,
              "y":211},
            "size":{
              "width":410,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"c67c9eb3119f42de9ad9d27738c5697c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":1617,
              "y":204},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d8f25a6e21d416c9770f084531ffbe8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":1617,
                  "y":204},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"374483e6b03e4033948577aadea468f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1100,
              "y":323},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f35b66c4c6684d4c8512b784041dfa09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1100,
                  "y":323},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88e9d6a56d62459184719dc3a4a11b85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1530,
              "y":323},
            "size":{
              "width":235,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5b3befbb319422bb4677aba1d20a48f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1530,
                  "y":323},
                "size":{
                  "width":235,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务内容",
                      "target":{
                        "targetType":"page",
                        "url":"任务内容.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af68c1144e854d179a96e5077d4f21d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":1070,
              "y":1324},
            "size":{
              "width":750,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12429d98d5484dc598593b2e66ab23f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":1070,
                  "y":1324},
                "size":{
                  "width":750,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u26.png"}},
{
          "id":"c7277972b3ed4b0394be953739cef16f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1072,
              "y":283},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf974ea2afe4b13a4e86ba9a349d0f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1072,
                  "y":283},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"c7054ddf5913482f855f05368e06c1bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1072,
              "y":392},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b156e047c324daeba8d0f9a0c1a9264",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1072,
                  "y":392},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"1d0b88e3a23d4eb19790f7d2cffc2738",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1072,
              "y":574},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"54d7f35d50134b7b8678ae6d067d044f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1102,
              "y":514},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd69f6d1bbf6444d80f54a07796f1c93",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1102,
                  "y":514},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e89299538944aaba8e1c7e9c76722a2",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1072,
              "y":580},
            "size":{
              "width":746,
              "height":400}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"2ede4b8f4a854d9d99ef589870dc1fd6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b135fb5b8df7405fb42d65629a643d9f",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"850d3ef3c10c458a908c685a14ae5c97",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"54407c8fb9f94c308817ac15b5c972e1",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c2d20c4dd7604aabb67eca366297f69c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"99ad22a1eb0847aab827e58e2ef39f24",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1985f45409e14f7cbb978cc4c8852158",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"2dd50ca278284e90b7cb4f6999ac0a3e",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":90},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f88d97dcebd46ef9bfcb43b0c2b72f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":90},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1db98676a0d2438c884603008ff9614b",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"438cce54269a4dde9e6628f5d7655693",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":240},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"6e0b181bd0b3416c938d4eb85b65078c",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"480736fc452844719886fb2747fbb4c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":320},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"a04c491dc9e14c8d9dacd8e569adf29a",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":14},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c4b73ca47b34586b9cfef8f50c32f11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":14},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"32ce3a88c5e34363a9a04831a4d0c145",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":360,
                      "y":22},
                    "size":{
                      "width":120,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"da39d6aa6bfb46cca0b8d6b2be12bd7a",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":14},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ebe52487db34ba89b0e783e47c752e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":490,
                          "y":14},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8dc4423cf854477bbea0ac870b9e3630",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":360,
                      "y":102},
                    "size":{
                      "width":120,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"3a204d62d70e4341b5ee1752ab9cc35b",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":94},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb151a63bd0f4f758acd029e6e2d2de8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":490,
                          "y":94},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"41eb927a824a407e9ec1dbfe0aca8595",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":90},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa6ae357a94f4c18874ec9b4aba46e0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":90},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4c6c2d6b727a49faae2a1145b968df16",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":170},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41d048bf37004d0690d48bce9778f540",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":170},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3e13f76e389745768fbfa8ddbfc6f987",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":250},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bba05262a8cc4cd69b4db06683239ec1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":250},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d69d31cc95c54202a2f7edacb6c465ad",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":330},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30d9df0ea68f4c3a89c2e59d7c9622e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":330},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4030a2e1fbf14ba5aa322fa5ee4425f2",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":360,
                      "y":178},
                    "size":{
                      "width":120,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"1543f8be1c9d4ecebd6f195a550c25bb",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":170},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f3ef2d7d25f485c92c9bba19a3520ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":490,
                          "y":170},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd3357ee7fa943f89d85413bc1e9731c",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":360,
                      "y":258},
                    "size":{
                      "width":120,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"fd200063b073476abe53a6c2383974c7",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":250},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5f6d175a80384e5abaf3489255d3e7ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":490,
                          "y":250},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"96ef50a0e7804e3ca49997af7aaf0c13",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":360,
                      "y":338},
                    "size":{
                      "width":120,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"1fa74d4587b849c5b9ff45c1bba96473",
                  "label":"",
                  "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":490,
                      "y":330},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"525a55d8f15e415992b987c63381954a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e89299538944aaba8e1c7e9c76722a2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":490,
                          "y":330},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"ab3c68adb8714a4a8c634b44d6618256",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1102,
              "y":430},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c88b0ab1e0fb45989a94ef9e28b02446",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1102,
                  "y":430},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"935a20e42907402ea7f473d0c48f4574",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1072,
              "y":494},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8499ae55228c431ebcaeb9988837eb5f":{
      "scriptId":"u0"},
    "51797cc80ba0459da7e62d617576d1df":{
      "scriptId":"u1"},
    "73c1b8ff6f8e48a0adfe0ac9a41cdfc3":{
      "scriptId":"u2"},
    "f06628f3f5ba4c9d8404eae2ec83ffb1":{
      "scriptId":"u3"},
    "7aac969641774e0b937efb7d242193c8":{
      "scriptId":"u4"},
    "902cd3b50e1949fab1fb895296ec4838":{
      "scriptId":"u5"},
    "041cd372a617467ba0ae48cc9f54813b":{
      "scriptId":"u6"},
    "e2b31d8d08f94b2f83bda77016f1533b":{
      "scriptId":"u7"},
    "53e1fb1f6c66484f968ee58ac9f96736":{
      "scriptId":"u8"},
    "a7e9ddfb1f43421dadada9874b51d1d4":{
      "scriptId":"u9"},
    "559abaf665a54260b3ff9e3f1bbc6dad":{
      "scriptId":"u10"},
    "2bfd0533cd1c44bc993fe791e326954a":{
      "scriptId":"u11"},
    "64161935293b467596140e2f086bb7fc":{
      "scriptId":"u12"},
    "30d16f9c4bb4460388b4102abfeea686":{
      "scriptId":"u13"},
    "ae1a266bb347478b8c096b0759e67437":{
      "scriptId":"u14"},
    "e8ed501d61c1401dac33b7449bc1ae60":{
      "scriptId":"u15"},
    "c56f1a5a864a4081a52fa11304be6307":{
      "scriptId":"u16"},
    "3d13431524034f35aa986aa04a9aca97":{
      "scriptId":"u17"},
    "d31deeca05104fab9b1db5a12ace802f":{
      "scriptId":"u18"},
    "f7393abb262e4bc781808eb4d1600979":{
      "scriptId":"u19"},
    "f83b15c978ef42a1b922d01abd365d87":{
      "scriptId":"u20"},
    "ba00e1a012754f439c81ead9eaa1285d":{
      "scriptId":"u21"},
    "5a67a2b82b3d4dbdbc704e3b79a053eb":{
      "scriptId":"u22"},
    "e7512b79b5914c1e9ccb45f01201b1a3":{
      "scriptId":"u23"},
    "8c23efad3a5d427c98019ea97c0fba5d":{
      "scriptId":"u24"},
    "024053fc16674930b11476fff68ba0ee":{
      "scriptId":"u25"},
    "743bf0f336e549d9b29cbcd426d3260c":{
      "scriptId":"u26"},
    "7e2a601d503948749ca93d124eda4729":{
      "scriptId":"u27"},
    "c05e084c0f7347e2ae80dcfa85302040":{
      "scriptId":"u28"},
    "8b428df77fed40e0aaab350e0289eed7":{
      "scriptId":"u29"},
    "9af2cd6863b24664b0be729e2e893ec0":{
      "scriptId":"u30"},
    "00e18c03c6b1442eb67bd392a1e6f1bc":{
      "scriptId":"u31"},
    "e88489e36d084542918d7b11cfb488e2":{
      "scriptId":"u32"},
    "02ccdd650244409e907a456fdb8184eb":{
      "scriptId":"u33"},
    "0c20f71dbd2c4f87b4261d2cbb094f38":{
      "scriptId":"u34"},
    "df0eb9771f19464a94b5f11480ac9342":{
      "scriptId":"u35"},
    "2f12a980f31e40f989e14740491bd379":{
      "scriptId":"u36"},
    "96ca7ace31614aca90b2cd2927b4a268":{
      "scriptId":"u37"},
    "3f58388e8d30400ba51878cc7311a361":{
      "scriptId":"u38"},
    "716494b1985d4882ad49e97a08b30619":{
      "scriptId":"u39"},
    "70bc3871b49b496eba14e65b169e9d00":{
      "scriptId":"u40"},
    "35b58e57aaae4dcc89884582e5bb2dfa":{
      "scriptId":"u41"},
    "1d300eb5f3664f90b60471048273d2a0":{
      "scriptId":"u42"},
    "c3a6abfc040141a089679912815feceb":{
      "scriptId":"u43"},
    "bc3eef06acab4cce86771486b24fa3ad":{
      "scriptId":"u44"},
    "fbb60d4dc90c4658b6eea942e8a9dcfe":{
      "scriptId":"u45"},
    "3d53e9a9b1cc4cbc8ab93077fe955543":{
      "scriptId":"u46"},
    "4fb903f4eb67471686156021752c7628":{
      "scriptId":"u47"},
    "5c6740dc55554a2dbe7194fe76d5b624":{
      "scriptId":"u48"},
    "c4bf65d80def4ef39d895cd7a7ff521a":{
      "scriptId":"u49"},
    "562b009d95c84d8a99e6a5a582c69033":{
      "scriptId":"u50"},
    "389b754262ad414a9417ad68f1cee483":{
      "scriptId":"u51"},
    "a70a3f86370f4682a469565a2b7a6953":{
      "scriptId":"u52"},
    "c3aee171285d443d8f2351db7fbb51f0":{
      "scriptId":"u53"},
    "11f990a0b93046ae932d3c811870189b":{
      "scriptId":"u54"},
    "60509fdf81b1444f8b8e713e615429f5":{
      "scriptId":"u55"},
    "95a962cf02d2496a8471820b3128e018":{
      "scriptId":"u56"},
    "6ba320a1d81a402689d5cc34f273786a":{
      "scriptId":"u57"},
    "60b20c446b86481682066a7fa07ef064":{
      "scriptId":"u58"},
    "f018ea80aa2743d18ee6a06c7638f85f":{
      "scriptId":"u59"},
    "f48cc4b3e21b4f5ea6683ae574978231":{
      "scriptId":"u60"},
    "5916dc2f16014c8596f7462de996bda9":{
      "scriptId":"u61"},
    "8082d778ae1e4a849ef626dadaeb85bb":{
      "scriptId":"u62"},
    "e398a536e8d6445ba81d2331f1b3016b":{
      "scriptId":"u63"},
    "695afab4d6784e92a1114b8bed608364":{
      "scriptId":"u64"},
    "bf5d478daea1497aa63f52c8acc7a76a":{
      "scriptId":"u65"},
    "498db7fc52554ac5bbb3b9a2aed00615":{
      "scriptId":"u66"},
    "a804271300fb41478c12173e59d6cc11":{
      "scriptId":"u67"},
    "ef0fbe7dee234ea9b7b6bd009f133033":{
      "scriptId":"u68"},
    "e7d4c2df2636477d9e0055caef7a13f0":{
      "scriptId":"u69"},
    "5ac748d7cc684a33ad5f73f95759c57c":{
      "scriptId":"u70"},
    "cc6e2b07c28b4b50b205f2d5f4b3bb9b":{
      "scriptId":"u71"},
    "6b437674c8e94d9cba7eb32329696411":{
      "scriptId":"u72"},
    "6cc8cf0c6d90418b8f654ad2f94e1392":{
      "scriptId":"u73"},
    "c67c9eb3119f42de9ad9d27738c5697c":{
      "scriptId":"u74"},
    "1d8f25a6e21d416c9770f084531ffbe8":{
      "scriptId":"u75"},
    "374483e6b03e4033948577aadea468f6":{
      "scriptId":"u76"},
    "f35b66c4c6684d4c8512b784041dfa09":{
      "scriptId":"u77"},
    "88e9d6a56d62459184719dc3a4a11b85":{
      "scriptId":"u78"},
    "a5b3befbb319422bb4677aba1d20a48f":{
      "scriptId":"u79"},
    "af68c1144e854d179a96e5077d4f21d9":{
      "scriptId":"u80"},
    "12429d98d5484dc598593b2e66ab23f4":{
      "scriptId":"u81"},
    "c7277972b3ed4b0394be953739cef16f":{
      "scriptId":"u82"},
    "bdf974ea2afe4b13a4e86ba9a349d0f5":{
      "scriptId":"u83"},
    "c7054ddf5913482f855f05368e06c1bf":{
      "scriptId":"u84"},
    "0b156e047c324daeba8d0f9a0c1a9264":{
      "scriptId":"u85"},
    "1d0b88e3a23d4eb19790f7d2cffc2738":{
      "scriptId":"u86"},
    "54d7f35d50134b7b8678ae6d067d044f":{
      "scriptId":"u87"},
    "fd69f6d1bbf6444d80f54a07796f1c93":{
      "scriptId":"u88"},
    "1e89299538944aaba8e1c7e9c76722a2":{
      "scriptId":"u89"},
    "b135fb5b8df7405fb42d65629a643d9f":{
      "scriptId":"u90"},
    "850d3ef3c10c458a908c685a14ae5c97":{
      "scriptId":"u91"},
    "54407c8fb9f94c308817ac15b5c972e1":{
      "scriptId":"u92"},
    "c2d20c4dd7604aabb67eca366297f69c":{
      "scriptId":"u93"},
    "99ad22a1eb0847aab827e58e2ef39f24":{
      "scriptId":"u94"},
    "1985f45409e14f7cbb978cc4c8852158":{
      "scriptId":"u95"},
    "2dd50ca278284e90b7cb4f6999ac0a3e":{
      "scriptId":"u96"},
    "1f88d97dcebd46ef9bfcb43b0c2b72f8":{
      "scriptId":"u97"},
    "1db98676a0d2438c884603008ff9614b":{
      "scriptId":"u98"},
    "438cce54269a4dde9e6628f5d7655693":{
      "scriptId":"u99"},
    "6e0b181bd0b3416c938d4eb85b65078c":{
      "scriptId":"u100"},
    "480736fc452844719886fb2747fbb4c6":{
      "scriptId":"u101"},
    "a04c491dc9e14c8d9dacd8e569adf29a":{
      "scriptId":"u102"},
    "1c4b73ca47b34586b9cfef8f50c32f11":{
      "scriptId":"u103"},
    "32ce3a88c5e34363a9a04831a4d0c145":{
      "scriptId":"u104"},
    "da39d6aa6bfb46cca0b8d6b2be12bd7a":{
      "scriptId":"u105"},
    "4ebe52487db34ba89b0e783e47c752e4":{
      "scriptId":"u106"},
    "8dc4423cf854477bbea0ac870b9e3630":{
      "scriptId":"u107"},
    "3a204d62d70e4341b5ee1752ab9cc35b":{
      "scriptId":"u108"},
    "eb151a63bd0f4f758acd029e6e2d2de8":{
      "scriptId":"u109"},
    "41eb927a824a407e9ec1dbfe0aca8595":{
      "scriptId":"u110"},
    "fa6ae357a94f4c18874ec9b4aba46e0a":{
      "scriptId":"u111"},
    "4c6c2d6b727a49faae2a1145b968df16":{
      "scriptId":"u112"},
    "41d048bf37004d0690d48bce9778f540":{
      "scriptId":"u113"},
    "3e13f76e389745768fbfa8ddbfc6f987":{
      "scriptId":"u114"},
    "bba05262a8cc4cd69b4db06683239ec1":{
      "scriptId":"u115"},
    "d69d31cc95c54202a2f7edacb6c465ad":{
      "scriptId":"u116"},
    "30d9df0ea68f4c3a89c2e59d7c9622e4":{
      "scriptId":"u117"},
    "4030a2e1fbf14ba5aa322fa5ee4425f2":{
      "scriptId":"u118"},
    "1543f8be1c9d4ecebd6f195a550c25bb":{
      "scriptId":"u119"},
    "5f3ef2d7d25f485c92c9bba19a3520ec":{
      "scriptId":"u120"},
    "bd3357ee7fa943f89d85413bc1e9731c":{
      "scriptId":"u121"},
    "fd200063b073476abe53a6c2383974c7":{
      "scriptId":"u122"},
    "5f6d175a80384e5abaf3489255d3e7ee":{
      "scriptId":"u123"},
    "96ef50a0e7804e3ca49997af7aaf0c13":{
      "scriptId":"u124"},
    "1fa74d4587b849c5b9ff45c1bba96473":{
      "scriptId":"u125"},
    "525a55d8f15e415992b987c63381954a":{
      "scriptId":"u126"},
    "ab3c68adb8714a4a8c634b44d6618256":{
      "scriptId":"u127"},
    "c88b0ab1e0fb45989a94ef9e28b02446":{
      "scriptId":"u128"},
    "935a20e42907402ea7f473d0c48f4574":{
      "scriptId":"u129"}}});