$axure.loadCurrentPage({
  "url":"任务名称1.html",
  "generationDate":new Date(1515736332210),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"554404ad50c34a14b70b5a4408163204",
    "type":"Axure:Page",
    "name":"任务名称1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16d16187fd5f4362904dffcbbe256836",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":70},
            "size":{
              "width":750,
              "height":1294}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6543f58c55a415f965ad05337c87a48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":70},
                "size":{
                  "width":750,
                  "height":1294}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u0.png"}},
{
          "id":"8bb7585792c1488aa23e170ae8eaf49c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":110,
              "y":70},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd38292a306049548bb1e274be693e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":110,
                  "y":70},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"675ec37362054005be13055636593b78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":90},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"350d162267774088967f25fd32cf28e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":90},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的事项",
                      "target":{
                        "targetType":"page",
                        "url":"我的事项.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"abaf0a045f9046aea78e29a5178402dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":110,
              "y":30},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f0184eafaf4668ba02d5ea5f43954c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":110,
                  "y":30},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"87fdb43cafec4bcdaa5f2e92d6155f69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209.5,
              "y":437},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"937cf2542c794fba85c461489b91212b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209.5,
                  "y":437},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 考勤",
                      "target":{
                        "targetType":"page",
                        "url":"考勤.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"a266bf38944149979d4e8dbc2f309145",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":200,
              "y":615},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8992f270dad4975a0e5a0198a2c71ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":200,
                  "y":615},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4525ac56601d43c7ba3cc878b0d4f3d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":609.5,
              "y":437},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eca3ec61143c4619be2f984f7ae96232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":609.5,
                  "y":437},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交作业",
                      "target":{
                        "targetType":"page",
                        "url":"交作业.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"0378e59df5fc4f27a3e7cf8a41248122",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":600,
              "y":615},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70aa6264720241328f79ebd568386047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":600,
                  "y":615},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cc0ba4c773241a280ae57fb783c1bca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "lineSpacing":"48px",
            "location":{
              "x":129,
              "y":175},
            "size":{
              "width":661,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d2af3677a8d4a619803adb9ec930b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "lineSpacing":"48px",
                "location":{
                  "x":129,
                  "y":175},
                "size":{
                  "width":661,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务详情",
                      "target":{
                        "targetType":"page",
                        "url":"任务详情.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db1b200b96324475964c3951e85901fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":209.5,
              "y":737},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e7ab9c8470a426a8ddeff0137706904",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":209.5,
                  "y":737},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 老师打分",
                      "target":{
                        "targetType":"page",
                        "url":"老师打分.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"51c15186f65044159afaa01b2eb80a24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":200,
              "y":915},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a107c7b947c8477887770c85b3652491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":200,
                  "y":915},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ea41906fe0644aba26ddc71906f36a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF19AEB7,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":1080,
              "y":601.5},
            "size":{
              "width":650,
              "height":231}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cfab8d5868543e7b92a83eb1568da5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF19AEB7,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":1080,
                  "y":601.5},
                "size":{
                  "width":650,
                  "height":231}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u22.png"}},
{
          "id":"ff779408ca8946d2a5c6931b2afaaacf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":683,
              "y":80},
            "size":{
              "width":171,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4283cf64f5744ead88f99118e4d41e8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":683,
                  "y":80},
                "size":{
                  "width":171,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 小组加分",
                      "target":{
                        "targetType":"page",
                        "url":"小组加分.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"61193e99c9e34561a6f169a1e7ffb023",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":109,
              "y":345},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"85a50f3a02db443cb3b0826561865f27",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":890,
              "y":407},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77e24ad72d6745dc82429023ed3b4639",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":890,
                  "y":407},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"eacb271d13df476f822117f5e163c105",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":800,
              "y":238},
            "size":{
              "width":31,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bffebdfa92349139302390164a9dd51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":800,
                  "y":238},
                "size":{
                  "width":31,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u29.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "16d16187fd5f4362904dffcbbe256836":{
      "scriptId":"u0"},
    "e6543f58c55a415f965ad05337c87a48":{
      "scriptId":"u1"},
    "8bb7585792c1488aa23e170ae8eaf49c":{
      "scriptId":"u2"},
    "fd38292a306049548bb1e274be693e31":{
      "scriptId":"u3"},
    "675ec37362054005be13055636593b78":{
      "scriptId":"u4"},
    "350d162267774088967f25fd32cf28e4":{
      "scriptId":"u5"},
    "abaf0a045f9046aea78e29a5178402dc":{
      "scriptId":"u6"},
    "a3f0184eafaf4668ba02d5ea5f43954c":{
      "scriptId":"u7"},
    "87fdb43cafec4bcdaa5f2e92d6155f69":{
      "scriptId":"u8"},
    "937cf2542c794fba85c461489b91212b":{
      "scriptId":"u9"},
    "a266bf38944149979d4e8dbc2f309145":{
      "scriptId":"u10"},
    "a8992f270dad4975a0e5a0198a2c71ff":{
      "scriptId":"u11"},
    "4525ac56601d43c7ba3cc878b0d4f3d7":{
      "scriptId":"u12"},
    "eca3ec61143c4619be2f984f7ae96232":{
      "scriptId":"u13"},
    "0378e59df5fc4f27a3e7cf8a41248122":{
      "scriptId":"u14"},
    "70aa6264720241328f79ebd568386047":{
      "scriptId":"u15"},
    "5cc0ba4c773241a280ae57fb783c1bca":{
      "scriptId":"u16"},
    "5d2af3677a8d4a619803adb9ec930b2d":{
      "scriptId":"u17"},
    "db1b200b96324475964c3951e85901fd":{
      "scriptId":"u18"},
    "2e7ab9c8470a426a8ddeff0137706904":{
      "scriptId":"u19"},
    "51c15186f65044159afaa01b2eb80a24":{
      "scriptId":"u20"},
    "a107c7b947c8477887770c85b3652491":{
      "scriptId":"u21"},
    "0ea41906fe0644aba26ddc71906f36a3":{
      "scriptId":"u22"},
    "3cfab8d5868543e7b92a83eb1568da5f":{
      "scriptId":"u23"},
    "ff779408ca8946d2a5c6931b2afaaacf":{
      "scriptId":"u24"},
    "4283cf64f5744ead88f99118e4d41e8c":{
      "scriptId":"u25"},
    "61193e99c9e34561a6f169a1e7ffb023":{
      "scriptId":"u26"},
    "85a50f3a02db443cb3b0826561865f27":{
      "scriptId":"u27"},
    "77e24ad72d6745dc82429023ed3b4639":{
      "scriptId":"u28"},
    "eacb271d13df476f822117f5e163c105":{
      "scriptId":"u29"},
    "4bffebdfa92349139302390164a9dd51":{
      "scriptId":"u30"}}});