$axure.loadCurrentPage({
  "url":"组长评分.html",
  "generationDate":new Date(1515736339038),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e40eb1121b7844ab9dd46f698bb08e49",
    "type":"Axure:Page",
    "name":"组长评分",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d541d87e9241462eadfdbf726f39ee92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":30},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f48739aa81bf40f9b89f88347a41409a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":30},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"0ebf14b9b99643078b5cbcecb2111cde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":120,
              "y":70},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac5f71e141454439952f476efa5a5414",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":120,
                  "y":70},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"bc8681cac915466ca6e6f04376208739",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":91},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf712a94a9d346a6b5bb8471f04d3b2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":91},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"d556ed0ada2745e3aa2048d754aca0ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":120,
              "y":30},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae472692801a489e86dcacbea24b745b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":120,
                  "y":30},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"e36fd866d0a14988b35278e040a44310",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":120,
              "y":160},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f00690b2a9e84cb4ab4684e29acfd344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":160},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f42120688a7c40049609285f4378f2eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":120,
              "y":1291},
            "size":{
              "width":750,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45a739666f8c4e5c863f773d938ff53b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":120,
                  "y":1291},
                "size":{
                  "width":750,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u10.png"}},
{
          "id":"35b955b8aceb40e8bdf62ccc30984895",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":123,
              "y":250},
            "size":{
              "width":744,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cc46d46ae27492cb731d5f7e01f564a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":123,
                  "y":250},
                "size":{
                  "width":744,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u12.png"}},
{
          "id":"3bd23bdc50af44a785e84284b48e3fa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":166,
              "y":272},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d39848fa33bd4982a927e8ad94cb6345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":166,
                  "y":272},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"a72cf86bc1d0408cbc37af5984a92e62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":362,
              "y":272},
            "size":{
              "width":199,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d263e9a9dda84ece9bde5b5ed25bd03e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":362,
                  "y":272},
                "size":{
                  "width":199,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a03f61c70e634793a3c00453d39f313a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":236,
              "y":270},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1399dedf82451284bb9970925a4bd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":236,
                  "y":270},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d55bf093726449db30b7f332629017e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":630,
              "y":275},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"3c9e61fc377a420ab4ed2dc276d9261e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":730,
              "y":272},
            "size":{
              "width":56,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d58bb46fb7af4215a297cc31e657bf43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":730,
                  "y":272},
                "size":{
                  "width":56,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u23.png"}},
{
          "id":"a732d913b8154ce192e5014136419a6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1270,
              "y":30},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da557f09591241f299b8f33ac4ec2448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1270,
                  "y":30},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"d07e375efd584a03a2a9fc9d0517b97a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":1270,
              "y":70},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce110986aa3d4e13a8c6f012ec2bbeee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":1270,
                  "y":70},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"95ff507e692340399e3486e900d36cb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1286,
              "y":91},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee388bdee264d63a7b3401271fe1e3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1286,
                  "y":91},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"063f9b0533b4467d9efbc291bddbef54",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1270,
              "y":30},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31bad77b439d454496df3f1c36b8fe8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1270,
                  "y":30},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"6619d30c278f467b8dfa579a78821e84",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC,
              "opacity":1},
            "location":{
              "x":1270,
              "y":160},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3703bf2d6a7746a28291489efdf207a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFBCBCBC,
                  "opacity":1},
                "location":{
                  "x":1270,
                  "y":160},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"837e5874b0454c3ebc46bb54e0c5acfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":1270,
              "y":1291},
            "size":{
              "width":750,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a64df9484674d84b21737d64d091dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":1270,
                  "y":1291},
                "size":{
                  "width":750,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u10.png"}},
{
          "id":"f249b6a03b2143489c5903b4a8d64862",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1272,
              "y":250},
            "size":{
              "width":745,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5755861c4aa44f37a35edf8c8eabb6ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1272,
                  "y":250},
                "size":{
                  "width":745,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u35.png"}},
{
          "id":"7e9ad3afaee040aa91058700b419c472",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1316,
              "y":272},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8fbaf49c28c41999d4956c7adff6976",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1316,
                  "y":272},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"fb23966a28c14ac18ef70d9b8f874557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":1512,
              "y":272},
            "size":{
              "width":199,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc412f80b51f4602b7a842beb0f392e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1512,
                  "y":272},
                "size":{
                  "width":199,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9f548f8925af48b984460302d68ba5f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":1386,
              "y":270},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a4204983da427c95497da4bdef9523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1386,
                  "y":270},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a43792989a84484cac1b7b29653e1871",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":1780,
              "y":275},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"1761b9b3ae3b47c480f2a3cf85cdaadc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1990,
              "y":1322},
            "size":{
              "width":100,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/老师打分/u44_line.png"}},
{
          "id":"4a479975157f4a65ad50b938166d69bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "location":{
              "x":2090,
              "y":1245},
            "size":{
              "width":590,
              "height":164}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e484947e4bd41bb8a9ed643f51a110b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "location":{
                  "x":2090,
                  "y":1245},
                "size":{
                  "width":590,
                  "height":164}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u45.png"}},
{
          "id":"13d1927f7ca64e7285df8f598bf9987b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":2090,
              "y":1431},
            "size":{
              "width":500,
              "height":159}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d60ddceaed44d758e58d45cee6b89c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2090,
                  "y":1431},
                "size":{
                  "width":500,
                  "height":159}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u47.png"}},
{
          "id":"e9f88104d3904481a4f0ba754c6e2d52",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":2090,
              "y":1525},
            "size":{
              "width":500,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/老师打分/u49_line.png"}},
{
          "id":"0db6bd6760e94c7f8aae6352a350a5fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":2108,
              "y":1450},
            "size":{
              "width":464,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f91271a8b73d4ba08f98942b81976750",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":2108,
                  "y":1450},
                "size":{
                  "width":464,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab82ca048ff04f688541bf13d5e09661",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":2090,
              "y":1530},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73782311e5ca439ea592530a38a33b3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":2090,
                  "y":1530},
                "size":{
                  "width":250,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u52.png"}},
{
          "id":"8529cb4cdd6b47d58302ace4a2f2a09f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "fill":{
              "fillType":"solid",
              "color":0xFF00CC66},
            "location":{
              "x":2340,
              "y":1530},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f2c7838a6984debb64daba8009dcec1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CC66},
                "location":{
                  "x":2340,
                  "y":1530},
                "size":{
                  "width":250,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u54.png"}},
{
          "id":"fc8db2b56dab4b0ba3e3e90ec7072373",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":365},
            "size":{
              "width":744,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be5a567233794df7b01e0255651f26db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":365},
                "size":{
                  "width":744,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u12.png"}},
{
          "id":"5c5f509db46949ab88fd96dfac80825c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":167,
              "y":387},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78e666bd5e414395a4908ed1a487a541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":167,
                  "y":387},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"910d817a90a842c0a53cacc0f04ee5e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":363,
              "y":387},
            "size":{
              "width":199,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b7b9357abd4a34af0e299866bee73d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":363,
                  "y":387},
                "size":{
                  "width":199,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6f820906a2b448e806517c6d4122339",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":237,
              "y":385},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b64f548b94f4631b9ef0b94d4c5fb26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":237,
                  "y":385},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0954c949e6d24fedac13df65d0ab952e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":631,
              "y":390},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"e142c89be972448f806d67a83d0a8850",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":731,
              "y":387},
            "size":{
              "width":56,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"160ec5a1cd324f6d990968b33e25f467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":731,
                  "y":387},
                "size":{
                  "width":56,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u23.png"}},
{
          "id":"f11a19a8efb14baab264b3a109c93238",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":477},
            "size":{
              "width":744,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b322a370843d4724b4d67263cc292e9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":477},
                "size":{
                  "width":744,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u12.png"}},
{
          "id":"2a6fdc154e394db7a7169bf32ac12fde",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":165,
              "y":497},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b26543dd93481d88855706af90af38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":165,
                  "y":497},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"3156d1c7d0874135aa9d83cb95939c61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":361,
              "y":497},
            "size":{
              "width":199,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3339cfdb887c4df6880ad43e2edb0685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":361,
                  "y":497},
                "size":{
                  "width":199,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f441edd65968401f9062b5f8e916de0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":235,
              "y":495},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de6aad5633cf43148e31940e7a84c233",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":235,
                  "y":495},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07fc4082ead54b81b0bc8bcc0806e3f5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":629,
              "y":500},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"d087af954d4e4eaeba92521069a875fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":729,
              "y":497},
            "size":{
              "width":56,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7530ec07ab7402ca0ab7ea73501fc6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":729,
                  "y":497},
                "size":{
                  "width":56,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/打分/u23.png"}},
{
          "id":"9ce94b7d88f94893904576e0d5d2bb6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1273,
              "y":362},
            "size":{
              "width":745,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"274bd069cd254d82af5a701fa4cc6394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1273,
                  "y":362},
                "size":{
                  "width":745,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u35.png"}},
{
          "id":"98faca13297144089afca73cc74c8515",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":1317,
              "y":384},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a45264b556d4603b3bda74b8d862ac5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":1317,
                  "y":384},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"280a1f7f10df42dda83383ebf973fdc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":1513,
              "y":384},
            "size":{
              "width":199,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"472d4be15eff4e7585ab06aceaa69a8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1513,
                  "y":384},
                "size":{
                  "width":199,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"986cc6266f444d8bb241905299ea6c68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "location":{
              "x":1387,
              "y":382},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0c197c25d0c45db9dba5f6ebef70793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1387,
                  "y":382},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"36980c16a0d24d609d6dfc781a0257a7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "location":{
              "x":1781,
              "y":387},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"fca188a586d848bcb7900798e69bc846",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "lineSpacing":"48px",
            "location":{
              "x":2160,
              "y":248},
            "size":{
              "width":560,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"021413d085b5438ea268dc8dfb167745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "lineSpacing":"48px",
                "location":{
                  "x":2160,
                  "y":248},
                "size":{
                  "width":560,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/老师打分/u87.png"}},
{
          "id":"4909b8a6ac0740889c931c2710220407",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1990,
              "y":295},
            "size":{
              "width":140,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/老师打分/u89_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d541d87e9241462eadfdbf726f39ee92":{
      "scriptId":"u0"},
    "f48739aa81bf40f9b89f88347a41409a":{
      "scriptId":"u1"},
    "0ebf14b9b99643078b5cbcecb2111cde":{
      "scriptId":"u2"},
    "ac5f71e141454439952f476efa5a5414":{
      "scriptId":"u3"},
    "bc8681cac915466ca6e6f04376208739":{
      "scriptId":"u4"},
    "bf712a94a9d346a6b5bb8471f04d3b2a":{
      "scriptId":"u5"},
    "d556ed0ada2745e3aa2048d754aca0ee":{
      "scriptId":"u6"},
    "ae472692801a489e86dcacbea24b745b":{
      "scriptId":"u7"},
    "e36fd866d0a14988b35278e040a44310":{
      "scriptId":"u8"},
    "f00690b2a9e84cb4ab4684e29acfd344":{
      "scriptId":"u9"},
    "f42120688a7c40049609285f4378f2eb":{
      "scriptId":"u10"},
    "45a739666f8c4e5c863f773d938ff53b":{
      "scriptId":"u11"},
    "35b955b8aceb40e8bdf62ccc30984895":{
      "scriptId":"u12"},
    "9cc46d46ae27492cb731d5f7e01f564a":{
      "scriptId":"u13"},
    "3bd23bdc50af44a785e84284b48e3fa8":{
      "scriptId":"u14"},
    "d39848fa33bd4982a927e8ad94cb6345":{
      "scriptId":"u15"},
    "a72cf86bc1d0408cbc37af5984a92e62":{
      "scriptId":"u16"},
    "d263e9a9dda84ece9bde5b5ed25bd03e":{
      "scriptId":"u17"},
    "a03f61c70e634793a3c00453d39f313a":{
      "scriptId":"u18"},
    "5f1399dedf82451284bb9970925a4bd2":{
      "scriptId":"u19"},
    "7d55bf093726449db30b7f332629017e":{
      "scriptId":"u20"},
    "3c9e61fc377a420ab4ed2dc276d9261e":{
      "scriptId":"u21"},
    "d58bb46fb7af4215a297cc31e657bf43":{
      "scriptId":"u22"},
    "a732d913b8154ce192e5014136419a6d":{
      "scriptId":"u23"},
    "da557f09591241f299b8f33ac4ec2448":{
      "scriptId":"u24"},
    "d07e375efd584a03a2a9fc9d0517b97a":{
      "scriptId":"u25"},
    "ce110986aa3d4e13a8c6f012ec2bbeee":{
      "scriptId":"u26"},
    "95ff507e692340399e3486e900d36cb1":{
      "scriptId":"u27"},
    "0ee388bdee264d63a7b3401271fe1e3d":{
      "scriptId":"u28"},
    "063f9b0533b4467d9efbc291bddbef54":{
      "scriptId":"u29"},
    "31bad77b439d454496df3f1c36b8fe8a":{
      "scriptId":"u30"},
    "6619d30c278f467b8dfa579a78821e84":{
      "scriptId":"u31"},
    "3703bf2d6a7746a28291489efdf207a9":{
      "scriptId":"u32"},
    "837e5874b0454c3ebc46bb54e0c5acfe":{
      "scriptId":"u33"},
    "6a64df9484674d84b21737d64d091dab":{
      "scriptId":"u34"},
    "f249b6a03b2143489c5903b4a8d64862":{
      "scriptId":"u35"},
    "5755861c4aa44f37a35edf8c8eabb6ad":{
      "scriptId":"u36"},
    "7e9ad3afaee040aa91058700b419c472":{
      "scriptId":"u37"},
    "d8fbaf49c28c41999d4956c7adff6976":{
      "scriptId":"u38"},
    "fb23966a28c14ac18ef70d9b8f874557":{
      "scriptId":"u39"},
    "dc412f80b51f4602b7a842beb0f392e7":{
      "scriptId":"u40"},
    "9f548f8925af48b984460302d68ba5f3":{
      "scriptId":"u41"},
    "14a4204983da427c95497da4bdef9523":{
      "scriptId":"u42"},
    "a43792989a84484cac1b7b29653e1871":{
      "scriptId":"u43"},
    "1761b9b3ae3b47c480f2a3cf85cdaadc":{
      "scriptId":"u44"},
    "4a479975157f4a65ad50b938166d69bd":{
      "scriptId":"u45"},
    "0e484947e4bd41bb8a9ed643f51a110b":{
      "scriptId":"u46"},
    "13d1927f7ca64e7285df8f598bf9987b":{
      "scriptId":"u47"},
    "8d60ddceaed44d758e58d45cee6b89c5":{
      "scriptId":"u48"},
    "e9f88104d3904481a4f0ba754c6e2d52":{
      "scriptId":"u49"},
    "0db6bd6760e94c7f8aae6352a350a5fb":{
      "scriptId":"u50"},
    "f91271a8b73d4ba08f98942b81976750":{
      "scriptId":"u51"},
    "ab82ca048ff04f688541bf13d5e09661":{
      "scriptId":"u52"},
    "73782311e5ca439ea592530a38a33b3d":{
      "scriptId":"u53"},
    "8529cb4cdd6b47d58302ace4a2f2a09f":{
      "scriptId":"u54"},
    "9f2c7838a6984debb64daba8009dcec1":{
      "scriptId":"u55"},
    "fc8db2b56dab4b0ba3e3e90ec7072373":{
      "scriptId":"u56"},
    "be5a567233794df7b01e0255651f26db":{
      "scriptId":"u57"},
    "5c5f509db46949ab88fd96dfac80825c":{
      "scriptId":"u58"},
    "78e666bd5e414395a4908ed1a487a541":{
      "scriptId":"u59"},
    "910d817a90a842c0a53cacc0f04ee5e8":{
      "scriptId":"u60"},
    "36b7b9357abd4a34af0e299866bee73d":{
      "scriptId":"u61"},
    "c6f820906a2b448e806517c6d4122339":{
      "scriptId":"u62"},
    "2b64f548b94f4631b9ef0b94d4c5fb26":{
      "scriptId":"u63"},
    "0954c949e6d24fedac13df65d0ab952e":{
      "scriptId":"u64"},
    "e142c89be972448f806d67a83d0a8850":{
      "scriptId":"u65"},
    "160ec5a1cd324f6d990968b33e25f467":{
      "scriptId":"u66"},
    "f11a19a8efb14baab264b3a109c93238":{
      "scriptId":"u67"},
    "b322a370843d4724b4d67263cc292e9e":{
      "scriptId":"u68"},
    "2a6fdc154e394db7a7169bf32ac12fde":{
      "scriptId":"u69"},
    "76b26543dd93481d88855706af90af38":{
      "scriptId":"u70"},
    "3156d1c7d0874135aa9d83cb95939c61":{
      "scriptId":"u71"},
    "3339cfdb887c4df6880ad43e2edb0685":{
      "scriptId":"u72"},
    "f441edd65968401f9062b5f8e916de0c":{
      "scriptId":"u73"},
    "de6aad5633cf43148e31940e7a84c233":{
      "scriptId":"u74"},
    "07fc4082ead54b81b0bc8bcc0806e3f5":{
      "scriptId":"u75"},
    "d087af954d4e4eaeba92521069a875fd":{
      "scriptId":"u76"},
    "e7530ec07ab7402ca0ab7ea73501fc6f":{
      "scriptId":"u77"},
    "9ce94b7d88f94893904576e0d5d2bb6a":{
      "scriptId":"u78"},
    "274bd069cd254d82af5a701fa4cc6394":{
      "scriptId":"u79"},
    "98faca13297144089afca73cc74c8515":{
      "scriptId":"u80"},
    "3a45264b556d4603b3bda74b8d862ac5":{
      "scriptId":"u81"},
    "280a1f7f10df42dda83383ebf973fdc1":{
      "scriptId":"u82"},
    "472d4be15eff4e7585ab06aceaa69a8e":{
      "scriptId":"u83"},
    "986cc6266f444d8bb241905299ea6c68":{
      "scriptId":"u84"},
    "a0c197c25d0c45db9dba5f6ebef70793":{
      "scriptId":"u85"},
    "36980c16a0d24d609d6dfc781a0257a7":{
      "scriptId":"u86"},
    "fca188a586d848bcb7900798e69bc846":{
      "scriptId":"u87"},
    "021413d085b5438ea268dc8dfb167745":{
      "scriptId":"u88"},
    "4909b8a6ac0740889c931c2710220407":{
      "scriptId":"u89"}}});