$axure.loadCurrentPage({
  "url":"小组加分.html",
  "generationDate":new Date(1515736333565),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1dc6021fbfa645a0a429f7e1d3f5ef2d",
    "type":"Axure:Page",
    "name":"小组加分",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"955941bc93184fcabbd640927797da18",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":46},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82c266b1476424182fb69b09fef13fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":46},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"fd91483c77b64a6c9b3d159083ccd8f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "verticalAlignment":"top",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":230,
              "y":86},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"181dcd3ca52a478ca75a279440775a16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "verticalAlignment":"top",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":230,
                  "y":86},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"3dd26fe4bae04117b24d7080d1004d20",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":107},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf5de1f5ee9d4d9da53d504dc92ea507",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":107},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"a5eee47ce3e743b8b11d18d02d27994f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":230,
              "y":46},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a32cbf12ac304a93b78d02bac4cde0f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":230,
                  "y":46},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"df681c7e223c4abe8d03231f9c14e47e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":346},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12d79426ca6842d496a78c0b00da55a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":346},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"f77bb6f0462b4c0ab34eeb793f7c3c17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":286},
            "size":{
              "width":32,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f653cdf2694c43a3283a7464d4ee37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":286},
                "size":{
                  "width":32,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u10.png"}},
{
          "id":"ebbcc5693195466eb91c23d3a7f9dc0e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":288,
              "y":272},
            "size":{
              "width":150,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe1ef2e1411c4fe1a12a830d9d0edb5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":288,
                  "y":272},
                "size":{
                  "width":150,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b882228240e4f7f80115ddab33e8de5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":285,
              "y":355},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1e908ec8e5948829a239bd9c366cb65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":285,
                  "y":355},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"ca4f7153da2443d3a97a4c282f542014",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":535,
              "y":137},
            "size":{
              "width":130,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfa326d3974942889e5b318027516914",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":535,
                  "y":137},
                "size":{
                  "width":130,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e5d8642840544e8a0a8025b61b100e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":652,
              "y":147},
            "size":{
              "width":23,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74e9e7a717a8442c87bd750518e8d81e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":652,
                  "y":147},
                "size":{
                  "width":23,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤/u42.png"}},
{
          "id":"f3c5985475f14a19af7e85999307e2f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":379,
              "y":352},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd2c183687c74cea80e0a40d10b12b0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":352},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"127e39fa7a744d47ac4daab3e55fa3e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":500,
              "y":354},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02794982a20849a389e6d830bc126156",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":354},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ef7751e358c47c3afc7186a17028417",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":410},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e2aab45151d47549120843d638d000d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":410},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"7a58838609ec4b2b9abe5ec5eedaa675",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":285,
              "y":419},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b078af00980430b9a00721ae46d942e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":285,
                  "y":419},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"575fa6bfd6e040cda6147eeca7db523e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":379,
              "y":416},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71151552280a4c3a84f007b85f437a68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":416},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7067ebb068854e95a0af82a9bcc5bdcb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":500,
              "y":418},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ef0a9765d054096a69958b7a31d6e60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":418},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e1274afbf9a4c239ed5331ce9932b4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":474},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db5c0866130473cbb72f028ce23ddb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":474},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"4ec13102543a41728b616891b84b35e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":285,
              "y":483},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ec58bd816374510aef67aefbcb4d137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":285,
                  "y":483},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"1bbae2ef69b94a18a4ccd9106ee2603a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":379,
              "y":480},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1d326151bfc4442b5b1bdfecb2f9eb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":480},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"034a8b10f24041deb9713bc5b33f4052",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":500,
              "y":482},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7a21d49fb44d17b47ac08ecf20ef4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":482},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7557576cdee345f6a0a8498c3339eff3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":628},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa01f16209874624813fb6e757e25d5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":628},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"24a91e0eaa294fedb085a2c0e2f683b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":246,
              "y":565},
            "size":{
              "width":32,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e009f0aff1e46ea910a7a1b60524f12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":246,
                  "y":565},
                "size":{
                  "width":32,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u10.png"}},
{
          "id":"ed2513859e5545fe836fee7241c66481",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":288,
              "y":551},
            "size":{
              "width":150,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0147589808f540789a0461ff2138f33f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":288,
                  "y":551},
                "size":{
                  "width":150,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2336b76a8524e4fb6983d83ebee2f77",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":285,
              "y":637},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a2db2b761142a0b2bad9fd8209ed5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":285,
                  "y":637},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"c30b22d6161b45c787297919695dcb2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":379,
              "y":634},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d6dd4f3502d490a8013ac9869aef0c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":634},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffd92df09e2e4e28bf8389c985a01d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":500,
              "y":636},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe9aeabe99584246adc01bbf1ae8dc1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":636},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1aed1fb33d06448a8cd3bd4e80394496",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":692},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6baa9932c42446f7bd480b7522f2133e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":692},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"95f6fee81a484766998cba718af7b80b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":285,
              "y":701},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36488ca4d30248a0a68becf017472770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":285,
                  "y":701},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"657f5a21cf994dc8852f231715160bd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":379,
              "y":698},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"844f8f40a2dc431ebce1fc17a7d3f236",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":698},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2bf3458f9304c04b313c1c1133921a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":500,
              "y":700},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"500d7a99b4c6403392907fab76743645",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":700},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fd5434b19ee47a784213842680057d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":756},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b258103cf57f4f10afc78fa0ae3528b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":756},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"8437229e5d184e8ca665fcd801d4d9d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":285,
              "y":765},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754b9b521861400799d5b49c010aa7fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":285,
                  "y":765},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"b301e1f4cf5c416db8047252d436ecc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":379,
              "y":762},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d26581c34ce4e409973e34fa914a437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":379,
                  "y":762},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce651e70468b4396b2f144526a765f6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":500,
              "y":764},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca1ef477aae74eedb071df21951c9224",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":764},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"643a013fef13401f9c0a864340285c4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":732,
              "y":272},
            "size":{
              "width":64,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b34668afcce4319bf5a6046e73779ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":732,
                  "y":272},
                "size":{
                  "width":64,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1f5fd43c12424d7cb9d772d0791ef0f4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":789,
              "y":276},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"c7334e2ad1a741ca81c92c9a35fbe8b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":896,
              "y":272},
            "size":{
              "width":64,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf97f478950f40d7a14d86e610201ff4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":896,
                  "y":272},
                "size":{
                  "width":64,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"745cf278fc514b1094bfda889aad1ce5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":723,
              "y":550},
            "size":{
              "width":64,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"704d8a2212784f16af0d85133ab414a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":723,
                  "y":550},
                "size":{
                  "width":64,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfe4c9ac2ae74e1da3c9eeade2b04aaa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":780,
              "y":554},
            "size":{
              "width":100,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"9c31934d6e104023a2b6de25652699cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":887,
              "y":550},
            "size":{
              "width":64,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ba1433d41094e179df153a3b0d7aad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":887,
                  "y":550},
                "size":{
                  "width":64,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de0d7436dfac4300a8cd4c698e2c7d2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":890,
              "y":354},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22b253dc654f4332b47b62733bd7d789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":354},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cfc2295f0f9d4f5786ac066c145a2732",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":896,
              "y":637},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"413b6abb6cfc4991831a90ac5d7b5f6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":896,
                  "y":637},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac60f416373547dda2ebb1a4e19999e8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":230,
              "y":252},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"7ee2a791fcec40cf9a6e77dabfa7e9de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "opacity":"0.3",
            "location":{
              "x":260,
              "y":189},
            "size":{
              "width":700,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67721e21213642f1ad542afe5659e484",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "opacity":"0.3",
                "location":{
                  "x":260,
                  "y":189},
                "size":{
                  "width":700,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "955941bc93184fcabbd640927797da18":{
      "scriptId":"u0"},
    "f82c266b1476424182fb69b09fef13fd":{
      "scriptId":"u1"},
    "fd91483c77b64a6c9b3d159083ccd8f1":{
      "scriptId":"u2"},
    "181dcd3ca52a478ca75a279440775a16":{
      "scriptId":"u3"},
    "3dd26fe4bae04117b24d7080d1004d20":{
      "scriptId":"u4"},
    "bf5de1f5ee9d4d9da53d504dc92ea507":{
      "scriptId":"u5"},
    "a5eee47ce3e743b8b11d18d02d27994f":{
      "scriptId":"u6"},
    "a32cbf12ac304a93b78d02bac4cde0f8":{
      "scriptId":"u7"},
    "df681c7e223c4abe8d03231f9c14e47e":{
      "scriptId":"u8"},
    "12d79426ca6842d496a78c0b00da55a7":{
      "scriptId":"u9"},
    "f77bb6f0462b4c0ab34eeb793f7c3c17":{
      "scriptId":"u10"},
    "73f653cdf2694c43a3283a7464d4ee37":{
      "scriptId":"u11"},
    "ebbcc5693195466eb91c23d3a7f9dc0e":{
      "scriptId":"u12"},
    "fe1ef2e1411c4fe1a12a830d9d0edb5e":{
      "scriptId":"u13"},
    "8b882228240e4f7f80115ddab33e8de5":{
      "scriptId":"u14"},
    "c1e908ec8e5948829a239bd9c366cb65":{
      "scriptId":"u15"},
    "ca4f7153da2443d3a97a4c282f542014":{
      "scriptId":"u16"},
    "bfa326d3974942889e5b318027516914":{
      "scriptId":"u17"},
    "7e5d8642840544e8a0a8025b61b100e7":{
      "scriptId":"u18"},
    "74e9e7a717a8442c87bd750518e8d81e":{
      "scriptId":"u19"},
    "f3c5985475f14a19af7e85999307e2f7":{
      "scriptId":"u20"},
    "bd2c183687c74cea80e0a40d10b12b0f":{
      "scriptId":"u21"},
    "127e39fa7a744d47ac4daab3e55fa3e4":{
      "scriptId":"u22"},
    "02794982a20849a389e6d830bc126156":{
      "scriptId":"u23"},
    "3ef7751e358c47c3afc7186a17028417":{
      "scriptId":"u24"},
    "4e2aab45151d47549120843d638d000d":{
      "scriptId":"u25"},
    "7a58838609ec4b2b9abe5ec5eedaa675":{
      "scriptId":"u26"},
    "8b078af00980430b9a00721ae46d942e":{
      "scriptId":"u27"},
    "575fa6bfd6e040cda6147eeca7db523e":{
      "scriptId":"u28"},
    "71151552280a4c3a84f007b85f437a68":{
      "scriptId":"u29"},
    "7067ebb068854e95a0af82a9bcc5bdcb":{
      "scriptId":"u30"},
    "9ef0a9765d054096a69958b7a31d6e60":{
      "scriptId":"u31"},
    "0e1274afbf9a4c239ed5331ce9932b4c":{
      "scriptId":"u32"},
    "3db5c0866130473cbb72f028ce23ddb3":{
      "scriptId":"u33"},
    "4ec13102543a41728b616891b84b35e5":{
      "scriptId":"u34"},
    "2ec58bd816374510aef67aefbcb4d137":{
      "scriptId":"u35"},
    "1bbae2ef69b94a18a4ccd9106ee2603a":{
      "scriptId":"u36"},
    "d1d326151bfc4442b5b1bdfecb2f9eb2":{
      "scriptId":"u37"},
    "034a8b10f24041deb9713bc5b33f4052":{
      "scriptId":"u38"},
    "7b7a21d49fb44d17b47ac08ecf20ef4d":{
      "scriptId":"u39"},
    "7557576cdee345f6a0a8498c3339eff3":{
      "scriptId":"u40"},
    "fa01f16209874624813fb6e757e25d5f":{
      "scriptId":"u41"},
    "24a91e0eaa294fedb085a2c0e2f683b9":{
      "scriptId":"u42"},
    "2e009f0aff1e46ea910a7a1b60524f12":{
      "scriptId":"u43"},
    "ed2513859e5545fe836fee7241c66481":{
      "scriptId":"u44"},
    "0147589808f540789a0461ff2138f33f":{
      "scriptId":"u45"},
    "f2336b76a8524e4fb6983d83ebee2f77":{
      "scriptId":"u46"},
    "84a2db2b761142a0b2bad9fd8209ed5a":{
      "scriptId":"u47"},
    "c30b22d6161b45c787297919695dcb2e":{
      "scriptId":"u48"},
    "2d6dd4f3502d490a8013ac9869aef0c2":{
      "scriptId":"u49"},
    "ffd92df09e2e4e28bf8389c985a01d07":{
      "scriptId":"u50"},
    "fe9aeabe99584246adc01bbf1ae8dc1c":{
      "scriptId":"u51"},
    "1aed1fb33d06448a8cd3bd4e80394496":{
      "scriptId":"u52"},
    "6baa9932c42446f7bd480b7522f2133e":{
      "scriptId":"u53"},
    "95f6fee81a484766998cba718af7b80b":{
      "scriptId":"u54"},
    "36488ca4d30248a0a68becf017472770":{
      "scriptId":"u55"},
    "657f5a21cf994dc8852f231715160bd6":{
      "scriptId":"u56"},
    "844f8f40a2dc431ebce1fc17a7d3f236":{
      "scriptId":"u57"},
    "e2bf3458f9304c04b313c1c1133921a1":{
      "scriptId":"u58"},
    "500d7a99b4c6403392907fab76743645":{
      "scriptId":"u59"},
    "0fd5434b19ee47a784213842680057d5":{
      "scriptId":"u60"},
    "b258103cf57f4f10afc78fa0ae3528b5":{
      "scriptId":"u61"},
    "8437229e5d184e8ca665fcd801d4d9d4":{
      "scriptId":"u62"},
    "754b9b521861400799d5b49c010aa7fb":{
      "scriptId":"u63"},
    "b301e1f4cf5c416db8047252d436ecc2":{
      "scriptId":"u64"},
    "0d26581c34ce4e409973e34fa914a437":{
      "scriptId":"u65"},
    "ce651e70468b4396b2f144526a765f6a":{
      "scriptId":"u66"},
    "ca1ef477aae74eedb071df21951c9224":{
      "scriptId":"u67"},
    "643a013fef13401f9c0a864340285c4d":{
      "scriptId":"u68"},
    "3b34668afcce4319bf5a6046e73779ae":{
      "scriptId":"u69"},
    "1f5fd43c12424d7cb9d772d0791ef0f4":{
      "scriptId":"u70"},
    "c7334e2ad1a741ca81c92c9a35fbe8b7":{
      "scriptId":"u71"},
    "cf97f478950f40d7a14d86e610201ff4":{
      "scriptId":"u72"},
    "745cf278fc514b1094bfda889aad1ce5":{
      "scriptId":"u73"},
    "704d8a2212784f16af0d85133ab414a6":{
      "scriptId":"u74"},
    "bfe4c9ac2ae74e1da3c9eeade2b04aaa":{
      "scriptId":"u75"},
    "9c31934d6e104023a2b6de25652699cd":{
      "scriptId":"u76"},
    "6ba1433d41094e179df153a3b0d7aad4":{
      "scriptId":"u77"},
    "de0d7436dfac4300a8cd4c698e2c7d2a":{
      "scriptId":"u78"},
    "22b253dc654f4332b47b62733bd7d789":{
      "scriptId":"u79"},
    "cfc2295f0f9d4f5786ac066c145a2732":{
      "scriptId":"u80"},
    "413b6abb6cfc4991831a90ac5d7b5f6c":{
      "scriptId":"u81"},
    "ac60f416373547dda2ebb1a4e19999e8":{
      "scriptId":"u82"},
    "7ee2a791fcec40cf9a6e77dabfa7e9de":{
      "scriptId":"u83"},
    "67721e21213642f1ad542afe5659e484":{
      "scriptId":"u84"}}});