$axure.loadCurrentPage({
  "url":"添加组员.html",
  "generationDate":new Date(1515736335968),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3f157916cc414328aa86fe8828d3083a",
    "type":"Axure:Page",
    "name":"添加组员",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2e6d3db83c414da7b5d940a6571b39d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":60},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5735c15461640adbf18a9e2b3a5995b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":60},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"fd727b6bb9964516a1ee543429fd77f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":50,
              "y":100},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a1867863b643fbbb10cfc7d856250a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":50,
                  "y":100},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"b54101d0cb2b4912a955e15f0dce998b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":121},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3c3e2ec73f44fe9540c49315d8cb9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":121},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"396c842f986a43459c762dbf5691bf4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":50,
              "y":60},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2256cf2f8ee4c8482d1133b3169b96e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":50,
                  "y":60},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"9560575c77094a6995dee73e23c9cabd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":50,
              "y":321},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f182962ed45649c7bce1ade413c8d7f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.2",
                "location":{
                  "x":50,
                  "y":321},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"7c88c1e2343044428065edbfdb25c4de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":640,
              "y":126},
            "size":{
              "width":150,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c249e368d0047c39a3324e0e40164d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":640,
                  "y":126},
                "size":{
                  "width":150,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7b00b20c485c43ae89f0dfe41ef0be9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "location":{
              "x":66,
              "y":264},
            "size":{
              "width":675,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4482ee656b784448a783018437c84c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "location":{
                  "x":66,
                  "y":264},
                "size":{
                  "width":675,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c41e7e3e65e4d8982cf56ecf13d5b86",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":105,
              "y":330},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"927314d20fdf4c078baa71ef7e46a45d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":105,
                  "y":330},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"d72232e5e99b4d6689683baee338b83a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":199,
              "y":327},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ae066d8e604065b496908c7ffb1754",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":199,
                  "y":327},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24cfeb567f3a45dfa867869bbdf501b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":320,
              "y":329},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef2554b226ba4e7380d68bd210be80a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":320,
                  "y":329},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8033cdc8d8c444288eb9adda05417c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":50,
              "y":385},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"133f8727c4d24b80b9f7f18bcd7e5704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.2",
                "location":{
                  "x":50,
                  "y":385},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"abd5b5de4110443cafaed893c4249777",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":105,
              "y":394},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07dd2d503fe54e2ab5066b5905093449",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":105,
                  "y":394},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"7bea8976d18a45a3b5ea3a1ec26a9df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":199,
              "y":391},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dca21a7c5b8b4baf948ac88bb2206812",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":199,
                  "y":391},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9dc6fb155fbe43dba84184bad62a6892",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":320,
              "y":393},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8d7d2da263946fab0d6e83fc19a52a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":320,
                  "y":393},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28b1ff913388474bacdc8bce65c18824",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":50,
              "y":449},
            "size":{
              "width":750,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdaa938b258b43cfa77bd72de5e613c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.2",
                "location":{
                  "x":50,
                  "y":449},
                "size":{
                  "width":750,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/小组加分/u8.png"}},
{
          "id":"82fe6c9d7db14125b5849b302b8baa3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":105,
              "y":458},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95c26ff40b334e54ae7b7d8c8c2bb6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":105,
                  "y":458},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/交作业/u17.png"}},
{
          "id":"f81ae636d5d54f3aae911aaf1abdee0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":199,
              "y":455},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"894fa40657074c8b859739d8063e0d79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":199,
                  "y":455},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e4959d2fb70419f9c328a2a543a8e1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":320,
              "y":457},
            "size":{
              "width":70,
              "height":53}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88ce0ecc18dd49e782222e8c503a8d26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":320,
                  "y":457},
                "size":{
                  "width":70,
                  "height":53}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e702a92282846b08d77c81e9b3968f8",
          "label":"对勾4",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":730,
              "y":337},
            "size":{
              "width":39,
              "height":32},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e9fe465518943bf86cc5bac460c0a53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":730,
                  "y":337},
                "size":{
                  "width":39,
                  "height":32},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 对勾4",
                      "objectsToFades":[{
                          "objectPath":["4e702a92282846b08d77c81e9b3968f8"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/添加组员/对勾4_u36.png"}},
{
          "id":"1e5df5ac602f46feb49c4aa387a35589",
          "label":"对勾4",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":730,
              "y":401},
            "size":{
              "width":39,
              "height":32},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caee3b4d856d42d9abeb6be7b76559a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":730,
                  "y":401},
                "size":{
                  "width":39,
                  "height":32},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 对勾4",
                      "objectsToFades":[{
                          "objectPath":["1e5df5ac602f46feb49c4aa387a35589"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/添加组员/对勾4_u36.png"}},
{
          "id":"8cff83d2eab2419b93f9aeef790c5a17",
          "label":"对勾4",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":730,
              "y":465},
            "size":{
              "width":39,
              "height":32},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94011f6435da455bbad78d75c6e8e85e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":730,
                  "y":465},
                "size":{
                  "width":39,
                  "height":32},
                "visible":false},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 对勾4",
                      "objectsToFades":[{
                          "objectPath":["8cff83d2eab2419b93f9aeef790c5a17"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/添加组员/对勾4_u36.png"}},
{
          "id":"a225e2714bc8484498cbf75f84efd749",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":900,
              "y":175},
            "size":{
              "width":400,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5edbe84ffcc04aa5a5a5f229da7d361b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":900,
                  "y":175},
                "size":{
                  "width":400,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加组员/u42.png"}},
{
          "id":"dc8aed065cc84bf08adf34fb89308c67",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":50,
              "y":254},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"979dafab0c2a4dde9ae43183e0cc1ac0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":60,
              "y":198},
            "size":{
              "width":730,
              "height":54},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c85e1b9d65a40899c2fb2d79cb43268",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":60,
                  "y":198},
                "size":{
                  "width":730,
                  "height":54},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加组员/u45.png"}},
{
          "id":"4ef73963afb042f3a18374831358b164",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":751,
              "y":214},
            "size":{
              "width":139,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/添加组员/u47_line.png"}},
{
          "id":"0bddc862316a4caaa59e9d598598ab9d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":69,
              "y":206},
            "size":{
              "width":41,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bae38d20f00463e938f621afa2d4640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":69,
                  "y":206},
                "size":{
                  "width":41,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的事项/u42.png"}},
{
          "id":"70f38a1683134a1e9d7aed651ed88906",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":320},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d28021ebf65a4d82a450fab4c6ea8fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":820,
                  "y":320},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"898d8a533d65466d842a35fa631765ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":900,
              "y":357.5},
            "size":{
              "width":400,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2797e8faf401469d9508116ebba0759b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":900,
                  "y":357.5},
                "size":{
                  "width":400,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/添加组员/u52.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2e6d3db83c414da7b5d940a6571b39d5":{
      "scriptId":"u0"},
    "c5735c15461640adbf18a9e2b3a5995b":{
      "scriptId":"u1"},
    "fd727b6bb9964516a1ee543429fd77f3":{
      "scriptId":"u2"},
    "10a1867863b643fbbb10cfc7d856250a":{
      "scriptId":"u3"},
    "b54101d0cb2b4912a955e15f0dce998b":{
      "scriptId":"u4"},
    "1d3c3e2ec73f44fe9540c49315d8cb9b":{
      "scriptId":"u5"},
    "396c842f986a43459c762dbf5691bf4c":{
      "scriptId":"u6"},
    "b2256cf2f8ee4c8482d1133b3169b96e":{
      "scriptId":"u7"},
    "9560575c77094a6995dee73e23c9cabd":{
      "scriptId":"u8"},
    "f182962ed45649c7bce1ade413c8d7f3":{
      "scriptId":"u9"},
    "7c88c1e2343044428065edbfdb25c4de":{
      "scriptId":"u10"},
    "3c249e368d0047c39a3324e0e40164d7":{
      "scriptId":"u11"},
    "7b00b20c485c43ae89f0dfe41ef0be9d":{
      "scriptId":"u12"},
    "4482ee656b784448a783018437c84c96":{
      "scriptId":"u13"},
    "0c41e7e3e65e4d8982cf56ecf13d5b86":{
      "scriptId":"u14"},
    "927314d20fdf4c078baa71ef7e46a45d":{
      "scriptId":"u15"},
    "d72232e5e99b4d6689683baee338b83a":{
      "scriptId":"u16"},
    "26ae066d8e604065b496908c7ffb1754":{
      "scriptId":"u17"},
    "24cfeb567f3a45dfa867869bbdf501b3":{
      "scriptId":"u18"},
    "ef2554b226ba4e7380d68bd210be80a1":{
      "scriptId":"u19"},
    "8033cdc8d8c444288eb9adda05417c30":{
      "scriptId":"u20"},
    "133f8727c4d24b80b9f7f18bcd7e5704":{
      "scriptId":"u21"},
    "abd5b5de4110443cafaed893c4249777":{
      "scriptId":"u22"},
    "07dd2d503fe54e2ab5066b5905093449":{
      "scriptId":"u23"},
    "7bea8976d18a45a3b5ea3a1ec26a9df3":{
      "scriptId":"u24"},
    "dca21a7c5b8b4baf948ac88bb2206812":{
      "scriptId":"u25"},
    "9dc6fb155fbe43dba84184bad62a6892":{
      "scriptId":"u26"},
    "d8d7d2da263946fab0d6e83fc19a52a9":{
      "scriptId":"u27"},
    "28b1ff913388474bacdc8bce65c18824":{
      "scriptId":"u28"},
    "cdaa938b258b43cfa77bd72de5e613c2":{
      "scriptId":"u29"},
    "82fe6c9d7db14125b5849b302b8baa3b":{
      "scriptId":"u30"},
    "95c26ff40b334e54ae7b7d8c8c2bb6c6":{
      "scriptId":"u31"},
    "f81ae636d5d54f3aae911aaf1abdee0c":{
      "scriptId":"u32"},
    "894fa40657074c8b859739d8063e0d79":{
      "scriptId":"u33"},
    "8e4959d2fb70419f9c328a2a543a8e1a":{
      "scriptId":"u34"},
    "88ce0ecc18dd49e782222e8c503a8d26":{
      "scriptId":"u35"},
    "4e702a92282846b08d77c81e9b3968f8":{
      "scriptId":"u36"},
    "5e9fe465518943bf86cc5bac460c0a53":{
      "scriptId":"u37"},
    "1e5df5ac602f46feb49c4aa387a35589":{
      "scriptId":"u38"},
    "caee3b4d856d42d9abeb6be7b76559a2":{
      "scriptId":"u39"},
    "8cff83d2eab2419b93f9aeef790c5a17":{
      "scriptId":"u40"},
    "94011f6435da455bbad78d75c6e8e85e":{
      "scriptId":"u41"},
    "a225e2714bc8484498cbf75f84efd749":{
      "scriptId":"u42"},
    "5edbe84ffcc04aa5a5a5f229da7d361b":{
      "scriptId":"u43"},
    "dc8aed065cc84bf08adf34fb89308c67":{
      "scriptId":"u44"},
    "979dafab0c2a4dde9ae43183e0cc1ac0":{
      "scriptId":"u45"},
    "1c85e1b9d65a40899c2fb2d79cb43268":{
      "scriptId":"u46"},
    "4ef73963afb042f3a18374831358b164":{
      "scriptId":"u47"},
    "0bddc862316a4caaa59e9d598598ab9d":{
      "scriptId":"u48"},
    "4bae38d20f00463e938f621afa2d4640":{
      "scriptId":"u49"},
    "70f38a1683134a1e9d7aed651ed88906":{
      "scriptId":"u50"},
    "d28021ebf65a4d82a450fab4c6ea8fc3":{
      "scriptId":"u51"},
    "898d8a533d65466d842a35fa631765ca":{
      "scriptId":"u52"},
    "2797e8faf401469d9508116ebba0759b":{
      "scriptId":"u53"}}});