$axure.loadCurrentPage({
  "url":"数据统计.html",
  "generationDate":new Date(1515736337079),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"30ee49ea8c1143698a7955a810dbd3cf",
    "type":"Axure:Page",
    "name":"数据统计",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bdc43210b7c647f386b2309e6f94d3ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":168},
            "size":{
              "width":750,
              "height":1204},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf80d092cffb4461bf1a894bca7683d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":168},
                "size":{
                  "width":750,
                  "height":1204},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u0.png"}},
{
          "id":"97408e4968694b35bce0298796b282b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":60,
              "y":80},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79923ea3a6b46deb73e84e94a6ba5ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":60,
                  "y":80},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"ab0d02731b1f42a0a360af3d8c4da705",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":76,
              "y":100},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ece15b082a3e44bdbc33a4c6c6be44d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":76,
                  "y":100},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 管理员、老师",
                      "target":{
                        "targetType":"page",
                        "url":"管理员、老师.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"79d60fac97d94a9c9336c4c47df6132d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":60,
              "y":40},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f153b9ec2604e6baa21f4a3b35e4a19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":60,
                  "y":40},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"a21e819399dc45f18298f932bfda36c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":60,
              "y":168},
            "size":{
              "width":375,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d9a403eb1674630bd888ef069fc4a48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":60,
                  "y":168},
                "size":{
                  "width":375,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u8.png"}},
{
          "id":"c2f29cb91b2649749ba7f67a3dc2259a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":434,
              "y":168},
            "size":{
              "width":376,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"148c2876e91d41b5874f212f5f5cc872",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":434,
                  "y":168},
                "size":{
                  "width":376,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u10.png"}},
{
          "id":"c067009f62214591a2b3ae2042cdd8d3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":313,
              "y":194},
            "size":{
              "width":30,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b17378b157a42deaa35cc68ec05e675",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":313,
                  "y":194},
                "size":{
                  "width":30,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u12.png"}},
{
          "id":"49c1d416a2fc4fbd8fa245b4c3543818",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":193.5},
            "size":{
              "width":30,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c0e54cc4fb4a1f8a330eca0682105d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":193.5},
                "size":{
                  "width":30,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u12.png"}},
{
          "id":"84de54644bf24de99a9a28aa049b8532",
          "label":"课程名称",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":62,
              "y":250},
            "size":{
              "width":106,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c52669980464c0d8e6bf2b2fa3152b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":62,
                  "y":250},
                "size":{
                  "width":106,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"214da83b2336498daed29d0f746fc8c1",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":153,
              "y":248},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc0b576d67d7483a859c51a2450b32a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":248},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7dc0d5a15cee4bc1a1de2ed9574cd313",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":312,
              "y":248},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3a625c2b31c4f9ea8be9f35dc3dfb2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":312,
                  "y":248},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d63e6780a0444ad9a9c3813da50b6739",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":471,
              "y":248},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3df60aa0b7d24b1b8ec8dd706b348b5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":471,
                  "y":248},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"822a1c6a065d4c2db198af1850337d05",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":60,
              "y":306},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"c464eec9c35947b98823b59bf356b72a",
          "label":"课程名称",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":62,
              "y":322},
            "size":{
              "width":93,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a49fbeae5ab24540b3dcac74ec535abc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":62,
                  "y":322},
                "size":{
                  "width":93,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8b4a7e786174eb2ae3f6fd8e958076b",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":153,
              "y":318},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10c4398b44b1454189671575baf08584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":318},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2340ff3becee43f59e0acb2dda266b6e",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":312,
              "y":318},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9317af4e8b04824a971b5a96d835ec0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":312,
                  "y":318},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"300d86aef6244bef8e1b77f10b292d08",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":471,
              "y":318},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8aedce9c6cad437aa6301b564a40b527",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":471,
                  "y":318},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6cadc9cf4a4a4c1c9baf7c8fc875c96c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":60,
              "y":378},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"da2d213bdb404befa5b61ff109e3ac24",
          "label":"课程名称",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":62,
              "y":398},
            "size":{
              "width":93,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6693e3e805284e7a8544a1604903b9a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":62,
                  "y":398},
                "size":{
                  "width":93,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d9c8d5a95134b68baebd34479bec2bd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":60,
              "y":454},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"ebc0517cf9c44fbc8db8c4af8d6ddf92",
          "label":"课程名称",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":60,
              "y":468},
            "size":{
              "width":93,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e0e2f78bf73470ead5f0242e926c65c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":60,
                  "y":468},
                "size":{
                  "width":93,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b5d64a7b86fe4cdf91f83b762e0bbb58",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":58,
              "y":528},
            "size":{
              "width":752,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/数据统计/u39_line.png"}},
{
          "id":"dcd6fc7bb7d94dd78b61bc8b4d60b271",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":153,
              "y":392},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"384cae1c2774421f94032db52c47ecfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":392},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"273eede2e1034fb986a15fd10caabe4c",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":312,
              "y":392},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d8bb779ea0a47309de8784c6de84dfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":312,
                  "y":392},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bdc2d69249a94a7f87618a55c34d7323",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":471,
              "y":392},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"405635d9fff54b3c9f7a2531e45675c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":471,
                  "y":392},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2152515c10af410f80b96357b2c5284c",
          "label":"入学年份",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":153,
              "y":468},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f49548ff95b849579cb992dfd92000f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":153,
                  "y":468},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e526bccb805e4181965a2502a6593edc",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":312,
              "y":468},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bad42f5ea0c941589f02c90629545745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":312,
                  "y":468},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9511735409664dabb1c1b18d0805bdca",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":471,
              "y":468},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0226d627f9415c825d0daa37001166",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":471,
                  "y":468},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"719e9ff867d04327b24c1c0ab0cae6ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "location":{
              "x":940,
              "y":312},
            "size":{
              "width":260,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cfa9884e9604076ae0fcc9a50d8e33f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "location":{
                  "x":940,
                  "y":312},
                "size":{
                  "width":260,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据统计/u52.png"}},
{
          "id":"6aafe2fa9b504a30a259983f036ab2c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":312},
            "size":{
              "width":750,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99e4ed4cc3ac4568a8bba705f832a5a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":312},
                "size":{
                  "width":750,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 数据统计",
                      "target":{
                        "targetType":"page",
                        "url":"数据统计_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4debd50bc4b741bd8f58cf6e96a676b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":387},
            "size":{
              "width":750,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1d8f9d45f7f4c0d98368a704c8f871f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":387},
                "size":{
                  "width":750,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2913e99b37f44a2a6c7c4f74e889b97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":462},
            "size":{
              "width":750,
              "height":72}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61ce04d16c3d413bac5317d6925967f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":462},
                "size":{
                  "width":750,
                  "height":72}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92c03865f57d4d32bd6ebe352e3c9ee4",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":639,
              "y":249},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e238e053cddd4d28b1e03a07673dc11d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":639,
                  "y":249},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b325680d1954e60a90dd49b81c5b507",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":639,
              "y":318},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a741ea17aa34476986bc305a1c9eea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":639,
                  "y":318},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26ef944abc5249149ac64f34c9288b21",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":639,
              "y":388},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01b3bf1aafba41f6a376e12fa472a1b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":639,
                  "y":388},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd53f5e8f6c94f8186a010082f743e0e",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":639,
              "y":468},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73ee1073a7f3433aad982f416a343173",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":639,
                  "y":468},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1fb88bce065641a7aac514aafdc8dfd4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":790,
              "y":343},
            "size":{
              "width":140,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"images/数据统计/u68_start.png",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/数据统计/u68_line.png"}},
{
          "id":"e1f1ae55446c4c77a3ab586ce44cad08",
          "label":"所在班级",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":639,
              "y":98},
            "size":{
              "width":158,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"705f49efea204e1987c240174c47f335",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":639,
                  "y":98},
                "size":{
                  "width":158,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bdc43210b7c647f386b2309e6f94d3ce":{
      "scriptId":"u0"},
    "bf80d092cffb4461bf1a894bca7683d0":{
      "scriptId":"u1"},
    "97408e4968694b35bce0298796b282b6":{
      "scriptId":"u2"},
    "e79923ea3a6b46deb73e84e94a6ba5ea":{
      "scriptId":"u3"},
    "ab0d02731b1f42a0a360af3d8c4da705":{
      "scriptId":"u4"},
    "ece15b082a3e44bdbc33a4c6c6be44d3":{
      "scriptId":"u5"},
    "79d60fac97d94a9c9336c4c47df6132d":{
      "scriptId":"u6"},
    "0f153b9ec2604e6baa21f4a3b35e4a19":{
      "scriptId":"u7"},
    "a21e819399dc45f18298f932bfda36c6":{
      "scriptId":"u8"},
    "6d9a403eb1674630bd888ef069fc4a48":{
      "scriptId":"u9"},
    "c2f29cb91b2649749ba7f67a3dc2259a":{
      "scriptId":"u10"},
    "148c2876e91d41b5874f212f5f5cc872":{
      "scriptId":"u11"},
    "c067009f62214591a2b3ae2042cdd8d3":{
      "scriptId":"u12"},
    "2b17378b157a42deaa35cc68ec05e675":{
      "scriptId":"u13"},
    "49c1d416a2fc4fbd8fa245b4c3543818":{
      "scriptId":"u14"},
    "62c0e54cc4fb4a1f8a330eca0682105d":{
      "scriptId":"u15"},
    "84de54644bf24de99a9a28aa049b8532":{
      "scriptId":"u16"},
    "7c52669980464c0d8e6bf2b2fa3152b2":{
      "scriptId":"u17"},
    "214da83b2336498daed29d0f746fc8c1":{
      "scriptId":"u18"},
    "dc0b576d67d7483a859c51a2450b32a4":{
      "scriptId":"u19"},
    "7dc0d5a15cee4bc1a1de2ed9574cd313":{
      "scriptId":"u20"},
    "e3a625c2b31c4f9ea8be9f35dc3dfb2f":{
      "scriptId":"u21"},
    "d63e6780a0444ad9a9c3813da50b6739":{
      "scriptId":"u22"},
    "3df60aa0b7d24b1b8ec8dd706b348b5f":{
      "scriptId":"u23"},
    "822a1c6a065d4c2db198af1850337d05":{
      "scriptId":"u24"},
    "c464eec9c35947b98823b59bf356b72a":{
      "scriptId":"u25"},
    "a49fbeae5ab24540b3dcac74ec535abc":{
      "scriptId":"u26"},
    "c8b4a7e786174eb2ae3f6fd8e958076b":{
      "scriptId":"u27"},
    "10c4398b44b1454189671575baf08584":{
      "scriptId":"u28"},
    "2340ff3becee43f59e0acb2dda266b6e":{
      "scriptId":"u29"},
    "d9317af4e8b04824a971b5a96d835ec0":{
      "scriptId":"u30"},
    "300d86aef6244bef8e1b77f10b292d08":{
      "scriptId":"u31"},
    "8aedce9c6cad437aa6301b564a40b527":{
      "scriptId":"u32"},
    "6cadc9cf4a4a4c1c9baf7c8fc875c96c":{
      "scriptId":"u33"},
    "da2d213bdb404befa5b61ff109e3ac24":{
      "scriptId":"u34"},
    "6693e3e805284e7a8544a1604903b9a4":{
      "scriptId":"u35"},
    "2d9c8d5a95134b68baebd34479bec2bd":{
      "scriptId":"u36"},
    "ebc0517cf9c44fbc8db8c4af8d6ddf92":{
      "scriptId":"u37"},
    "8e0e2f78bf73470ead5f0242e926c65c":{
      "scriptId":"u38"},
    "b5d64a7b86fe4cdf91f83b762e0bbb58":{
      "scriptId":"u39"},
    "dcd6fc7bb7d94dd78b61bc8b4d60b271":{
      "scriptId":"u40"},
    "384cae1c2774421f94032db52c47ecfb":{
      "scriptId":"u41"},
    "273eede2e1034fb986a15fd10caabe4c":{
      "scriptId":"u42"},
    "8d8bb779ea0a47309de8784c6de84dfb":{
      "scriptId":"u43"},
    "bdc2d69249a94a7f87618a55c34d7323":{
      "scriptId":"u44"},
    "405635d9fff54b3c9f7a2531e45675c4":{
      "scriptId":"u45"},
    "2152515c10af410f80b96357b2c5284c":{
      "scriptId":"u46"},
    "f49548ff95b849579cb992dfd92000f8":{
      "scriptId":"u47"},
    "e526bccb805e4181965a2502a6593edc":{
      "scriptId":"u48"},
    "bad42f5ea0c941589f02c90629545745":{
      "scriptId":"u49"},
    "9511735409664dabb1c1b18d0805bdca":{
      "scriptId":"u50"},
    "cc0226d627f9415c825d0daa37001166":{
      "scriptId":"u51"},
    "719e9ff867d04327b24c1c0ab0cae6ea":{
      "scriptId":"u52"},
    "3cfa9884e9604076ae0fcc9a50d8e33f":{
      "scriptId":"u53"},
    "6aafe2fa9b504a30a259983f036ab2c1":{
      "scriptId":"u54"},
    "99e4ed4cc3ac4568a8bba705f832a5a6":{
      "scriptId":"u55"},
    "4debd50bc4b741bd8f58cf6e96a676b1":{
      "scriptId":"u56"},
    "f1d8f9d45f7f4c0d98368a704c8f871f":{
      "scriptId":"u57"},
    "a2913e99b37f44a2a6c7c4f74e889b97":{
      "scriptId":"u58"},
    "61ce04d16c3d413bac5317d6925967f9":{
      "scriptId":"u59"},
    "92c03865f57d4d32bd6ebe352e3c9ee4":{
      "scriptId":"u60"},
    "e238e053cddd4d28b1e03a07673dc11d":{
      "scriptId":"u61"},
    "8b325680d1954e60a90dd49b81c5b507":{
      "scriptId":"u62"},
    "7a741ea17aa34476986bc305a1c9eea2":{
      "scriptId":"u63"},
    "26ef944abc5249149ac64f34c9288b21":{
      "scriptId":"u64"},
    "01b3bf1aafba41f6a376e12fa472a1b5":{
      "scriptId":"u65"},
    "dd53f5e8f6c94f8186a010082f743e0e":{
      "scriptId":"u66"},
    "73ee1073a7f3433aad982f416a343173":{
      "scriptId":"u67"},
    "1fb88bce065641a7aac514aafdc8dfd4":{
      "scriptId":"u68"},
    "e1f1ae55446c4c77a3ab586ce44cad08":{
      "scriptId":"u69"},
    "705f49efea204e1987c240174c47f335":{
      "scriptId":"u70"}}});