$axure.loadCurrentPage({
  "url":"选择任务.html",
  "generationDate":new Date(1515736336341),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66bf284457bc4253b9ddd4e74729e4b0",
    "type":"Axure:Page",
    "name":"选择任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"946683e956134c5ea1c42d7b83bdfccf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"058e841c65a444fc9a1694443fab8348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"5de01d9ff755482086e23f2410ff7989",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f7e42fd50694431ad80d2a5c03f186f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"3a1936fbc13e47e79c84b14457b7ab7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7d5515dac7b47b197e3bc9d5e2a2d29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"16566b1c8067475c84b8ad852d72de5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":131},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"683837e8039747dda445e916d8f65dbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":131},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加任务",
                      "target":{
                        "targetType":"page",
                        "url":"添加任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"9daae52315844950b2d4e870b372ed73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":210},
            "size":{
              "width":244,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aad0cba4f2714cb293d91c3829ab7d90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":210},
                "size":{
                  "width":244,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc450bec5af94ef589ba99c9fc2ac2fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":270},
            "size":{
              "width":554,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6248bd185ad0490395886c1c3e109152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":270},
                "size":{
                  "width":554,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2156d97cfc2c49b394473da9b441a286",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":336},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"3f27a05321a94fc7a327e4cbdcca7a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":364},
            "size":{
              "width":234,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1728bc0e1aa24bee8113d88ac799aded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":364},
                "size":{
                  "width":234,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da8419cfcc024368b7d2cac3a842a5ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":424},
            "size":{
              "width":564,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35ef3351fcfc4dbcaaa6bca6520071f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":424},
                "size":{
                  "width":564,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1eb532f67e948df94892df54dc5326a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":490},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"1ee0ecbc28114bfb9b0e1807385cbe7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":520},
            "size":{
              "width":224,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a3cc1a0d38949efaa83e1610e572856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":520},
                "size":{
                  "width":224,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3209069c34d94d6ea8923caa98314467",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":106,
              "y":580},
            "size":{
              "width":574,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61c873ca8d544a0195b152c9c57fae12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":106,
                  "y":580},
                "size":{
                  "width":574,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45d92da13b684ae4977291f0096fcf74",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":646},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"129040bfc9bc46d7849cb21641d2a346",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":106,
              "y":669},
            "size":{
              "width":224,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d50b14cf5fb240f9a82ee44628d3ecfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":106,
                  "y":669},
                "size":{
                  "width":224,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d421d16e3de84ebea8b241abe5df80ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"36px",
            "location":{
              "x":106,
              "y":729},
            "size":{
              "width":574,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"856b92432f8248c98278459ef5cb9427",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"36px",
                "location":{
                  "x":106,
                  "y":729},
                "size":{
                  "width":574,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"daaf264d79134ff88145241a392841ef",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":96,
              "y":795},
            "size":{
              "width":704,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/任务库/u12_line.png"}},
{
          "id":"6c2c5c9bfae948e08aab0b9cc0744b6b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":810,
              "y":269},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56d20b94401d4c40ae3225d077131b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":810,
                  "y":269},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"3a51c5ae1757460c974f88df3cd50d76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":930,
              "y":223.5},
            "size":{
              "width":774,
              "height":97}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47535e9edbd242b3a5a62e291a0a0080",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":930,
                  "y":223.5},
                "size":{
                  "width":774,
                  "height":97}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u30.png"}},
{
          "id":"aad62f4a7b6e43a4a3da3c1e46539032",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":590,
              "y":242},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b477e0d604684f57a4db7162f9e94a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":242},
                "size":{
                  "width":70,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5311c8923abd4e0abdf4ab5423df7c1a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":590,
              "y":372},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f85897ce7d8d4bc9b044e4722ee349af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":372},
                "size":{
                  "width":70,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae192c2e9f944693bb3f640b8b7acd5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":590,
              "y":528},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a8d5170983b4fe1a1bddd479f8f390e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":528},
                "size":{
                  "width":70,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76afff234a1e402eb6e338abc23e857e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":590,
              "y":669},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59f7526f6bb3405a958f5a4b5b04c89d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":590,
                  "y":669},
                "size":{
                  "width":70,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c17b68413e6548e7b202c762b2c8c9ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":80,
              "y":1331},
            "size":{
              "width":750,
              "height":74},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f118d557d43749fca24727ff57516cef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":80,
                  "y":1331},
                "size":{
                  "width":750,
                  "height":74},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u40.png"}},
{
          "id":"e66829ebba8a4b339b1ea7ce0158378a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":250},
            "size":{
              "width":46,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a446c3d8c5754b47b46b0f5987bcc259",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":250},
                "size":{
                  "width":46,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u42.png"}},
{
          "id":"a4d91b17f7f24c468d877798512f9750",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":396},
            "size":{
              "width":46,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82e32abffe974c5baf1cec479483771d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":396},
                "size":{
                  "width":46,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u42.png"}},
{
          "id":"6d68abf7ddd34f8a9f205a9384e7cbb1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":544},
            "size":{
              "width":46,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea288355b0d42748763bed376830597",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":544},
                "size":{
                  "width":46,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u42.png"}},
{
          "id":"0553ff78840b4e6eb9594cd408bbe148",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":730,
              "y":715},
            "size":{
              "width":46,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f30303a7ba45d480d27d9e0bc543f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":730,
                  "y":715},
                "size":{
                  "width":46,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择任务/u42.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "946683e956134c5ea1c42d7b83bdfccf":{
      "scriptId":"u0"},
    "058e841c65a444fc9a1694443fab8348":{
      "scriptId":"u1"},
    "5de01d9ff755482086e23f2410ff7989":{
      "scriptId":"u2"},
    "3f7e42fd50694431ad80d2a5c03f186f":{
      "scriptId":"u3"},
    "3a1936fbc13e47e79c84b14457b7ab7a":{
      "scriptId":"u4"},
    "a7d5515dac7b47b197e3bc9d5e2a2d29":{
      "scriptId":"u5"},
    "16566b1c8067475c84b8ad852d72de5d":{
      "scriptId":"u6"},
    "683837e8039747dda445e916d8f65dbd":{
      "scriptId":"u7"},
    "9daae52315844950b2d4e870b372ed73":{
      "scriptId":"u8"},
    "aad0cba4f2714cb293d91c3829ab7d90":{
      "scriptId":"u9"},
    "bc450bec5af94ef589ba99c9fc2ac2fd":{
      "scriptId":"u10"},
    "6248bd185ad0490395886c1c3e109152":{
      "scriptId":"u11"},
    "2156d97cfc2c49b394473da9b441a286":{
      "scriptId":"u12"},
    "3f27a05321a94fc7a327e4cbdcca7a29":{
      "scriptId":"u13"},
    "1728bc0e1aa24bee8113d88ac799aded":{
      "scriptId":"u14"},
    "da8419cfcc024368b7d2cac3a842a5ca":{
      "scriptId":"u15"},
    "35ef3351fcfc4dbcaaa6bca6520071f9":{
      "scriptId":"u16"},
    "a1eb532f67e948df94892df54dc5326a":{
      "scriptId":"u17"},
    "1ee0ecbc28114bfb9b0e1807385cbe7a":{
      "scriptId":"u18"},
    "5a3cc1a0d38949efaa83e1610e572856":{
      "scriptId":"u19"},
    "3209069c34d94d6ea8923caa98314467":{
      "scriptId":"u20"},
    "61c873ca8d544a0195b152c9c57fae12":{
      "scriptId":"u21"},
    "45d92da13b684ae4977291f0096fcf74":{
      "scriptId":"u22"},
    "129040bfc9bc46d7849cb21641d2a346":{
      "scriptId":"u23"},
    "d50b14cf5fb240f9a82ee44628d3ecfb":{
      "scriptId":"u24"},
    "d421d16e3de84ebea8b241abe5df80ce":{
      "scriptId":"u25"},
    "856b92432f8248c98278459ef5cb9427":{
      "scriptId":"u26"},
    "daaf264d79134ff88145241a392841ef":{
      "scriptId":"u27"},
    "6c2c5c9bfae948e08aab0b9cc0744b6b":{
      "scriptId":"u28"},
    "56d20b94401d4c40ae3225d077131b2d":{
      "scriptId":"u29"},
    "3a51c5ae1757460c974f88df3cd50d76":{
      "scriptId":"u30"},
    "47535e9edbd242b3a5a62e291a0a0080":{
      "scriptId":"u31"},
    "aad62f4a7b6e43a4a3da3c1e46539032":{
      "scriptId":"u32"},
    "b477e0d604684f57a4db7162f9e94a31":{
      "scriptId":"u33"},
    "5311c8923abd4e0abdf4ab5423df7c1a":{
      "scriptId":"u34"},
    "f85897ce7d8d4bc9b044e4722ee349af":{
      "scriptId":"u35"},
    "ae192c2e9f944693bb3f640b8b7acd5a":{
      "scriptId":"u36"},
    "7a8d5170983b4fe1a1bddd479f8f390e":{
      "scriptId":"u37"},
    "76afff234a1e402eb6e338abc23e857e":{
      "scriptId":"u38"},
    "59f7526f6bb3405a958f5a4b5b04c89d":{
      "scriptId":"u39"},
    "c17b68413e6548e7b202c762b2c8c9ca":{
      "scriptId":"u40"},
    "f118d557d43749fca24727ff57516cef":{
      "scriptId":"u41"},
    "e66829ebba8a4b339b1ea7ce0158378a":{
      "scriptId":"u42"},
    "a446c3d8c5754b47b46b0f5987bcc259":{
      "scriptId":"u43"},
    "a4d91b17f7f24c468d877798512f9750":{
      "scriptId":"u44"},
    "82e32abffe974c5baf1cec479483771d":{
      "scriptId":"u45"},
    "6d68abf7ddd34f8a9f205a9384e7cbb1":{
      "scriptId":"u46"},
    "7ea288355b0d42748763bed376830597":{
      "scriptId":"u47"},
    "0553ff78840b4e6eb9594cd408bbe148":{
      "scriptId":"u48"},
    "84f30303a7ba45d480d27d9e0bc543f8":{
      "scriptId":"u49"}}});