$axure.loadCurrentPage({
  "url":"评分任务.html",
  "generationDate":new Date(1515736335323),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"795d749ed8cf468093b9e8e8c2a89b9e",
    "type":"Axure:Page",
    "name":"评分任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bc30c687d97c443fa34509f6e3a29990",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26179c11b5b5451787d32dc39fdd5558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"e10044a113e84c71adc8e7f69afbb544",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":50,
              "y":50},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53f16ff38c6c46deac873520a31e311b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":50,
                  "y":50},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"0f2c218c5aa046c795bdb34a1654f021",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":50,
              "y":90},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8909e1fc39e64a31985704d738c80626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":50,
                  "y":90},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"a6e99e08e7774734847f0e6f189f26ec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":111},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b8f29b6a7fb4a28a30c045cb0d20858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":111},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务库",
                      "target":{
                        "targetType":"page",
                        "url":"任务库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"40e57155703a4a0484e030ecf6014015",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":80,
              "y":194},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a17d642c89843ecafcdd733a439dceb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":80,
                  "y":194},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79439eb61e5f4209b924c99f99d37c9b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":50,
              "y":529},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"ae8a7a85b1ff4b27ace408e922b1295a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":52,
              "y":273},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef481bc038774dd8a20e225004f8e820",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":52,
                  "y":273},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"41ae526ab49942c598f4e3af282987fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":52,
              "y":430},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92f675606e7040d79a009c77bd417d02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":52,
                  "y":430},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"30a13f255f3242ed83889c98d123f18b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":80,
              "y":469},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d306e91c086845bb94011c0e17345372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":80,
                  "y":469},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f161d7235ab40ce9bdee901f20a56ae",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":536},
            "size":{
              "width":750,
              "height":379}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5b9aca9655e34bc99cc733a8a808bc95",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3b92c0edcb344bc1ab6bbb79964deadb",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":750,
                      "height":379},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"afc4552c01e24823b052afa0b0efc65e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":750,
                          "height":379},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/阅读任务/u93.png"}},
{
                  "id":"10bac34d7b694141be2c58324b237579",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0cb770228bec47159835a7c4257a5a13",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"52e4d209dae0480797895a4dcd6ac394",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":11},
                    "size":{
                      "width":124,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"28b6654e17f543ed869655367026d6b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":11},
                        "size":{
                          "width":124,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c60a523d28bb47eab8b8486dd79a192e",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":110},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c77e497d7e594dc4b1d15fb7cdeedb14",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":110},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"02387695a48846708fbc888932310d19",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":200},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14ff5894e2794199b9b22d4f8fd2e6cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":200},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"56a832b236fc4e808944719068c83db4",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":190},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a716ce1495f44b88dd8c7219ea2ae40",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":190},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"ddaece9303b74170a9c1bfa64902fc46",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":120},
                    "size":{
                      "width":184,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2023565275f3486b8d5bdbdc172d1572",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":120},
                        "size":{
                          "width":184,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c2d60aab52ae4d40a9a2592e45e7d651",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":200},
                    "size":{
                      "width":184,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"638827f49eec4635aeca9d5804f30fbe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":200},
                        "size":{
                          "width":184,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f005dd7e249b45b7be29787749fbf9ad",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":299},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c972e90d6069496c95d86d58cba737f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":299},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"6f91e83a2301439eadb41e9dd256b799",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":310},
                    "size":{
                      "width":244,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e5c92c1797643a89932794379dbdfe0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":310},
                        "size":{
                          "width":244,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"35a8c32f298646bbba256ee4cfb3a063",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":120},
                    "size":{
                      "width":70,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"787ba5f308574ce9a2a8388175a22020",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":540,
                          "y":120},
                        "size":{
                          "width":70,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"11bc1fa471474515a8d4941338a73154",
                  "label":"",
                  "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":310},
                    "size":{
                      "width":70,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"caaab580b1ac4438ab104092890e0663",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8f161d7235ab40ce9bdee901f20a56ae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":540,
                          "y":310},
                        "size":{
                          "width":70,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"188983a1c5bd4aa2ac193e3454e232e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":52,
              "y":953},
            "size":{
              "width":746,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aeca6716200459099e0bab24445ca44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":953},
                "size":{
                  "width":746,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u382.png"}},
{
          "id":"54d846a80627489c823cc33e41fb56dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":52,
              "y":1057},
            "size":{
              "width":746,
              "height":87},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7cee0fd31a4d06affbedd6cbfe4ced",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":52,
                  "y":1057},
                "size":{
                  "width":746,
                  "height":87},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u54.png"}},
{
          "id":"64b35c9929ab4af1aa09b5f5a6a8f8a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":52,
              "y":917},
            "size":{
              "width":746,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4ecb514d5374eeda1d19de918c2bd92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":52,
                  "y":917},
                "size":{
                  "width":746,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u56.png"}},
{
          "id":"efb6d1fff5c64cf6abf4069609f27055",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":52,
              "y":1024},
            "size":{
              "width":746,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cde77e8318b4bb2984600ad8f427a06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":52,
                  "y":1024},
                "size":{
                  "width":746,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u56.png"}},
{
          "id":"d3b4f697ed2c4cdc811288bf94b706e5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":52,
              "y":1144},
            "size":{
              "width":746,
              "height":236},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ca8e58429f24684bc9018e1f19890cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":52,
                  "y":1144},
                "size":{
                  "width":746,
                  "height":236},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评分任务/u50.png"}},
{
          "id":"f16037b3f09b41e98a1a8c1b87a05a3a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":1002},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"516f357c41b841c394ac45ddb08c42f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1040,
              "y":50},
            "size":{
              "width":750,
              "height":1466}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c79fa6b65cb24a06a561281396fccfa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1040,
                  "y":50},
                "size":{
                  "width":750,
                  "height":1466}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评分任务/u53.png"}},
{
          "id":"5f62700b89b74dd4981e067891d27a08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1040,
              "y":50},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc721b926bd049769f0970ba10c09bcd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1040,
                  "y":50},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"a7c310e1299345a988be3a66e8d63b11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":1040,
              "y":90},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"241d9d632c6641b3a42780858523688c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":1040,
                  "y":90},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"2e52d34548e34c58badf8bcf42f9f55b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1056,
              "y":111},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"571a086155854138a364143dcf27b665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1056,
                  "y":111},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"b5b6dcbf323d406997184da1cab52dda",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1070,
              "y":194},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ced4f849724d5c8f63aa1ab2d9eac1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1070,
                  "y":194},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d8399cd26494de1897aa91d203b0088",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":1199,
              "y":201},
            "size":{
              "width":410,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"475c6db0fd244bdf9f80a1ca2e1700e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":1587,
              "y":194},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"033718ea26024b38ae85ff32030005ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":1587,
                  "y":194},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dbe1b17673464af39c6c10e2329566f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1070,
              "y":313},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09210e45d3b46448831931aa07b05e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1070,
                  "y":313},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9efca7249d3488a9b29a12d22f202df",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1475,
              "y":313},
            "size":{
              "width":260,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9998806a8e54d92ad0954c4e3398c71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1475,
                  "y":313},
                "size":{
                  "width":260,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务内容",
                      "target":{
                        "targetType":"page",
                        "url":"任务内容.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8bbed4487bd74f7b8137c230f3ea4a3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":1041,
              "y":1405},
            "size":{
              "width":749,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65d480ca01d643f9ab548067b914312e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":1041,
                  "y":1405},
                "size":{
                  "width":749,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评分任务/u70.png"}},
{
          "id":"6d84e84c3d194a0894849c999bac75a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1042,
              "y":273},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daadb5f55e2640858b1f8a393f83fc6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1042,
                  "y":273},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"3ea4d44c5492494c95e6de314447b73e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1042,
              "y":382},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc130210089f4dd789b57244562a0e0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1042,
                  "y":382},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"6f723560148b48d5a0ddff784506ab58",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1041,
              "y":559},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"4166fa9ff84449ac9f2ac7580547a339",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1071,
              "y":499},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfa1b6a4ea77483b88d708f8ec5de9c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1071,
                  "y":499},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b335c7f0310c4a94acabe6ad4b54a5d3",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1041,
              "y":566},
            "size":{
              "width":751,
              "height":950}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"56de6b0d4e2540d58d9393851d684897",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d3419172d50944fa846c9d7e8679c845",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":1,
                      "y":160},
                    "size":{
                      "width":750,
                      "height":762},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c237dd0a5d644923b4ae6ad0c3fae7d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":1,
                          "y":160},
                        "size":{
                          "width":750,
                          "height":762},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/评分任务/u80.png"}},
{
                  "id":"3696fca1f5e14f3facddb50d93961d92",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":189},
                    "size":{
                      "width":750,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d03caf9a9e554524b13ee250b14570b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":189},
                        "size":{
                          "width":750,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u31.png"}},
{
                  "id":"02f12da3c18147f4bfc4b64f77f701e4",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":472,
                      "y":217},
                    "size":{
                      "width":108,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"989e4c36a09643b8bc285350df0f8eb8",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":610,
                      "y":209},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8ff1474e7304f63afc6c4c80cbfb137",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":610,
                          "y":209},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4baa82b6e55e441ea75b32181a3f56d7",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":209},
                    "size":{
                      "width":124,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"542be88dc80a4c61bfec33c910487f0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":209},
                        "size":{
                          "width":124,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"60ad2074dc8349e182c7237d4b292956",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":289},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7edfff7a71704181882fa03a3f7bcf0b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":289},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"b29cb74c06264b3c835cdb05a4893d55",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":319},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca743f6ac9a14823ba4db44085606f54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":319},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"9c48fa296a864a3cb5c1f5e68571360a",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":452},
                    "size":{
                      "width":750,
                      "height":298},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d318d9f271f8418e8029c0e1e54a7aba",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":452},
                        "size":{
                          "width":750,
                          "height":298},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/评分任务/u93.png"}},
{
                  "id":"bed0fb35494b416fb32a7cdb3c8dc8fe",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":544},
                    "size":{
                      "width":360,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0c7f041fed414386a7667245557442e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":544},
                        "size":{
                          "width":360,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"e55640edfa05482ea341d030a4dc4140",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":462},
                    "size":{
                      "width":190,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0516d18106794e08b82fde10a666086d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":462},
                        "size":{
                          "width":190,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"aed875f970464e1891bac9970e171bdd",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":614},
                    "size":{
                      "width":360,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"92ff2282b72c48ac9a92f3d94ab18316",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":614},
                        "size":{
                          "width":360,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"54adcdd22266426893848cf179534c39",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":682},
                    "size":{
                      "width":480,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c288a972c99f4fff9266750bda431d7f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":682},
                        "size":{
                          "width":480,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"0ba3e107da1c49b2ad1c19457be17ab0",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE,
                      "opacity":1},
                    "location":{
                      "x":30,
                      "y":760},
                    "size":{
                      "width":700,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cbc6e051c65e44978ea79caba27e00ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFAEAEAE,
                          "opacity":1},
                        "location":{
                          "x":30,
                          "y":760},
                        "size":{
                          "width":700,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2056b483107842e9a5ffc2f0aa8c65e0",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":842},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c34bd4ca92dc4948865f6fa25d7d0d6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":842},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"7ee5551fe0a64d42b41e896f5fff8a3a",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":472,
                      "y":860},
                    "size":{
                      "width":108,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"fe510b3d6ea54d499cf6d0e83c8b952b",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":610,
                      "y":852},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ccc473e6da184a7d8d050c3b7147de5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":610,
                          "y":852},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e899c70552149978f72877eea0decdc",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":30,
                      "y":852},
                    "size":{
                      "width":200,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6e8546c5d30c455f88fee8f4dcdcd8a0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":30,
                          "y":852},
                        "size":{
                          "width":200,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c4b63b4911d458eac9cab8097469c08",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f4ecdb772e642bcb1883a13779e8d72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"ba81c0f73e7648459307853e005de993",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efbc602a49a64994b66ef9b2eb93c1f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"9369f20b3dbe4b8a8924efbbcc99f99d",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":30},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"478381b255bf4366a1899677eb2ffbcb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":30},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"7fb0bc981e804e15b1df4a1c91c7d0c2",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":105},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c009a8490d02470d89c2d7af5926d2c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":105},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"b7de546801294d06b240e3abfc5c33dd",
                  "label":"",
                  "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFC9C9C9,
                      "opacity":1},
                    "location":{
                      "x":25,
                      "y":379},
                    "size":{
                      "width":700,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"239d6ab3c5b84320a73d70f4dcc49e8b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b335c7f0310c4a94acabe6ad4b54a5d3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFC9C9C9,
                          "opacity":1},
                        "location":{
                          "x":25,
                          "y":379},
                        "size":{
                          "width":700,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"60556747577943dc92f9f6a84f835132",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":80,
              "y":315},
            "size":{
              "width":680,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0329c30d8a348f188c893422feda1e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":80,
                  "y":315},
                "size":{
                  "width":680,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a19dc46981a41948c6ffa6aa0e8b89b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1072,
              "y":423},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9384b9cb234e89959ab0aa60592daf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1072,
                  "y":423},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3ea952a01fa4d32840a4b22af9a9114",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1042,
              "y":487},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bc30c687d97c443fa34509f6e3a29990":{
      "scriptId":"u0"},
    "26179c11b5b5451787d32dc39fdd5558":{
      "scriptId":"u1"},
    "e10044a113e84c71adc8e7f69afbb544":{
      "scriptId":"u2"},
    "53f16ff38c6c46deac873520a31e311b":{
      "scriptId":"u3"},
    "0f2c218c5aa046c795bdb34a1654f021":{
      "scriptId":"u4"},
    "8909e1fc39e64a31985704d738c80626":{
      "scriptId":"u5"},
    "a6e99e08e7774734847f0e6f189f26ec":{
      "scriptId":"u6"},
    "8b8f29b6a7fb4a28a30c045cb0d20858":{
      "scriptId":"u7"},
    "40e57155703a4a0484e030ecf6014015":{
      "scriptId":"u8"},
    "4a17d642c89843ecafcdd733a439dceb":{
      "scriptId":"u9"},
    "79439eb61e5f4209b924c99f99d37c9b":{
      "scriptId":"u10"},
    "ae8a7a85b1ff4b27ace408e922b1295a":{
      "scriptId":"u11"},
    "ef481bc038774dd8a20e225004f8e820":{
      "scriptId":"u12"},
    "41ae526ab49942c598f4e3af282987fc":{
      "scriptId":"u13"},
    "92f675606e7040d79a009c77bd417d02":{
      "scriptId":"u14"},
    "30a13f255f3242ed83889c98d123f18b":{
      "scriptId":"u15"},
    "d306e91c086845bb94011c0e17345372":{
      "scriptId":"u16"},
    "8f161d7235ab40ce9bdee901f20a56ae":{
      "scriptId":"u17"},
    "3b92c0edcb344bc1ab6bbb79964deadb":{
      "scriptId":"u18"},
    "afc4552c01e24823b052afa0b0efc65e":{
      "scriptId":"u19"},
    "10bac34d7b694141be2c58324b237579":{
      "scriptId":"u20"},
    "0cb770228bec47159835a7c4257a5a13":{
      "scriptId":"u21"},
    "52e4d209dae0480797895a4dcd6ac394":{
      "scriptId":"u22"},
    "28b6654e17f543ed869655367026d6b6":{
      "scriptId":"u23"},
    "c60a523d28bb47eab8b8486dd79a192e":{
      "scriptId":"u24"},
    "c77e497d7e594dc4b1d15fb7cdeedb14":{
      "scriptId":"u25"},
    "02387695a48846708fbc888932310d19":{
      "scriptId":"u26"},
    "14ff5894e2794199b9b22d4f8fd2e6cc":{
      "scriptId":"u27"},
    "56a832b236fc4e808944719068c83db4":{
      "scriptId":"u28"},
    "7a716ce1495f44b88dd8c7219ea2ae40":{
      "scriptId":"u29"},
    "ddaece9303b74170a9c1bfa64902fc46":{
      "scriptId":"u30"},
    "2023565275f3486b8d5bdbdc172d1572":{
      "scriptId":"u31"},
    "c2d60aab52ae4d40a9a2592e45e7d651":{
      "scriptId":"u32"},
    "638827f49eec4635aeca9d5804f30fbe":{
      "scriptId":"u33"},
    "f005dd7e249b45b7be29787749fbf9ad":{
      "scriptId":"u34"},
    "c972e90d6069496c95d86d58cba737f3":{
      "scriptId":"u35"},
    "6f91e83a2301439eadb41e9dd256b799":{
      "scriptId":"u36"},
    "9e5c92c1797643a89932794379dbdfe0":{
      "scriptId":"u37"},
    "35a8c32f298646bbba256ee4cfb3a063":{
      "scriptId":"u38"},
    "787ba5f308574ce9a2a8388175a22020":{
      "scriptId":"u39"},
    "11bc1fa471474515a8d4941338a73154":{
      "scriptId":"u40"},
    "caaab580b1ac4438ab104092890e0663":{
      "scriptId":"u41"},
    "188983a1c5bd4aa2ac193e3454e232e3":{
      "scriptId":"u42"},
    "7aeca6716200459099e0bab24445ca44":{
      "scriptId":"u43"},
    "54d846a80627489c823cc33e41fb56dc":{
      "scriptId":"u44"},
    "ec7cee0fd31a4d06affbedd6cbfe4ced":{
      "scriptId":"u45"},
    "64b35c9929ab4af1aa09b5f5a6a8f8a3":{
      "scriptId":"u46"},
    "a4ecb514d5374eeda1d19de918c2bd92":{
      "scriptId":"u47"},
    "efb6d1fff5c64cf6abf4069609f27055":{
      "scriptId":"u48"},
    "2cde77e8318b4bb2984600ad8f427a06":{
      "scriptId":"u49"},
    "d3b4f697ed2c4cdc811288bf94b706e5":{
      "scriptId":"u50"},
    "4ca8e58429f24684bc9018e1f19890cf":{
      "scriptId":"u51"},
    "f16037b3f09b41e98a1a8c1b87a05a3a":{
      "scriptId":"u52"},
    "516f357c41b841c394ac45ddb08c42f0":{
      "scriptId":"u53"},
    "c79fa6b65cb24a06a561281396fccfa6":{
      "scriptId":"u54"},
    "5f62700b89b74dd4981e067891d27a08":{
      "scriptId":"u55"},
    "fc721b926bd049769f0970ba10c09bcd":{
      "scriptId":"u56"},
    "a7c310e1299345a988be3a66e8d63b11":{
      "scriptId":"u57"},
    "241d9d632c6641b3a42780858523688c":{
      "scriptId":"u58"},
    "2e52d34548e34c58badf8bcf42f9f55b":{
      "scriptId":"u59"},
    "571a086155854138a364143dcf27b665":{
      "scriptId":"u60"},
    "b5b6dcbf323d406997184da1cab52dda":{
      "scriptId":"u61"},
    "e1ced4f849724d5c8f63aa1ab2d9eac1":{
      "scriptId":"u62"},
    "7d8399cd26494de1897aa91d203b0088":{
      "scriptId":"u63"},
    "475c6db0fd244bdf9f80a1ca2e1700e3":{
      "scriptId":"u64"},
    "033718ea26024b38ae85ff32030005ff":{
      "scriptId":"u65"},
    "dbe1b17673464af39c6c10e2329566f8":{
      "scriptId":"u66"},
    "c09210e45d3b46448831931aa07b05e9":{
      "scriptId":"u67"},
    "e9efca7249d3488a9b29a12d22f202df":{
      "scriptId":"u68"},
    "f9998806a8e54d92ad0954c4e3398c71":{
      "scriptId":"u69"},
    "8bbed4487bd74f7b8137c230f3ea4a3e":{
      "scriptId":"u70"},
    "65d480ca01d643f9ab548067b914312e":{
      "scriptId":"u71"},
    "6d84e84c3d194a0894849c999bac75a4":{
      "scriptId":"u72"},
    "daadb5f55e2640858b1f8a393f83fc6c":{
      "scriptId":"u73"},
    "3ea4d44c5492494c95e6de314447b73e":{
      "scriptId":"u74"},
    "fc130210089f4dd789b57244562a0e0a":{
      "scriptId":"u75"},
    "6f723560148b48d5a0ddff784506ab58":{
      "scriptId":"u76"},
    "4166fa9ff84449ac9f2ac7580547a339":{
      "scriptId":"u77"},
    "dfa1b6a4ea77483b88d708f8ec5de9c8":{
      "scriptId":"u78"},
    "b335c7f0310c4a94acabe6ad4b54a5d3":{
      "scriptId":"u79"},
    "d3419172d50944fa846c9d7e8679c845":{
      "scriptId":"u80"},
    "c237dd0a5d644923b4ae6ad0c3fae7d1":{
      "scriptId":"u81"},
    "3696fca1f5e14f3facddb50d93961d92":{
      "scriptId":"u82"},
    "d03caf9a9e554524b13ee250b14570b3":{
      "scriptId":"u83"},
    "02f12da3c18147f4bfc4b64f77f701e4":{
      "scriptId":"u84"},
    "989e4c36a09643b8bc285350df0f8eb8":{
      "scriptId":"u85"},
    "f8ff1474e7304f63afc6c4c80cbfb137":{
      "scriptId":"u86"},
    "4baa82b6e55e441ea75b32181a3f56d7":{
      "scriptId":"u87"},
    "542be88dc80a4c61bfec33c910487f0e":{
      "scriptId":"u88"},
    "60ad2074dc8349e182c7237d4b292956":{
      "scriptId":"u89"},
    "7edfff7a71704181882fa03a3f7bcf0b":{
      "scriptId":"u90"},
    "b29cb74c06264b3c835cdb05a4893d55":{
      "scriptId":"u91"},
    "ca743f6ac9a14823ba4db44085606f54":{
      "scriptId":"u92"},
    "9c48fa296a864a3cb5c1f5e68571360a":{
      "scriptId":"u93"},
    "d318d9f271f8418e8029c0e1e54a7aba":{
      "scriptId":"u94"},
    "bed0fb35494b416fb32a7cdb3c8dc8fe":{
      "scriptId":"u95"},
    "0c7f041fed414386a7667245557442e0":{
      "scriptId":"u96"},
    "e55640edfa05482ea341d030a4dc4140":{
      "scriptId":"u97"},
    "0516d18106794e08b82fde10a666086d":{
      "scriptId":"u98"},
    "aed875f970464e1891bac9970e171bdd":{
      "scriptId":"u99"},
    "92ff2282b72c48ac9a92f3d94ab18316":{
      "scriptId":"u100"},
    "54adcdd22266426893848cf179534c39":{
      "scriptId":"u101"},
    "c288a972c99f4fff9266750bda431d7f":{
      "scriptId":"u102"},
    "0ba3e107da1c49b2ad1c19457be17ab0":{
      "scriptId":"u103"},
    "cbc6e051c65e44978ea79caba27e00ee":{
      "scriptId":"u104"},
    "2056b483107842e9a5ffc2f0aa8c65e0":{
      "scriptId":"u105"},
    "c34bd4ca92dc4948865f6fa25d7d0d6c":{
      "scriptId":"u106"},
    "7ee5551fe0a64d42b41e896f5fff8a3a":{
      "scriptId":"u107"},
    "fe510b3d6ea54d499cf6d0e83c8b952b":{
      "scriptId":"u108"},
    "ccc473e6da184a7d8d050c3b7147de5a":{
      "scriptId":"u109"},
    "1e899c70552149978f72877eea0decdc":{
      "scriptId":"u110"},
    "6e8546c5d30c455f88fee8f4dcdcd8a0":{
      "scriptId":"u111"},
    "8c4b63b4911d458eac9cab8097469c08":{
      "scriptId":"u112"},
    "1f4ecdb772e642bcb1883a13779e8d72":{
      "scriptId":"u113"},
    "ba81c0f73e7648459307853e005de993":{
      "scriptId":"u114"},
    "efbc602a49a64994b66ef9b2eb93c1f9":{
      "scriptId":"u115"},
    "9369f20b3dbe4b8a8924efbbcc99f99d":{
      "scriptId":"u116"},
    "478381b255bf4366a1899677eb2ffbcb":{
      "scriptId":"u117"},
    "7fb0bc981e804e15b1df4a1c91c7d0c2":{
      "scriptId":"u118"},
    "c009a8490d02470d89c2d7af5926d2c4":{
      "scriptId":"u119"},
    "b7de546801294d06b240e3abfc5c33dd":{
      "scriptId":"u120"},
    "239d6ab3c5b84320a73d70f4dcc49e8b":{
      "scriptId":"u121"},
    "60556747577943dc92f9f6a84f835132":{
      "scriptId":"u122"},
    "c0329c30d8a348f188c893422feda1e1":{
      "scriptId":"u123"},
    "1a19dc46981a41948c6ffa6aa0e8b89b":{
      "scriptId":"u124"},
    "aa9384b9cb234e89959ab0aa60592daf":{
      "scriptId":"u125"},
    "a3ea952a01fa4d32840a4b22af9a9114":{
      "scriptId":"u126"}}});