$axure.loadCurrentPage({
  "url":"考勤_1.html",
  "generationDate":new Date(1515736337998),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"feae550753bf47368a617de02311b5b8",
    "type":"Axure:Page",
    "name":"考勤",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fe5b67bd2c134f3299029f0e58db47b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":76},
            "size":{
              "width":750,
              "height":1294}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a978cd034a544ffcb3cbf68d7f0586b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":76},
                "size":{
                  "width":750,
                  "height":1294}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务名称1/u0.png"}},
{
          "id":"1984a5b588824eaca4df44c1dfff3ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"34px",
            "location":{
              "x":50,
              "y":76},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8bda0ecee444d0c9f7ae15619580467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"34px",
                "location":{
                  "x":50,
                  "y":76},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"fe365eecfa6840629c3b57b8d6660398",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":96},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84623987ae8648469f9f11005d3b66a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":96},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务名称1",
                      "target":{
                        "targetType":"page",
                        "url":"任务名称1_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"7b9e8d13a71e470c861d572063eb7045",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":50,
              "y":36},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f880dea6ad84b2a987cf8707f02ba0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":50,
                  "y":36},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"d676222d73a34b308bd2fe7ce608aa57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":149.5,
              "y":340},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b3adc7f6e0f4320b4b5bf28b3f98bd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149.5,
                  "y":340},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 签到",
                      "target":{
                        "targetType":"page",
                        "url":"签到.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"01acbf4420f74b36add39cb8dc321e23",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":140,
              "y":518},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e12998941b004761a1dd3195e21fff1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":140,
                  "y":518},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad99acfc2e52423eb4fd674a42bae46f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":549.5,
              "y":340},
            "size":{
              "width":150,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71bb76a765c14a518571c187c7ae5d7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":549.5,
                  "y":340},
                "size":{
                  "width":150,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 请假",
                      "target":{
                        "targetType":"page",
                        "url":"请假.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/任务名称1/u8.png"}},
{
          "id":"0fd71f4130b34331a697365e40bc3909",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"center",
            "lineSpacing":"72px",
            "location":{
              "x":540,
              "y":518},
            "size":{
              "width":171,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e1a4be724cc4630bac0a169ab1d3b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"center",
                "lineSpacing":"72px",
                "location":{
                  "x":540,
                  "y":518},
                "size":{
                  "width":171,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"76d7cbc109df46e6b5af8620d0244c2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"72px",
            "location":{
              "x":50,
              "y":165},
            "size":{
              "width":750,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09ecdb0783664fad88a531bc38a2f706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"72px",
                "location":{
                  "x":50,
                  "y":165},
                "size":{
                  "width":750,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤_1/u16.png"}},
{
          "id":"cbe27d3bcd6246a0a608cca5fa866911",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":200.5},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u110_end.png",
            "line~":"images/学生管理/u46_line.png"}},
{
          "id":"6a2d264f656448a3b11436742617fcfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"36px",
            "location":{
              "x":980,
              "y":146},
            "size":{
              "width":660,
              "height":119}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38467c78f8d2405fa4b383973286e0ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"36px",
                "location":{
                  "x":980,
                  "y":146},
                "size":{
                  "width":660,
                  "height":119}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/考勤_1/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fe5b67bd2c134f3299029f0e58db47b9":{
      "scriptId":"u0"},
    "a978cd034a544ffcb3cbf68d7f0586b2":{
      "scriptId":"u1"},
    "1984a5b588824eaca4df44c1dfff3ff7":{
      "scriptId":"u2"},
    "e8bda0ecee444d0c9f7ae15619580467":{
      "scriptId":"u3"},
    "fe365eecfa6840629c3b57b8d6660398":{
      "scriptId":"u4"},
    "84623987ae8648469f9f11005d3b66a0":{
      "scriptId":"u5"},
    "7b9e8d13a71e470c861d572063eb7045":{
      "scriptId":"u6"},
    "7f880dea6ad84b2a987cf8707f02ba0c":{
      "scriptId":"u7"},
    "d676222d73a34b308bd2fe7ce608aa57":{
      "scriptId":"u8"},
    "2b3adc7f6e0f4320b4b5bf28b3f98bd3":{
      "scriptId":"u9"},
    "01acbf4420f74b36add39cb8dc321e23":{
      "scriptId":"u10"},
    "e12998941b004761a1dd3195e21fff1b":{
      "scriptId":"u11"},
    "ad99acfc2e52423eb4fd674a42bae46f":{
      "scriptId":"u12"},
    "71bb76a765c14a518571c187c7ae5d7c":{
      "scriptId":"u13"},
    "0fd71f4130b34331a697365e40bc3909":{
      "scriptId":"u14"},
    "0e1a4be724cc4630bac0a169ab1d3b51":{
      "scriptId":"u15"},
    "76d7cbc109df46e6b5af8620d0244c2e":{
      "scriptId":"u16"},
    "09ecdb0783664fad88a531bc38a2f706":{
      "scriptId":"u17"},
    "cbe27d3bcd6246a0a608cca5fa866911":{
      "scriptId":"u18"},
    "6a2d264f656448a3b11436742617fcfc":{
      "scriptId":"u19"},
    "38467c78f8d2405fa4b383973286e0ee":{
      "scriptId":"u20"}}});