$axure.loadCurrentPage({
  "url":"任务内容.html",
  "generationDate":new Date(1515736334524),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba6600fa4b55450da5356703014c22a6",
    "type":"Axure:Page",
    "name":"任务内容",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"78fa91dfdfe546b9bdda25d04e36b04e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":1333}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d164cee696047ccbdab704747edcb08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":1333}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务内容/u0.png"}},
{
          "id":"86ade422b3c247098d4dc5d3e3b4c34d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":80,
              "y":70},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0076c75b13b44b26a953e09c2297dac1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":80,
                  "y":70},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"315d525995d04a0d998c0a8527875846",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":80,
              "y":110},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e447556ad6e04fa1bb648740849f1f42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":80,
                  "y":110},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"1d75fdc5c8734791a8ebb304e17ae7af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":96,
              "y":131},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8699d74597854c72b4897d21c7dc61ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":96,
                  "y":131},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建育人活动",
                      "target":{
                        "targetType":"page",
                        "url":"创建育人活动.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"41a63610c15c401586e41464d881672d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":133,
              "y":123},
            "size":{
              "width":130,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c1dcac030a41d2a939958ef8219475",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":123},
                "size":{
                  "width":130,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建任务",
                      "target":{
                        "targetType":"page",
                        "url":"创建任务.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9aaeb95f10ca495b8a072e3937be767d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":710,
              "y":125},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2821938bd32e44d49397aa22d57ab240",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":710,
                  "y":125},
                "size":{
                  "width":100,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"88a951cf4e6941fe85ceee8971644e07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":91,
              "y":205},
            "size":{
              "width":730,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ebb1d2eec75483286672c5c62196705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":91,
                  "y":205},
                "size":{
                  "width":730,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "78fa91dfdfe546b9bdda25d04e36b04e":{
      "scriptId":"u0"},
    "5d164cee696047ccbdab704747edcb08":{
      "scriptId":"u1"},
    "86ade422b3c247098d4dc5d3e3b4c34d":{
      "scriptId":"u2"},
    "0076c75b13b44b26a953e09c2297dac1":{
      "scriptId":"u3"},
    "315d525995d04a0d998c0a8527875846":{
      "scriptId":"u4"},
    "e447556ad6e04fa1bb648740849f1f42":{
      "scriptId":"u5"},
    "1d75fdc5c8734791a8ebb304e17ae7af":{
      "scriptId":"u6"},
    "8699d74597854c72b4897d21c7dc61ad":{
      "scriptId":"u7"},
    "41a63610c15c401586e41464d881672d":{
      "scriptId":"u8"},
    "66c1dcac030a41d2a939958ef8219475":{
      "scriptId":"u9"},
    "9aaeb95f10ca495b8a072e3937be767d":{
      "scriptId":"u10"},
    "2821938bd32e44d49397aa22d57ab240":{
      "scriptId":"u11"},
    "88a951cf4e6941fe85ceee8971644e07":{
      "scriptId":"u12"},
    "8ebb1d2eec75483286672c5c62196705":{
      "scriptId":"u13"}}});