$axure.loadCurrentPage({
  "url":"阅读任务.html",
  "generationDate":new Date(1515736335021),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7fa8cbde5c6a46b4b1a023969a388867",
    "type":"Axure:Page",
    "name":"阅读任务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0bd3441b7c754546845b0bb61cacbe97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":50},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc659b59b52946439b3c9275ab65ae1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":50},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"216bf12f4cc34bbc9ae45c9aba015be4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":140,
              "y":50},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a05a008e66334df3a867fd54e845232f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":140,
                  "y":50},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"5fc7d3ff4b9e494b8da2e6ff8fd1a705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":140,
              "y":90},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4cfad89c25f4a11aa847eb48e63d862",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":140,
                  "y":90},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"49457bb23fd140f69cd0c5d25ea6575d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":111},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33ebdc255aaa4d939236ef9d76ffd4bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":111},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务库",
                      "target":{
                        "targetType":"page",
                        "url":"任务库.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"cc244edb24f944c1ac1ad50a5755e274",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":170,
              "y":194},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f7db7ec2e9540a58f03fb5de19bd2b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":170,
                  "y":194},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"061df7b65ea84dd192721b7ba5302e64",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":140,
              "y":529},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"9259cdb96366407fae138d78021d1d07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":142,
              "y":273},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c46a4ac659ae45ab9fb7230e1e72af25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":142,
                  "y":273},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"9b5fb0b8ae9246ada6b9a773d6e0cd64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":142,
              "y":430},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d32123dff04f87bee921da876185fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":142,
                  "y":430},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"531497af80d74905b1c15d403d32a7db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":170,
              "y":469},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7fd4dca8b8a4bf1a346c71cf4778970",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":170,
                  "y":469},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cca0cebce7564647a4dfd0c7c144cf8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF00CC00,
              "opacity":1},
            "location":{
              "x":143,
              "y":950},
            "size":{
              "width":746,
              "height":71},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95f40f5a9684423ba7526f412e9c592a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF00CC00,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":950},
                "size":{
                  "width":746,
                  "height":71},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u382.png"}},
{
          "id":"1f39e2b7f21f4a5f9790b884fe469050",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":143,
              "y":1054},
            "size":{
              "width":746,
              "height":87},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1733433f25ef42f793a62c70c691782d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":143,
                  "y":1054},
                "size":{
                  "width":746,
                  "height":87},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u54.png"}},
{
          "id":"f7bd48aff57d4b8184ffed00a755766b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":143,
              "y":914},
            "size":{
              "width":746,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd1f6981c4b14a4bb037fc760404909c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":143,
                  "y":914},
                "size":{
                  "width":746,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u56.png"}},
{
          "id":"dd3304e541e0434382e6f8a5948dc1e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":143,
              "y":1021},
            "size":{
              "width":746,
              "height":34},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c47cf1f0813b46bebaeeba5688dbd3a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":143,
                  "y":1021},
                "size":{
                  "width":746,
                  "height":34},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/晨训任务/u56.png"}},
{
          "id":"29e16667dc994655a60163e40e791c13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":142,
              "y":1141},
            "size":{
              "width":746,
              "height":239},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bce45f7f65064b0cadff0a8e7c250f02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":142,
                  "y":1141},
                "size":{
                  "width":746,
                  "height":239},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/阅读任务/u25.png"}},
{
          "id":"506a2bf0ef574f539517cf553b356690",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":1002},
            "size":{
              "width":200,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/我的事项/u44_line.png"}},
{
          "id":"f1c48780157c45978be34c88e295e4bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":1130,
              "y":50},
            "size":{
              "width":750,
              "height":1334}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf45e612095b48a99068cbee84f022a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1130,
                  "y":50},
                "size":{
                  "width":750,
                  "height":1334}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u0.png"}},
{
          "id":"19f8fb9f67c14f6c923b4b313a407908",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":1130,
              "y":50},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae96ae41bcb481b9c32ab161bdb8839",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":1130,
                  "y":50},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"2bc07d7883ba4ac6938f3ce54bcb12a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":1130,
              "y":90},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bbe2e0d18c941f2a4b0b9bd97bcd190",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":1130,
                  "y":90},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"4863358139f94a289797564360114a8d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1146,
              "y":111},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"514598bb1ff44e2e9632dfa006a053d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1146,
                  "y":111},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"fd57389686964d4fbcf663eca29880e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1160,
              "y":194},
            "size":{
              "width":140,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d013a6c686f4ab0997016eaffb238d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1160,
                  "y":194},
                "size":{
                  "width":140,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d8f34a9c5ae44b6874ee37f7c037641",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":1289,
              "y":201},
            "size":{
              "width":410,
              "height":45}},
          "adaptiveStyles":{
}},
{
          "id":"faabb139c88644f59c664e432fc47448",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "location":{
              "x":1677,
              "y":194},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdc9f2648c084870aef6c209931c93ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "location":{
                  "x":1677,
                  "y":194},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c014832c94524141ac69cf6695f8cf4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1160,
              "y":313},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f506b64ab544b34a3eb42f02cb794e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1160,
                  "y":313},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92a051e5b841497d8279b917d5fef354",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":1590,
              "y":313},
            "size":{
              "width":235,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733adeb80a59424183435a3229ff10ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":1590,
                  "y":313},
                "size":{
                  "width":235,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 任务内容",
                      "target":{
                        "targetType":"page",
                        "url":"任务内容.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcddf8e18c6b4992b65fd4d854f9b75e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "location":{
              "x":1130,
              "y":1314},
            "size":{
              "width":750,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c196e6d3344405da2ef631c264759ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "location":{
                  "x":1130,
                  "y":1314},
                "size":{
                  "width":750,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u26.png"}},
{
          "id":"48f7cc9cc6714eb38ace7e9c25b5874c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1132,
              "y":273},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de2c7b9dca254a98b63476052b4ccfd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1132,
                  "y":273},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"817908fbe5134c1194e9c5bf7c080cb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1132,
              "y":382},
            "size":{
              "width":746,
              "height":31},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"400ac2805deb40ca9829e83a020c7e72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1132,
                  "y":382},
                "size":{
                  "width":746,
                  "height":31},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/创建任务/u156.png"}},
{
          "id":"e44d3173362345b49e3ccd34e202d81e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1130,
              "y":564},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"60c69d22023e4154b4be7a8cbea3285e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1160,
              "y":504},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f31feac2124520b4c0ddb79572b843",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1160,
                  "y":504},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a61b7cc8406427f8674b4751007608b",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":1130,
              "y":571},
            "size":{
              "width":746,
              "height":560}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"6e5b4189bdc34bb69d5ae2935d044e6a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8f94e0caea994bdc948a7ac9cd603e3a",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":750,
                      "height":560},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65762a8aadc2425bb4f7529b337e83bb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":750,
                          "height":560},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u29.png"}},
{
                  "id":"17040f4f08a34c5a9de753dcd24f5b6e",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":750,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0c5081c96c44e4d9fc9763b9cb1f32c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":750,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u31.png"}},
{
                  "id":"10e70011091642eaacbd8fe45f053f5f",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":410,
                      "y":28},
                    "size":{
                      "width":170,
                      "height":45}},
                  "adaptiveStyles":{
}},
{
                  "id":"5936d9abd2eb4b1b8be24bd438bdcfc8",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":610,
                      "y":20},
                    "size":{
                      "width":40,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e69a83aeb484b73a9f92c2258568975",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":610,
                          "y":20},
                        "size":{
                          "width":40,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dc8197d058b740d290580cd8c30fc22b",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":20},
                    "size":{
                      "width":124,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb5d523b770a4e61bce483c48050a969",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":20},
                        "size":{
                          "width":124,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b4d5f026ad194ae2893a9531c9569503",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":130},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f24cbefa97e04ef2adec1755de0fcf6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":130},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"23fb9c083ce348d49bb4edc525c3fe7d",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":210},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8a47064e1ed4404956f33cf304c0fff",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":210},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"d708ae3bf69d4d08bb5281494045b26b",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":290},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67f06a644fbc47219029d2ff8e75aeb0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":290},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"1ab2ca65e0694ccd9241f7c477e27cf6",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":160},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7aef0c8b91a54530bb1f02d9a0af5930",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":160},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"390ad7c179354ef9b307ca6894fc4b52",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":235},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da200a0a510c43ac968ab4b594ff327c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":235},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"1cd2ac7dd48647ba89978d3d387eb605",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":320},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c1307cafa324ff6841da5edf4e7dc13",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":320},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"8ea7323838d844ec8143bc0683c6ebc8",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":380,
                      "y":144},
                    "size":{
                      "width":330,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f67846739e54b22a127f6473a9f566d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":380,
                          "y":144},
                        "size":{
                          "width":330,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5617eac2a6ed4eaab009d6e7b1676b3c",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":220},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b721bbe94554132913d24b436cafb8e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":220},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"56377d6539af46669a6f865e56577e9e",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":400},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9d30d5af8f54ce4acb89bf9a05b2618",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":400},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"830632731a404b08aa54cd34cd6e9c5f",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":480},
                    "size":{
                      "width":750,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a9f30d72eac4eaba1a59fdaa6c62cce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":480},
                        "size":{
                          "width":750,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建任务/u38.png"}},
{
                  "id":"587beb4794b94bf982e9f0885270f24a",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":425},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62142362657f4cf49d6c79a92a0f26e0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":425},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"4b87c3c72a6949d59fc04d1df0baa3ee",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "location":{
                      "x":30,
                      "y":510},
                    "size":{
                      "width":230,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4335d5cf081547c0a72ea91123661576",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "location":{
                          "x":30,
                          "y":510},
                        "size":{
                          "width":230,
                          "height":28}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"dd070e2481794cbdb6f7492e9c6c155a",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":383,
                      "y":220},
                    "size":{
                      "width":330,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10ba896b006a465fa149004300784f23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":383,
                          "y":220},
                        "size":{
                          "width":330,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3997e3d53b274932befd011f0add87f4",
                  "label":"",
                  "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":383,
                      "y":300},
                    "size":{
                      "width":330,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ca507e760c348508c339da92854ed86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0a61b7cc8406427f8674b4751007608b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":383,
                          "y":300},
                        "size":{
                          "width":330,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"19d094356fff4e91a42df94588a7e086",
          "label":"交作业动态面板",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":142,
              "y":535},
            "size":{
              "width":750,
              "height":400}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"38c001e5a0d5481d8316bef9950957de",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c4aab0e81e114644b179b047c665fa99",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":750,
                      "height":379},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"58a9ec5de222468a841390ced9d8a8fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":750,
                          "height":379},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/阅读任务/u93.png"}},
{
                  "id":"1901507eaeba4048b435b504708ed64a",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c01f2006819d4bd3a919b60a5bc73ed6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"80d35eaa7b7244ba8327105bd99f77c2",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":540,
                      "y":11},
                    "size":{
                      "width":45,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c32616ed07234719a40ed3402f8d9f71",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":540,
                          "y":11},
                        "size":{
                          "width":45,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"98795f5c124246d7a8218dfa4592115a",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":11},
                    "size":{
                      "width":124,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c111f923bfb44fdb9daaedc85644d4fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":11},
                        "size":{
                          "width":124,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ee77066530074865b625ab1291861c8a",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":110},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c19d74a8cf044511b4d4bca48a52aa4c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":110},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"cafa3e2a89ba40ea9beab4a11d5bdf21",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":380,
                      "y":124},
                    "size":{
                      "width":330,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5e68277ac344dfb89c5fa688671921e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":380,
                          "y":124},
                        "size":{
                          "width":330,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8f9749f3fbfc46ddba217592f94bf309",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF6B6B6B,
                      "opacity":1},
                    "lineSpacing":"36px",
                    "location":{
                      "x":381,
                      "y":200},
                    "size":{
                      "width":332,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"904e37ddf0de449c8c1f24f12b0bf80d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF6B6B6B,
                          "opacity":1},
                        "lineSpacing":"36px",
                        "location":{
                          "x":381,
                          "y":200},
                        "size":{
                          "width":332,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3ebd53e05d0e4bb9b5adcb19d237b1b5",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":220},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09ee5312a7224043b2d8baf28201307c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":220},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"a30069da8d8d4c499143345023db8637",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":120},
                    "size":{
                      "width":184,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ed382c76d70483caadf46a34af48fa0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":120},
                        "size":{
                          "width":184,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c426fa256aa42d99cd398434aeaeaed",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":230},
                    "size":{
                      "width":184,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"442cdf89fdf84d9585dc9575ae6f6809",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":230},
                        "size":{
                          "width":184,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f8ca95e353894abe85db6c35c9eaf839",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":299},
                    "size":{
                      "width":746,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"10c7fcd50f7e476baa21d51f76a04684",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":299},
                        "size":{
                          "width":746,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/晨训任务/u90.png"}},
{
                  "id":"60ab51fc95cb46458c20ce671a5ebb1e",
                  "label":"",
                  "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"24px",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":26,
                      "y":310},
                    "size":{
                      "width":184,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ff78cfbbe6354c88bf564f6c00075746",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"19d094356fff4e91a42df94588a7e086",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"24px",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":26,
                          "y":310},
                        "size":{
                          "width":184,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"28d3358e0e994e7689e3e30e10f795b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "lineSpacing":"48px",
            "location":{
              "x":170,
              "y":325},
            "size":{
              "width":680,
              "height":105}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad692820d2924a5889b7488b2deafa3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "lineSpacing":"48px",
                "location":{
                  "x":170,
                  "y":325},
                "size":{
                  "width":680,
                  "height":105}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0102545c786f4034805c0f0370bc2b1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "location":{
              "x":1162,
              "y":420},
            "size":{
              "width":214,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52651d158ceb419ea3fd0d7adfb4db13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "location":{
                  "x":1162,
                  "y":420},
                "size":{
                  "width":214,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60eb492427bd4b1b8d01f8965c49ecc3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":1132,
              "y":484},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0bd3441b7c754546845b0bb61cacbe97":{
      "scriptId":"u0"},
    "fc659b59b52946439b3c9275ab65ae1b":{
      "scriptId":"u1"},
    "216bf12f4cc34bbc9ae45c9aba015be4":{
      "scriptId":"u2"},
    "a05a008e66334df3a867fd54e845232f":{
      "scriptId":"u3"},
    "5fc7d3ff4b9e494b8da2e6ff8fd1a705":{
      "scriptId":"u4"},
    "b4cfad89c25f4a11aa847eb48e63d862":{
      "scriptId":"u5"},
    "49457bb23fd140f69cd0c5d25ea6575d":{
      "scriptId":"u6"},
    "33ebdc255aaa4d939236ef9d76ffd4bf":{
      "scriptId":"u7"},
    "cc244edb24f944c1ac1ad50a5755e274":{
      "scriptId":"u8"},
    "9f7db7ec2e9540a58f03fb5de19bd2b2":{
      "scriptId":"u9"},
    "061df7b65ea84dd192721b7ba5302e64":{
      "scriptId":"u10"},
    "9259cdb96366407fae138d78021d1d07":{
      "scriptId":"u11"},
    "c46a4ac659ae45ab9fb7230e1e72af25":{
      "scriptId":"u12"},
    "9b5fb0b8ae9246ada6b9a773d6e0cd64":{
      "scriptId":"u13"},
    "d7d32123dff04f87bee921da876185fd":{
      "scriptId":"u14"},
    "531497af80d74905b1c15d403d32a7db":{
      "scriptId":"u15"},
    "a7fd4dca8b8a4bf1a346c71cf4778970":{
      "scriptId":"u16"},
    "cca0cebce7564647a4dfd0c7c144cf8f":{
      "scriptId":"u17"},
    "95f40f5a9684423ba7526f412e9c592a":{
      "scriptId":"u18"},
    "1f39e2b7f21f4a5f9790b884fe469050":{
      "scriptId":"u19"},
    "1733433f25ef42f793a62c70c691782d":{
      "scriptId":"u20"},
    "f7bd48aff57d4b8184ffed00a755766b":{
      "scriptId":"u21"},
    "cd1f6981c4b14a4bb037fc760404909c":{
      "scriptId":"u22"},
    "dd3304e541e0434382e6f8a5948dc1e3":{
      "scriptId":"u23"},
    "c47cf1f0813b46bebaeeba5688dbd3a5":{
      "scriptId":"u24"},
    "29e16667dc994655a60163e40e791c13":{
      "scriptId":"u25"},
    "bce45f7f65064b0cadff0a8e7c250f02":{
      "scriptId":"u26"},
    "506a2bf0ef574f539517cf553b356690":{
      "scriptId":"u27"},
    "f1c48780157c45978be34c88e295e4bd":{
      "scriptId":"u28"},
    "bf45e612095b48a99068cbee84f022a7":{
      "scriptId":"u29"},
    "19f8fb9f67c14f6c923b4b313a407908":{
      "scriptId":"u30"},
    "4ae96ae41bcb481b9c32ab161bdb8839":{
      "scriptId":"u31"},
    "2bc07d7883ba4ac6938f3ce54bcb12a5":{
      "scriptId":"u32"},
    "5bbe2e0d18c941f2a4b0b9bd97bcd190":{
      "scriptId":"u33"},
    "4863358139f94a289797564360114a8d":{
      "scriptId":"u34"},
    "514598bb1ff44e2e9632dfa006a053d6":{
      "scriptId":"u35"},
    "fd57389686964d4fbcf663eca29880e1":{
      "scriptId":"u36"},
    "2d013a6c686f4ab0997016eaffb238d7":{
      "scriptId":"u37"},
    "7d8f34a9c5ae44b6874ee37f7c037641":{
      "scriptId":"u38"},
    "faabb139c88644f59c664e432fc47448":{
      "scriptId":"u39"},
    "fdc9f2648c084870aef6c209931c93ad":{
      "scriptId":"u40"},
    "c014832c94524141ac69cf6695f8cf4d":{
      "scriptId":"u41"},
    "1f506b64ab544b34a3eb42f02cb794e4":{
      "scriptId":"u42"},
    "92a051e5b841497d8279b917d5fef354":{
      "scriptId":"u43"},
    "733adeb80a59424183435a3229ff10ea":{
      "scriptId":"u44"},
    "bcddf8e18c6b4992b65fd4d854f9b75e":{
      "scriptId":"u45"},
    "1c196e6d3344405da2ef631c264759ce":{
      "scriptId":"u46"},
    "48f7cc9cc6714eb38ace7e9c25b5874c":{
      "scriptId":"u47"},
    "de2c7b9dca254a98b63476052b4ccfd4":{
      "scriptId":"u48"},
    "817908fbe5134c1194e9c5bf7c080cb4":{
      "scriptId":"u49"},
    "400ac2805deb40ca9829e83a020c7e72":{
      "scriptId":"u50"},
    "e44d3173362345b49e3ccd34e202d81e":{
      "scriptId":"u51"},
    "60c69d22023e4154b4be7a8cbea3285e":{
      "scriptId":"u52"},
    "e7f31feac2124520b4c0ddb79572b843":{
      "scriptId":"u53"},
    "0a61b7cc8406427f8674b4751007608b":{
      "scriptId":"u54"},
    "8f94e0caea994bdc948a7ac9cd603e3a":{
      "scriptId":"u55"},
    "65762a8aadc2425bb4f7529b337e83bb":{
      "scriptId":"u56"},
    "17040f4f08a34c5a9de753dcd24f5b6e":{
      "scriptId":"u57"},
    "d0c5081c96c44e4d9fc9763b9cb1f32c":{
      "scriptId":"u58"},
    "10e70011091642eaacbd8fe45f053f5f":{
      "scriptId":"u59"},
    "5936d9abd2eb4b1b8be24bd438bdcfc8":{
      "scriptId":"u60"},
    "9e69a83aeb484b73a9f92c2258568975":{
      "scriptId":"u61"},
    "dc8197d058b740d290580cd8c30fc22b":{
      "scriptId":"u62"},
    "bb5d523b770a4e61bce483c48050a969":{
      "scriptId":"u63"},
    "b4d5f026ad194ae2893a9531c9569503":{
      "scriptId":"u64"},
    "f24cbefa97e04ef2adec1755de0fcf6a":{
      "scriptId":"u65"},
    "23fb9c083ce348d49bb4edc525c3fe7d":{
      "scriptId":"u66"},
    "f8a47064e1ed4404956f33cf304c0fff":{
      "scriptId":"u67"},
    "d708ae3bf69d4d08bb5281494045b26b":{
      "scriptId":"u68"},
    "67f06a644fbc47219029d2ff8e75aeb0":{
      "scriptId":"u69"},
    "1ab2ca65e0694ccd9241f7c477e27cf6":{
      "scriptId":"u70"},
    "7aef0c8b91a54530bb1f02d9a0af5930":{
      "scriptId":"u71"},
    "390ad7c179354ef9b307ca6894fc4b52":{
      "scriptId":"u72"},
    "da200a0a510c43ac968ab4b594ff327c":{
      "scriptId":"u73"},
    "1cd2ac7dd48647ba89978d3d387eb605":{
      "scriptId":"u74"},
    "1c1307cafa324ff6841da5edf4e7dc13":{
      "scriptId":"u75"},
    "8ea7323838d844ec8143bc0683c6ebc8":{
      "scriptId":"u76"},
    "3f67846739e54b22a127f6473a9f566d":{
      "scriptId":"u77"},
    "5617eac2a6ed4eaab009d6e7b1676b3c":{
      "scriptId":"u78"},
    "7b721bbe94554132913d24b436cafb8e":{
      "scriptId":"u79"},
    "56377d6539af46669a6f865e56577e9e":{
      "scriptId":"u80"},
    "e9d30d5af8f54ce4acb89bf9a05b2618":{
      "scriptId":"u81"},
    "830632731a404b08aa54cd34cd6e9c5f":{
      "scriptId":"u82"},
    "6a9f30d72eac4eaba1a59fdaa6c62cce":{
      "scriptId":"u83"},
    "587beb4794b94bf982e9f0885270f24a":{
      "scriptId":"u84"},
    "62142362657f4cf49d6c79a92a0f26e0":{
      "scriptId":"u85"},
    "4b87c3c72a6949d59fc04d1df0baa3ee":{
      "scriptId":"u86"},
    "4335d5cf081547c0a72ea91123661576":{
      "scriptId":"u87"},
    "dd070e2481794cbdb6f7492e9c6c155a":{
      "scriptId":"u88"},
    "10ba896b006a465fa149004300784f23":{
      "scriptId":"u89"},
    "3997e3d53b274932befd011f0add87f4":{
      "scriptId":"u90"},
    "2ca507e760c348508c339da92854ed86":{
      "scriptId":"u91"},
    "19d094356fff4e91a42df94588a7e086":{
      "scriptId":"u92"},
    "c4aab0e81e114644b179b047c665fa99":{
      "scriptId":"u93"},
    "58a9ec5de222468a841390ced9d8a8fd":{
      "scriptId":"u94"},
    "1901507eaeba4048b435b504708ed64a":{
      "scriptId":"u95"},
    "c01f2006819d4bd3a919b60a5bc73ed6":{
      "scriptId":"u96"},
    "80d35eaa7b7244ba8327105bd99f77c2":{
      "scriptId":"u97"},
    "c32616ed07234719a40ed3402f8d9f71":{
      "scriptId":"u98"},
    "98795f5c124246d7a8218dfa4592115a":{
      "scriptId":"u99"},
    "c111f923bfb44fdb9daaedc85644d4fb":{
      "scriptId":"u100"},
    "ee77066530074865b625ab1291861c8a":{
      "scriptId":"u101"},
    "c19d74a8cf044511b4d4bca48a52aa4c":{
      "scriptId":"u102"},
    "cafa3e2a89ba40ea9beab4a11d5bdf21":{
      "scriptId":"u103"},
    "d5e68277ac344dfb89c5fa688671921e":{
      "scriptId":"u104"},
    "8f9749f3fbfc46ddba217592f94bf309":{
      "scriptId":"u105"},
    "904e37ddf0de449c8c1f24f12b0bf80d":{
      "scriptId":"u106"},
    "3ebd53e05d0e4bb9b5adcb19d237b1b5":{
      "scriptId":"u107"},
    "09ee5312a7224043b2d8baf28201307c":{
      "scriptId":"u108"},
    "a30069da8d8d4c499143345023db8637":{
      "scriptId":"u109"},
    "2ed382c76d70483caadf46a34af48fa0":{
      "scriptId":"u110"},
    "8c426fa256aa42d99cd398434aeaeaed":{
      "scriptId":"u111"},
    "442cdf89fdf84d9585dc9575ae6f6809":{
      "scriptId":"u112"},
    "f8ca95e353894abe85db6c35c9eaf839":{
      "scriptId":"u113"},
    "10c7fcd50f7e476baa21d51f76a04684":{
      "scriptId":"u114"},
    "60ab51fc95cb46458c20ce671a5ebb1e":{
      "scriptId":"u115"},
    "ff78cfbbe6354c88bf564f6c00075746":{
      "scriptId":"u116"},
    "28d3358e0e994e7689e3e30e10f795b4":{
      "scriptId":"u117"},
    "ad692820d2924a5889b7488b2deafa3d":{
      "scriptId":"u118"},
    "0102545c786f4034805c0f0370bc2b1c":{
      "scriptId":"u119"},
    "52651d158ceb419ea3fd0d7adfb4db13":{
      "scriptId":"u120"},
    "60eb492427bd4b1b8d01f8965c49ecc3":{
      "scriptId":"u121"}}});