$axure.loadCurrentPage({
  "url":"任务详情.html",
  "generationDate":new Date(1515736339322),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"523136f37abc4604a90cfe0fd0e2f9c4",
    "type":"Axure:Page",
    "name":"任务详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"060b4001e1ff430ba4d4eb3c076823b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":200,
              "y":210},
            "size":{
              "width":750,
              "height":1010}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4a62b161c6f40d887695bf02c88f8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":200,
                  "y":210},
                "size":{
                  "width":750,
                  "height":1010}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务详情/u0.png"}},
{
          "id":"92cc56e45c2142b9a3254540f3432e32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"32px",
            "location":{
              "x":200,
              "y":120},
            "size":{
              "width":750,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c2dd2e5ab744a3956e8e521f0fd933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"32px",
                "location":{
                  "x":200,
                  "y":120},
                "size":{
                  "width":750,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u2.png"}},
{
          "id":"7980022de15f448cbe3e57a10f187bf9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":140},
            "size":{
              "width":44,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bd06a951f924f0288bce7a59aa2e8d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":140},
                "size":{
                  "width":44,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的事项",
                      "target":{
                        "targetType":"page",
                        "url":"我的事项_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/管理员、老师/u4.png"}},
{
          "id":"561de8a59a0943c5b050e802074106a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":200,
              "y":80},
            "size":{
              "width":750,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7cedf4dcb5e457b9763e95609b8f29c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":200,
                  "y":80},
                "size":{
                  "width":750,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u6.png"}},
{
          "id":"08719fa8ead0436cb9a11a2ad9511720",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":202,
              "y":304},
            "size":{
              "width":746,
              "height":134},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0cbf92954f34027a914a017706e9a87",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":202,
                  "y":304},
                "size":{
                  "width":746,
                  "height":134},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u46.png"}},
{
          "id":"40190b51b0f54d3db3757e6140dc0d63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"middle",
            "location":{
              "x":202,
              "y":210},
            "size":{
              "width":746,
              "height":75},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"693599a2d8a247439e90814fc50fa180",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":210},
                "size":{
                  "width":746,
                  "height":75},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u343.png"}},
{
          "id":"e39d120d78244bdeb95c1de6833c3900",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "lineSpacing":"48px",
            "location":{
              "x":202,
              "y":464},
            "size":{
              "width":746,
              "height":410},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be8b9a6475074343a968c76fcb8319ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "lineSpacing":"48px",
                "location":{
                  "x":202,
                  "y":464},
                "size":{
                  "width":746,
                  "height":410},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u345.png"}},
{
          "id":"cb0188503b94420cbb6660bca70e66e5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":202,
              "y":618},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"10b9e503b3524523bed40b56789babdb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":202,
              "y":532},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"b70a3a4a9cfa4f61af65c2f52e6ea039",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":202,
              "y":782},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"cfe4d470fc874cc7b7dd1abbd18b9521",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":202,
              "y":702},
            "size":{
              "width":748,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u347_line.png"}},
{
          "id":"db3bfa334ff5420b89fcebb840fe1a83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":230,
              "y":472},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ead10942e78f434d916ea75befe4ca04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":230,
                  "y":472},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cec9ae7bc8a4993bfe06f67dbbcdc2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":230,
              "y":552},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea4b5b8268b407798bdfc378039818a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":230,
                  "y":552},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e911eb4ec8944d987a14bba5f04b59b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":230,
              "y":638},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82632cc67ed242498cca7e649b0ad35a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":230,
                  "y":638},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8012f9a3d86a4a0c9c54521b8a5e06ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":230,
              "y":722},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04c631015ec846f2aef9d227c5b8974b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":230,
                  "y":722},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f6c7ebd786404000bc0f29dd34c909e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "lineSpacing":"36px",
            "location":{
              "x":230,
              "y":804},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f9f2bcef0e84acf94d165e68406659f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "lineSpacing":"36px",
                "location":{
                  "x":230,
                  "y":804},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d564f4d4a6f34a3baa5070315fd0450c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "verticalAlignment":"top",
            "lineSpacing":"48px",
            "location":{
              "x":202,
              "y":894},
            "size":{
              "width":746,
              "height":316},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984ec059c012421ab6c921a58a405e9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "verticalAlignment":"top",
                "lineSpacing":"48px",
                "location":{
                  "x":202,
                  "y":894},
                "size":{
                  "width":746,
                  "height":316},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/任务详情/u28.png"}},
{
          "id":"99ecb057caaf4e388c4f025e692daeea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":218,
              "y":978},
            "size":{
              "width":84,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b77dddac55bd47478e700cd3cef6b444",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":978},
                "size":{
                  "width":84,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbc0fe8162844527872bd5e4962a6bc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":696,
              "y":978},
            "size":{
              "width":85,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e35abb1bc434d58b988b8b0adf23617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":696,
                  "y":978},
                "size":{
                  "width":85,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0de91e228ec49ff83596fdc023bb5a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":826,
              "y":978},
            "size":{
              "width":85,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6eb4c0111ba4e2e9c5992c4bbd62b50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":826,
                  "y":978},
                "size":{
                  "width":85,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c478b2c66934e42bf82d5e9b90f52dd",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":792,
              "y":1002},
            "size":{
              "width":49,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u369_end.png",
            "line~":"images/管理员、老师/u369_line.png"}},
{
          "id":"1fcfc8fc4eac41f7aab14dd4f93aa505",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":200,
              "y":1038},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"e111e801fac14b258cf5b257bcecd425",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.3",
            "location":{
              "x":198,
              "y":1124},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"5cff7dc1bc10446f802252374e7c8983",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":214,
              "y":1062},
            "size":{
              "width":194,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"956c76a7690c4457884d4187154d83db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":214,
                  "y":1062},
                "size":{
                  "width":194,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b985723411474fcb9cae6353b4b07361",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":214,
              "y":1144},
            "size":{
              "width":164,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d205e8fbbd0443d7b2f34af9cacd403e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":214,
                  "y":1144},
                "size":{
                  "width":164,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df09d467a1514559b33db8d023bcc5cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":718,
              "y":1062},
            "size":{
              "width":216,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2f5066a971c43939ee50ef29be0607a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":718,
                  "y":1062},
                "size":{
                  "width":216,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25c501dfd8654c0fa9902dbcb4c3a7b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":718,
              "y":1142},
            "size":{
              "width":216,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f566fc27530d42469faf770f978e9768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":718,
                  "y":1142},
                "size":{
                  "width":216,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30801917f087469580eaa2001090f9d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"24px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":218,
              "y":900},
            "size":{
              "width":300,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0626fd61faf84683bc2661fa837c43ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"24px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":218,
                  "y":900},
                "size":{
                  "width":300,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcaf8eb9ac164a79ad5a6b37507ec91f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "opacity":"0.2",
            "location":{
              "x":198,
              "y":968},
            "size":{
              "width":750,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/管理员、老师/u370_line.png"}},
{
          "id":"69cdbb938634425292c8de9a3fee2a47",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":922,
              "y":657},
            "size":{
              "width":99,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"images/管理员、老师/u316_end.png",
            "line~":"images/管理员、老师/u390_line.png"}},
{
          "id":"694cd0504ed443d2a6fba851e13ca0bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "lineSpacing":"48px",
            "location":{
              "x":1032,
              "y":612},
            "size":{
              "width":488,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2f42b76aa1a4305b13ce62d10904a7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "lineSpacing":"48px",
                "location":{
                  "x":1032,
                  "y":612},
                "size":{
                  "width":488,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/管理员、老师/u534.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "060b4001e1ff430ba4d4eb3c076823b1":{
      "scriptId":"u0"},
    "c4a62b161c6f40d887695bf02c88f8a5":{
      "scriptId":"u1"},
    "92cc56e45c2142b9a3254540f3432e32":{
      "scriptId":"u2"},
    "69c2dd2e5ab744a3956e8e521f0fd933":{
      "scriptId":"u3"},
    "7980022de15f448cbe3e57a10f187bf9":{
      "scriptId":"u4"},
    "3bd06a951f924f0288bce7a59aa2e8d1":{
      "scriptId":"u5"},
    "561de8a59a0943c5b050e802074106a1":{
      "scriptId":"u6"},
    "b7cedf4dcb5e457b9763e95609b8f29c":{
      "scriptId":"u7"},
    "08719fa8ead0436cb9a11a2ad9511720":{
      "scriptId":"u8"},
    "a0cbf92954f34027a914a017706e9a87":{
      "scriptId":"u9"},
    "40190b51b0f54d3db3757e6140dc0d63":{
      "scriptId":"u10"},
    "693599a2d8a247439e90814fc50fa180":{
      "scriptId":"u11"},
    "e39d120d78244bdeb95c1de6833c3900":{
      "scriptId":"u12"},
    "be8b9a6475074343a968c76fcb8319ed":{
      "scriptId":"u13"},
    "cb0188503b94420cbb6660bca70e66e5":{
      "scriptId":"u14"},
    "10b9e503b3524523bed40b56789babdb":{
      "scriptId":"u15"},
    "b70a3a4a9cfa4f61af65c2f52e6ea039":{
      "scriptId":"u16"},
    "cfe4d470fc874cc7b7dd1abbd18b9521":{
      "scriptId":"u17"},
    "db3bfa334ff5420b89fcebb840fe1a83":{
      "scriptId":"u18"},
    "ead10942e78f434d916ea75befe4ca04":{
      "scriptId":"u19"},
    "2cec9ae7bc8a4993bfe06f67dbbcdc2a":{
      "scriptId":"u20"},
    "1ea4b5b8268b407798bdfc378039818a":{
      "scriptId":"u21"},
    "7e911eb4ec8944d987a14bba5f04b59b":{
      "scriptId":"u22"},
    "82632cc67ed242498cca7e649b0ad35a":{
      "scriptId":"u23"},
    "8012f9a3d86a4a0c9c54521b8a5e06ba":{
      "scriptId":"u24"},
    "04c631015ec846f2aef9d227c5b8974b":{
      "scriptId":"u25"},
    "f6c7ebd786404000bc0f29dd34c909e4":{
      "scriptId":"u26"},
    "0f9f2bcef0e84acf94d165e68406659f":{
      "scriptId":"u27"},
    "d564f4d4a6f34a3baa5070315fd0450c":{
      "scriptId":"u28"},
    "984ec059c012421ab6c921a58a405e9d":{
      "scriptId":"u29"},
    "99ecb057caaf4e388c4f025e692daeea":{
      "scriptId":"u30"},
    "b77dddac55bd47478e700cd3cef6b444":{
      "scriptId":"u31"},
    "bbc0fe8162844527872bd5e4962a6bc9":{
      "scriptId":"u32"},
    "6e35abb1bc434d58b988b8b0adf23617":{
      "scriptId":"u33"},
    "b0de91e228ec49ff83596fdc023bb5a1":{
      "scriptId":"u34"},
    "f6eb4c0111ba4e2e9c5992c4bbd62b50":{
      "scriptId":"u35"},
    "4c478b2c66934e42bf82d5e9b90f52dd":{
      "scriptId":"u36"},
    "1fcfc8fc4eac41f7aab14dd4f93aa505":{
      "scriptId":"u37"},
    "e111e801fac14b258cf5b257bcecd425":{
      "scriptId":"u38"},
    "5cff7dc1bc10446f802252374e7c8983":{
      "scriptId":"u39"},
    "956c76a7690c4457884d4187154d83db":{
      "scriptId":"u40"},
    "b985723411474fcb9cae6353b4b07361":{
      "scriptId":"u41"},
    "d205e8fbbd0443d7b2f34af9cacd403e":{
      "scriptId":"u42"},
    "df09d467a1514559b33db8d023bcc5cf":{
      "scriptId":"u43"},
    "a2f5066a971c43939ee50ef29be0607a":{
      "scriptId":"u44"},
    "25c501dfd8654c0fa9902dbcb4c3a7b3":{
      "scriptId":"u45"},
    "f566fc27530d42469faf770f978e9768":{
      "scriptId":"u46"},
    "30801917f087469580eaa2001090f9d5":{
      "scriptId":"u47"},
    "0626fd61faf84683bc2661fa837c43ed":{
      "scriptId":"u48"},
    "dcaf8eb9ac164a79ad5a6b37507ec91f":{
      "scriptId":"u49"},
    "69cdbb938634425292c8de9a3fee2a47":{
      "scriptId":"u50"},
    "694cd0504ed443d2a6fba851e13ca0bb":{
      "scriptId":"u51"},
    "d2f42b76aa1a4305b13ce62d10904a7d":{
      "scriptId":"u52"}}});